/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  GetSessions200,
  GetSessionsId200,
  GetSessionsParams,
  GetSessionsPreview200,
  GetSessionsPreviewParams,
  PostSessions201,
  PostSessionsAddStudent200,
  PostSessionsAddStudentBody,
  PostSessionsAddTeacher200,
  PostSessionsAddTeacherBody,
  PostSessionsBody,
  PostSessionsOnlineSessionToken200,
  PostSessionsOnlineSessionTokenBody,
  PostSessionsRemoveStudent200,
  PostSessionsRemoveStudentBody,
  PostSessionsRemoveTeacher200,
  PostSessionsRemoveTeacherBody,
  PutSessionsId200,
  PutSessionsIdBody
} from '.././schemas';



type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class SessionsService {
  constructor(
    private http: HttpClient,
  ) {}/**
 * Retrieve a list of all sessions with optional filtering
 * @summary Get all sessions
 */
 getSessions<TData = GetSessions200>(
    params?: GetSessionsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getSessions<TData = GetSessions200>(
    params?: GetSessionsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getSessions<TData = GetSessions200>(
    params?: GetSessionsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getSessions<TData = GetSessions200>(
    params?: GetSessionsParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/sessions`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Create a new session with the given details
 * @summary Create a new session
 */
 postSessions<TData = PostSessions201>(
    postSessionsBody: PostSessionsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postSessions<TData = PostSessions201>(
    postSessionsBody: PostSessionsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postSessions<TData = PostSessions201>(
    postSessionsBody: PostSessionsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postSessions<TData = PostSessions201>(
    postSessionsBody: PostSessionsBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/sessions`,
      postSessionsBody,options
    );
  }
/**
 * Retrieve details of a specific session by ID
 * @summary Get session by ID
 */
 getSessionsId<TData = GetSessionsId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getSessionsId<TData = GetSessionsId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getSessionsId<TData = GetSessionsId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getSessionsId<TData = GetSessionsId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/sessions/${id}`,options
    );
  }
/**
 * Update details of a specific session
 * @summary Update session
 */
 putSessionsId<TData = PutSessionsId200>(
    id: string,
    putSessionsIdBody: PutSessionsIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    putSessionsId<TData = PutSessionsId200>(
    id: string,
    putSessionsIdBody: PutSessionsIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    putSessionsId<TData = PutSessionsId200>(
    id: string,
    putSessionsIdBody: PutSessionsIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;putSessionsId<TData = PutSessionsId200>(
    id: string,
    putSessionsIdBody: PutSessionsIdBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.put<TData>(
      `http://localhost:3193/v1/sessions/${id}`,
      putSessionsIdBody,options
    );
  }
/**
 * Delete a specific session
 * @summary Delete session
 */
 deleteSessionsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    deleteSessionsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    deleteSessionsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;deleteSessionsId<TData = void>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.delete<TData>(
      `http://localhost:3193/v1/sessions/${id}`,options
    );
  }
/**
 * Add a student to a specific session
 * @summary Add student to session
 */
 postSessionsAddStudent<TData = PostSessionsAddStudent200>(
    postSessionsAddStudentBody: PostSessionsAddStudentBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postSessionsAddStudent<TData = PostSessionsAddStudent200>(
    postSessionsAddStudentBody: PostSessionsAddStudentBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postSessionsAddStudent<TData = PostSessionsAddStudent200>(
    postSessionsAddStudentBody: PostSessionsAddStudentBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postSessionsAddStudent<TData = PostSessionsAddStudent200>(
    postSessionsAddStudentBody: PostSessionsAddStudentBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/sessions/add-student`,
      postSessionsAddStudentBody,options
    );
  }
/**
 * Remove a student from a specific session
 * @summary Remove student from session
 */
 postSessionsRemoveStudent<TData = PostSessionsRemoveStudent200>(
    postSessionsRemoveStudentBody: PostSessionsRemoveStudentBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postSessionsRemoveStudent<TData = PostSessionsRemoveStudent200>(
    postSessionsRemoveStudentBody: PostSessionsRemoveStudentBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postSessionsRemoveStudent<TData = PostSessionsRemoveStudent200>(
    postSessionsRemoveStudentBody: PostSessionsRemoveStudentBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postSessionsRemoveStudent<TData = PostSessionsRemoveStudent200>(
    postSessionsRemoveStudentBody: PostSessionsRemoveStudentBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/sessions/remove-student`,
      postSessionsRemoveStudentBody,options
    );
  }
/**
 * Add a teacher to a specific session
 * @summary Add teacher to session
 */
 postSessionsAddTeacher<TData = PostSessionsAddTeacher200>(
    postSessionsAddTeacherBody: PostSessionsAddTeacherBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postSessionsAddTeacher<TData = PostSessionsAddTeacher200>(
    postSessionsAddTeacherBody: PostSessionsAddTeacherBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postSessionsAddTeacher<TData = PostSessionsAddTeacher200>(
    postSessionsAddTeacherBody: PostSessionsAddTeacherBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postSessionsAddTeacher<TData = PostSessionsAddTeacher200>(
    postSessionsAddTeacherBody: PostSessionsAddTeacherBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/sessions/add-teacher`,
      postSessionsAddTeacherBody,options
    );
  }
/**
 * Remove a teacher from a specific session
 * @summary Remove teacher from session
 */
 postSessionsRemoveTeacher<TData = PostSessionsRemoveTeacher200>(
    postSessionsRemoveTeacherBody: PostSessionsRemoveTeacherBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postSessionsRemoveTeacher<TData = PostSessionsRemoveTeacher200>(
    postSessionsRemoveTeacherBody: PostSessionsRemoveTeacherBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postSessionsRemoveTeacher<TData = PostSessionsRemoveTeacher200>(
    postSessionsRemoveTeacherBody: PostSessionsRemoveTeacherBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postSessionsRemoveTeacher<TData = PostSessionsRemoveTeacher200>(
    postSessionsRemoveTeacherBody: PostSessionsRemoveTeacherBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/sessions/remove-teacher`,
      postSessionsRemoveTeacherBody,options
    );
  }
/**
 * Get a preview of sessions that would be generated for given parameters
 * @summary Preview recurring sessions
 */
 getSessionsPreview<TData = GetSessionsPreview200>(
    params: GetSessionsPreviewParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getSessionsPreview<TData = GetSessionsPreview200>(
    params: GetSessionsPreviewParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getSessionsPreview<TData = GetSessionsPreview200>(
    params: GetSessionsPreviewParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getSessionsPreview<TData = GetSessionsPreview200>(
    params: GetSessionsPreviewParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/sessions/preview`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Create a specific token for online session
 * @summary Create a token (JWT) for online session
 */
 postSessionsOnlineSessionToken<TData = PostSessionsOnlineSessionToken200>(
    postSessionsOnlineSessionTokenBody: PostSessionsOnlineSessionTokenBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postSessionsOnlineSessionToken<TData = PostSessionsOnlineSessionToken200>(
    postSessionsOnlineSessionTokenBody: PostSessionsOnlineSessionTokenBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postSessionsOnlineSessionToken<TData = PostSessionsOnlineSessionToken200>(
    postSessionsOnlineSessionTokenBody: PostSessionsOnlineSessionTokenBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postSessionsOnlineSessionToken<TData = PostSessionsOnlineSessionToken200>(
    postSessionsOnlineSessionTokenBody: PostSessionsOnlineSessionTokenBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/sessions/online-session-token`,
      postSessionsOnlineSessionTokenBody,options
    );
  }
};

export type GetSessionsClientResult = NonNullable<GetSessions200>
export type PostSessionsClientResult = NonNullable<PostSessions201>
export type GetSessionsIdClientResult = NonNullable<GetSessionsId200>
export type PutSessionsIdClientResult = NonNullable<PutSessionsId200>
export type DeleteSessionsIdClientResult = NonNullable<void>
export type PostSessionsAddStudentClientResult = NonNullable<PostSessionsAddStudent200>
export type PostSessionsRemoveStudentClientResult = NonNullable<PostSessionsRemoveStudent200>
export type PostSessionsAddTeacherClientResult = NonNullable<PostSessionsAddTeacher200>
export type PostSessionsRemoveTeacherClientResult = NonNullable<PostSessionsRemoveTeacher200>
export type GetSessionsPreviewClientResult = NonNullable<GetSessionsPreview200>
export type PostSessionsOnlineSessionTokenClientResult = NonNullable<PostSessionsOnlineSessionToken200>
