/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  GetBookmarksAppId200Item,
  PutBookmarksBody
} from '.././schemas';



type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class EbookBookmarksService {
  constructor(
    private http: HttpClient,
  ) {}/**
 * Retrieve a list of all bookmarks
 * @summary Get all bookmarks
 */
 getBookmarksAppId<TData = GetBookmarksAppId200Item[]>(
    appId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getBookmarksAppId<TData = GetBookmarksAppId200Item[]>(
    appId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getBookmarksAppId<TData = GetBookmarksAppId200Item[]>(
    appId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getBookmarksAppId<TData = GetBookmarksAppId200Item[]>(
    appId: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/bookmarks/${appId}`,options
    );
  }
/**
 * Replace the old list of bookmarks with the new one
 * @summary Update bookmarks
 */
 putBookmarks<TData = void>(
    putBookmarksBody: PutBookmarksBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    putBookmarks<TData = void>(
    putBookmarksBody: PutBookmarksBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    putBookmarks<TData = void>(
    putBookmarksBody: PutBookmarksBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;putBookmarks<TData = void>(
    putBookmarksBody: PutBookmarksBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.put<TData>(
      `http://localhost:3193/v1/bookmarks`,
      putBookmarksBody,options
    );
  }
};

export type GetBookmarksAppIdClientResult = NonNullable<GetBookmarksAppId200Item[]>
export type PutBookmarksClientResult = NonNullable<void>
