/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  DeleteMessagingAttachmentsId200,
  DeleteMessagingChatsChatId200,
  DeleteMessagingMessagesIdReactions200,
  DeleteMessagingMessagesIdReactionsParams,
  DeleteMessagingMessagesMessageId200,
  DeleteMessagingNotificationsId200,
  GetMessagingAttachmentsChatChatId200,
  GetMessagingAttachmentsChatChatIdParams,
  GetMessagingAttachmentsId200,
  GetMessagingAttachmentsMessageMessageId200,
  GetMessagingChats200,
  GetMessagingChatsChatId200,
  GetMessagingChatsChatIdMessages200,
  GetMessagingChatsChatIdMessagesParams,
  GetMessagingChatsParams,
  GetMessagingChatsParticipantsUserId200,
  GetMessagingIncomingUserId200,
  GetMessagingIncomingUserIdParams,
  GetMessagingMessages200,
  GetMessagingMessagesParams,
  GetMessagingNotifications200,
  GetMessagingNotificationsParams,
  GetMessagingNotificationsTypeType200,
  GetMessagingNotificationsTypeTypeParams,
  GetMessagingNotificationsUnreadCount200,
  GetMessagingSentUserId200,
  GetMessagingSentUserIdParams,
  PatchMessagingChatsChatId200,
  PatchMessagingChatsChatIdBody,
  PatchMessagingMessagesIdRead200,
  PatchMessagingMessagesMessageIdRead200,
  PatchMessagingMessagesMessageIdReadBody,
  PatchMessagingNotificationsIdRead200,
  PostMessagingAttachmentsStatus200,
  PostMessagingAttachmentsStatusBody,
  PostMessagingAttachmentsUpload201,
  PostMessagingAttachmentsUploadBody,
  PostMessagingChats201,
  PostMessagingChatsBody,
  PostMessagingChatsChatIdRead200,
  PostMessagingChatsChatIdReadBody,
  PostMessagingChatsChatIdResetUnread200,
  PostMessagingChatsChatIdResetUnreadBody,
  PostMessagingMessages201,
  PostMessagingMessagesBody,
  PostMessagingMessagesIdReactions201,
  PostMessagingMessagesIdReactionsBody,
  PostMessagingMessagesMessageIdDelivered200,
  PostMessagingMessagesMessageIdDeliveredBody,
  PostMessagingNotificationsClear200,
  PostMessagingNotificationsReadAll200,
  PostMessagingNotificationsSystem201,
  PostMessagingNotificationsSystemBody
} from '.././schemas';



type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class MessagingService {
  constructor(
    private http: HttpClient,
  ) {}/**
 * Get all chats for a specific user with populated participant details
 * @summary Get user chats
 */
 getMessagingChatsParticipantsUserId<TData = GetMessagingChatsParticipantsUserId200>(
    userId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getMessagingChatsParticipantsUserId<TData = GetMessagingChatsParticipantsUserId200>(
    userId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getMessagingChatsParticipantsUserId<TData = GetMessagingChatsParticipantsUserId200>(
    userId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getMessagingChatsParticipantsUserId<TData = GetMessagingChatsParticipantsUserId200>(
    userId: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/messaging/chats/participants/${userId}`,options
    );
  }
/**
 * Reset unread count for a user in a chat
 * @summary Reset unread count
 */
 postMessagingChatsChatIdResetUnread<TData = PostMessagingChatsChatIdResetUnread200>(
    chatId: string,
    postMessagingChatsChatIdResetUnreadBody: PostMessagingChatsChatIdResetUnreadBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postMessagingChatsChatIdResetUnread<TData = PostMessagingChatsChatIdResetUnread200>(
    chatId: string,
    postMessagingChatsChatIdResetUnreadBody: PostMessagingChatsChatIdResetUnreadBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postMessagingChatsChatIdResetUnread<TData = PostMessagingChatsChatIdResetUnread200>(
    chatId: string,
    postMessagingChatsChatIdResetUnreadBody: PostMessagingChatsChatIdResetUnreadBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postMessagingChatsChatIdResetUnread<TData = PostMessagingChatsChatIdResetUnread200>(
    chatId: string,
    postMessagingChatsChatIdResetUnreadBody: PostMessagingChatsChatIdResetUnreadBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/messaging/chats/${chatId}/reset-unread`,
      postMessagingChatsChatIdResetUnreadBody,options
    );
  }
/**
 * Retrieve details of a specific chat by ID
 * @summary Get chat by ID
 */
 getMessagingChatsChatId<TData = GetMessagingChatsChatId200>(
    chatId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getMessagingChatsChatId<TData = GetMessagingChatsChatId200>(
    chatId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getMessagingChatsChatId<TData = GetMessagingChatsChatId200>(
    chatId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getMessagingChatsChatId<TData = GetMessagingChatsChatId200>(
    chatId: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/messaging/chats/${chatId}`,options
    );
  }
/**
 * Update chat settings (user-specific or global)
 * @summary Update chat
 */
 patchMessagingChatsChatId<TData = PatchMessagingChatsChatId200>(
    chatId: string,
    patchMessagingChatsChatIdBody: PatchMessagingChatsChatIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchMessagingChatsChatId<TData = PatchMessagingChatsChatId200>(
    chatId: string,
    patchMessagingChatsChatIdBody: PatchMessagingChatsChatIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchMessagingChatsChatId<TData = PatchMessagingChatsChatId200>(
    chatId: string,
    patchMessagingChatsChatIdBody: PatchMessagingChatsChatIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchMessagingChatsChatId<TData = PatchMessagingChatsChatId200>(
    chatId: string,
    patchMessagingChatsChatIdBody: PatchMessagingChatsChatIdBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/messaging/chats/${chatId}`,
      patchMessagingChatsChatIdBody,options
    );
  }
/**
 * Delete a chat and all its messages
 * @summary Delete chat
 */
 deleteMessagingChatsChatId<TData = DeleteMessagingChatsChatId200>(
    chatId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    deleteMessagingChatsChatId<TData = DeleteMessagingChatsChatId200>(
    chatId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    deleteMessagingChatsChatId<TData = DeleteMessagingChatsChatId200>(
    chatId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;deleteMessagingChatsChatId<TData = DeleteMessagingChatsChatId200>(
    chatId: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.delete<TData>(
      `http://localhost:3193/v1/messaging/chats/${chatId}`,options
    );
  }
/**
 * List chats, optionally filtered by participant user id
 * @summary List chats
 */
 getMessagingChats<TData = GetMessagingChats200>(
    params?: GetMessagingChatsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getMessagingChats<TData = GetMessagingChats200>(
    params?: GetMessagingChatsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getMessagingChats<TData = GetMessagingChats200>(
    params?: GetMessagingChatsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getMessagingChats<TData = GetMessagingChats200>(
    params?: GetMessagingChatsParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/messaging/chats`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Create a new chat (direct or group)
 * @summary Create chat
 */
 postMessagingChats<TData = PostMessagingChats201>(
    postMessagingChatsBody: PostMessagingChatsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postMessagingChats<TData = PostMessagingChats201>(
    postMessagingChatsBody: PostMessagingChatsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postMessagingChats<TData = PostMessagingChats201>(
    postMessagingChatsBody: PostMessagingChatsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postMessagingChats<TData = PostMessagingChats201>(
    postMessagingChatsBody: PostMessagingChatsBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/messaging/chats`,
      postMessagingChatsBody,options
    );
  }
/**
 * Mark all messages in a chat as read for a user
 * @summary Mark chat as read
 */
 postMessagingChatsChatIdRead<TData = PostMessagingChatsChatIdRead200>(
    chatId: string,
    postMessagingChatsChatIdReadBody: PostMessagingChatsChatIdReadBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postMessagingChatsChatIdRead<TData = PostMessagingChatsChatIdRead200>(
    chatId: string,
    postMessagingChatsChatIdReadBody: PostMessagingChatsChatIdReadBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postMessagingChatsChatIdRead<TData = PostMessagingChatsChatIdRead200>(
    chatId: string,
    postMessagingChatsChatIdReadBody: PostMessagingChatsChatIdReadBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postMessagingChatsChatIdRead<TData = PostMessagingChatsChatIdRead200>(
    chatId: string,
    postMessagingChatsChatIdReadBody: PostMessagingChatsChatIdReadBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/messaging/chats/${chatId}/read`,
      postMessagingChatsChatIdReadBody,options
    );
  }
/**
 * Retrieve messages for a chat with pagination (legacy endpoint)
 * @summary Get messages by chat ID
 */
 getMessagingChatsChatIdMessages<TData = GetMessagingChatsChatIdMessages200>(
    chatId: string,
    params?: GetMessagingChatsChatIdMessagesParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getMessagingChatsChatIdMessages<TData = GetMessagingChatsChatIdMessages200>(
    chatId: string,
    params?: GetMessagingChatsChatIdMessagesParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getMessagingChatsChatIdMessages<TData = GetMessagingChatsChatIdMessages200>(
    chatId: string,
    params?: GetMessagingChatsChatIdMessagesParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getMessagingChatsChatIdMessages<TData = GetMessagingChatsChatIdMessages200>(
    chatId: string,
    params?: GetMessagingChatsChatIdMessagesParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/messaging/chats/${chatId}/messages`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Retrieve messages for a chat with optional filtering
 * @summary Get messages in a chat
 */
 getMessagingMessages<TData = GetMessagingMessages200>(
    params: GetMessagingMessagesParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getMessagingMessages<TData = GetMessagingMessages200>(
    params: GetMessagingMessagesParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getMessagingMessages<TData = GetMessagingMessages200>(
    params: GetMessagingMessagesParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getMessagingMessages<TData = GetMessagingMessages200>(
    params: GetMessagingMessagesParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/messaging/messages`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Send a new message to a chat
 * @summary Send message
 */
 postMessagingMessages<TData = PostMessagingMessages201>(
    postMessagingMessagesBody: PostMessagingMessagesBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postMessagingMessages<TData = PostMessagingMessages201>(
    postMessagingMessagesBody: PostMessagingMessagesBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postMessagingMessages<TData = PostMessagingMessages201>(
    postMessagingMessagesBody: PostMessagingMessagesBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postMessagingMessages<TData = PostMessagingMessages201>(
    postMessagingMessagesBody: PostMessagingMessagesBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/messaging/messages`,
      postMessagingMessagesBody,options
    );
  }
/**
 * Mark a single message as read
 * @summary Mark message as read
 */
 patchMessagingMessagesIdRead<TData = PatchMessagingMessagesIdRead200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchMessagingMessagesIdRead<TData = PatchMessagingMessagesIdRead200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchMessagingMessagesIdRead<TData = PatchMessagingMessagesIdRead200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchMessagingMessagesIdRead<TData = PatchMessagingMessagesIdRead200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/messaging/messages/${id}/read`,undefined,options
    );
  }
/**
 * Mark a message as delivered to a user
 * @summary Mark message as delivered
 */
 postMessagingMessagesMessageIdDelivered<TData = PostMessagingMessagesMessageIdDelivered200>(
    messageId: string,
    postMessagingMessagesMessageIdDeliveredBody: PostMessagingMessagesMessageIdDeliveredBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postMessagingMessagesMessageIdDelivered<TData = PostMessagingMessagesMessageIdDelivered200>(
    messageId: string,
    postMessagingMessagesMessageIdDeliveredBody: PostMessagingMessagesMessageIdDeliveredBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postMessagingMessagesMessageIdDelivered<TData = PostMessagingMessagesMessageIdDelivered200>(
    messageId: string,
    postMessagingMessagesMessageIdDeliveredBody: PostMessagingMessagesMessageIdDeliveredBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postMessagingMessagesMessageIdDelivered<TData = PostMessagingMessagesMessageIdDelivered200>(
    messageId: string,
    postMessagingMessagesMessageIdDeliveredBody: PostMessagingMessagesMessageIdDeliveredBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/messaging/messages/${messageId}/delivered`,
      postMessagingMessagesMessageIdDeliveredBody,options
    );
  }
/**
 * Mark a message as read by a user (alternative endpoint)
 * @summary Update read status
 */
 patchMessagingMessagesMessageIdRead<TData = PatchMessagingMessagesMessageIdRead200>(
    messageId: string,
    patchMessagingMessagesMessageIdReadBody: PatchMessagingMessagesMessageIdReadBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchMessagingMessagesMessageIdRead<TData = PatchMessagingMessagesMessageIdRead200>(
    messageId: string,
    patchMessagingMessagesMessageIdReadBody: PatchMessagingMessagesMessageIdReadBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchMessagingMessagesMessageIdRead<TData = PatchMessagingMessagesMessageIdRead200>(
    messageId: string,
    patchMessagingMessagesMessageIdReadBody: PatchMessagingMessagesMessageIdReadBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchMessagingMessagesMessageIdRead<TData = PatchMessagingMessagesMessageIdRead200>(
    messageId: string,
    patchMessagingMessagesMessageIdReadBody: PatchMessagingMessagesMessageIdReadBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/messaging/messages/${messageId}/read`,
      patchMessagingMessagesMessageIdReadBody,options
    );
  }
/**
 * Delete a message (only sender can delete)
 * @summary Delete message
 */
 deleteMessagingMessagesMessageId<TData = DeleteMessagingMessagesMessageId200>(
    messageId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    deleteMessagingMessagesMessageId<TData = DeleteMessagingMessagesMessageId200>(
    messageId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    deleteMessagingMessagesMessageId<TData = DeleteMessagingMessagesMessageId200>(
    messageId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;deleteMessagingMessagesMessageId<TData = DeleteMessagingMessagesMessageId200>(
    messageId: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.delete<TData>(
      `http://localhost:3193/v1/messaging/messages/${messageId}`,options
    );
  }
/**
 * Retrieve all incoming messages for a user with pagination
 * @summary Get incoming messages
 */
 getMessagingIncomingUserId<TData = GetMessagingIncomingUserId200>(
    userId: string,
    params?: GetMessagingIncomingUserIdParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getMessagingIncomingUserId<TData = GetMessagingIncomingUserId200>(
    userId: string,
    params?: GetMessagingIncomingUserIdParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getMessagingIncomingUserId<TData = GetMessagingIncomingUserId200>(
    userId: string,
    params?: GetMessagingIncomingUserIdParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getMessagingIncomingUserId<TData = GetMessagingIncomingUserId200>(
    userId: string,
    params?: GetMessagingIncomingUserIdParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/messaging/incoming/${userId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Retrieve all sent messages for a user with pagination
 * @summary Get sent messages
 */
 getMessagingSentUserId<TData = GetMessagingSentUserId200>(
    userId: string,
    params?: GetMessagingSentUserIdParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getMessagingSentUserId<TData = GetMessagingSentUserId200>(
    userId: string,
    params?: GetMessagingSentUserIdParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getMessagingSentUserId<TData = GetMessagingSentUserId200>(
    userId: string,
    params?: GetMessagingSentUserIdParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getMessagingSentUserId<TData = GetMessagingSentUserId200>(
    userId: string,
    params?: GetMessagingSentUserIdParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/messaging/sent/${userId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Add a reaction emoji to a message
 * @summary Add reaction
 */
 postMessagingMessagesIdReactions<TData = PostMessagingMessagesIdReactions201>(
    id: string,
    postMessagingMessagesIdReactionsBody: PostMessagingMessagesIdReactionsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postMessagingMessagesIdReactions<TData = PostMessagingMessagesIdReactions201>(
    id: string,
    postMessagingMessagesIdReactionsBody: PostMessagingMessagesIdReactionsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postMessagingMessagesIdReactions<TData = PostMessagingMessagesIdReactions201>(
    id: string,
    postMessagingMessagesIdReactionsBody: PostMessagingMessagesIdReactionsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postMessagingMessagesIdReactions<TData = PostMessagingMessagesIdReactions201>(
    id: string,
    postMessagingMessagesIdReactionsBody: PostMessagingMessagesIdReactionsBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/messaging/messages/${id}/reactions`,
      postMessagingMessagesIdReactionsBody,options
    );
  }
/**
 * Remove a reaction emoji from a message
 * @summary Remove reaction
 */
 deleteMessagingMessagesIdReactions<TData = DeleteMessagingMessagesIdReactions200>(
    id: string,
    params: DeleteMessagingMessagesIdReactionsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    deleteMessagingMessagesIdReactions<TData = DeleteMessagingMessagesIdReactions200>(
    id: string,
    params: DeleteMessagingMessagesIdReactionsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    deleteMessagingMessagesIdReactions<TData = DeleteMessagingMessagesIdReactions200>(
    id: string,
    params: DeleteMessagingMessagesIdReactionsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;deleteMessagingMessagesIdReactions<TData = DeleteMessagingMessagesIdReactions200>(
    id: string,
    params: DeleteMessagingMessagesIdReactionsParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.delete<TData>(
      `http://localhost:3193/v1/messaging/messages/${id}/reactions`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Upload files to a chat or message
 * @summary Upload attachments
 */
 postMessagingAttachmentsUpload<TData = PostMessagingAttachmentsUpload201>(
    postMessagingAttachmentsUploadBody: PostMessagingAttachmentsUploadBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postMessagingAttachmentsUpload<TData = PostMessagingAttachmentsUpload201>(
    postMessagingAttachmentsUploadBody: PostMessagingAttachmentsUploadBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postMessagingAttachmentsUpload<TData = PostMessagingAttachmentsUpload201>(
    postMessagingAttachmentsUploadBody: PostMessagingAttachmentsUploadBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postMessagingAttachmentsUpload<TData = PostMessagingAttachmentsUpload201>(
    postMessagingAttachmentsUploadBody: PostMessagingAttachmentsUploadBody, options?: HttpClientOptions
  ): Observable<TData>  {const formData = new FormData();
postMessagingAttachmentsUploadBody.files.forEach(value => formData.append('files', value));
formData.append('chatId', postMessagingAttachmentsUploadBody.chatId)
if(postMessagingAttachmentsUploadBody.messageId !== undefined) {
 formData.append('messageId', postMessagingAttachmentsUploadBody.messageId)
 }
if(postMessagingAttachmentsUploadBody.userId !== undefined) {
 formData.append('userId', postMessagingAttachmentsUploadBody.userId)
 }

    return this.http.post<TData>(
      `http://localhost:3193/v1/messaging/attachments/upload`,
      formData,options
    );
  }
/**
 * Get all attachments for a chat
 * @summary Get chat attachments
 */
 getMessagingAttachmentsChatChatId<TData = GetMessagingAttachmentsChatChatId200>(
    chatId: string,
    params?: GetMessagingAttachmentsChatChatIdParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getMessagingAttachmentsChatChatId<TData = GetMessagingAttachmentsChatChatId200>(
    chatId: string,
    params?: GetMessagingAttachmentsChatChatIdParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getMessagingAttachmentsChatChatId<TData = GetMessagingAttachmentsChatChatId200>(
    chatId: string,
    params?: GetMessagingAttachmentsChatChatIdParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getMessagingAttachmentsChatChatId<TData = GetMessagingAttachmentsChatChatId200>(
    chatId: string,
    params?: GetMessagingAttachmentsChatChatIdParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/messaging/attachments/chat/${chatId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Get all attachments for a message
 * @summary Get message attachments
 */
 getMessagingAttachmentsMessageMessageId<TData = GetMessagingAttachmentsMessageMessageId200>(
    messageId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getMessagingAttachmentsMessageMessageId<TData = GetMessagingAttachmentsMessageMessageId200>(
    messageId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getMessagingAttachmentsMessageMessageId<TData = GetMessagingAttachmentsMessageMessageId200>(
    messageId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getMessagingAttachmentsMessageMessageId<TData = GetMessagingAttachmentsMessageMessageId200>(
    messageId: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/messaging/attachments/message/${messageId}`,options
    );
  }
/**
 * Get single attachment by ID
 * @summary Get attachment
 */
 getMessagingAttachmentsId<TData = GetMessagingAttachmentsId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getMessagingAttachmentsId<TData = GetMessagingAttachmentsId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getMessagingAttachmentsId<TData = GetMessagingAttachmentsId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getMessagingAttachmentsId<TData = GetMessagingAttachmentsId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/messaging/attachments/${id}`,options
    );
  }
/**
 * Delete an attachment (only uploader can delete)
 * @summary Delete attachment
 */
 deleteMessagingAttachmentsId<TData = DeleteMessagingAttachmentsId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    deleteMessagingAttachmentsId<TData = DeleteMessagingAttachmentsId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    deleteMessagingAttachmentsId<TData = DeleteMessagingAttachmentsId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;deleteMessagingAttachmentsId<TData = DeleteMessagingAttachmentsId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.delete<TData>(
      `http://localhost:3193/v1/messaging/attachments/${id}`,options
    );
  }
/**
 * Download/redirect to attachment URL
 * @summary Download attachment
 */
 getMessagingAttachmentsIdDownload<TData = unknown>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getMessagingAttachmentsIdDownload<TData = unknown>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getMessagingAttachmentsIdDownload<TData = unknown>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getMessagingAttachmentsIdDownload<TData = unknown>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/messaging/attachments/${id}/download`,options
    );
  }
/**
 * Get upload status for multiple attachments
 * @summary Get upload status
 */
 postMessagingAttachmentsStatus<TData = PostMessagingAttachmentsStatus200>(
    postMessagingAttachmentsStatusBody: PostMessagingAttachmentsStatusBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postMessagingAttachmentsStatus<TData = PostMessagingAttachmentsStatus200>(
    postMessagingAttachmentsStatusBody: PostMessagingAttachmentsStatusBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postMessagingAttachmentsStatus<TData = PostMessagingAttachmentsStatus200>(
    postMessagingAttachmentsStatusBody: PostMessagingAttachmentsStatusBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postMessagingAttachmentsStatus<TData = PostMessagingAttachmentsStatus200>(
    postMessagingAttachmentsStatusBody: PostMessagingAttachmentsStatusBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/messaging/attachments/status`,
      postMessagingAttachmentsStatusBody,options
    );
  }
/**
 * Get notifications for a user with pagination
 * @summary Get user notifications
 */
 getMessagingNotifications<TData = GetMessagingNotifications200>(
    params?: GetMessagingNotificationsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getMessagingNotifications<TData = GetMessagingNotifications200>(
    params?: GetMessagingNotificationsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getMessagingNotifications<TData = GetMessagingNotifications200>(
    params?: GetMessagingNotificationsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getMessagingNotifications<TData = GetMessagingNotifications200>(
    params?: GetMessagingNotificationsParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/messaging/notifications`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Get unread notifications count for current user
 * @summary Get unread count
 */
 getMessagingNotificationsUnreadCount<TData = GetMessagingNotificationsUnreadCount200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getMessagingNotificationsUnreadCount<TData = GetMessagingNotificationsUnreadCount200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getMessagingNotificationsUnreadCount<TData = GetMessagingNotificationsUnreadCount200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getMessagingNotificationsUnreadCount<TData = GetMessagingNotificationsUnreadCount200>(
     options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/messaging/notifications/unread/count`,options
    );
  }
/**
 * Mark a single notification as read
 * @summary Mark notification as read
 */
 patchMessagingNotificationsIdRead<TData = PatchMessagingNotificationsIdRead200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchMessagingNotificationsIdRead<TData = PatchMessagingNotificationsIdRead200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchMessagingNotificationsIdRead<TData = PatchMessagingNotificationsIdRead200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchMessagingNotificationsIdRead<TData = PatchMessagingNotificationsIdRead200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/messaging/notifications/${id}/read`,undefined,options
    );
  }
/**
 * Mark all notifications as read for current user
 * @summary Mark all as read
 */
 postMessagingNotificationsReadAll<TData = PostMessagingNotificationsReadAll200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postMessagingNotificationsReadAll<TData = PostMessagingNotificationsReadAll200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postMessagingNotificationsReadAll<TData = PostMessagingNotificationsReadAll200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postMessagingNotificationsReadAll<TData = PostMessagingNotificationsReadAll200>(
     options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/messaging/notifications/read/all`,undefined,options
    );
  }
/**
 * Soft delete a notification
 * @summary Delete notification
 */
 deleteMessagingNotificationsId<TData = DeleteMessagingNotificationsId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    deleteMessagingNotificationsId<TData = DeleteMessagingNotificationsId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    deleteMessagingNotificationsId<TData = DeleteMessagingNotificationsId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;deleteMessagingNotificationsId<TData = DeleteMessagingNotificationsId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.delete<TData>(
      `http://localhost:3193/v1/messaging/notifications/${id}`,options
    );
  }
/**
 * Clear all notifications for current user (soft delete)
 * @summary Clear all notifications
 */
 postMessagingNotificationsClear<TData = PostMessagingNotificationsClear200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postMessagingNotificationsClear<TData = PostMessagingNotificationsClear200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postMessagingNotificationsClear<TData = PostMessagingNotificationsClear200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postMessagingNotificationsClear<TData = PostMessagingNotificationsClear200>(
     options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/messaging/notifications/clear`,undefined,options
    );
  }
/**
 * Create system notification for multiple users (admin only)
 * @summary Create system notification
 */
 postMessagingNotificationsSystem<TData = PostMessagingNotificationsSystem201>(
    postMessagingNotificationsSystemBody: PostMessagingNotificationsSystemBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postMessagingNotificationsSystem<TData = PostMessagingNotificationsSystem201>(
    postMessagingNotificationsSystemBody: PostMessagingNotificationsSystemBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postMessagingNotificationsSystem<TData = PostMessagingNotificationsSystem201>(
    postMessagingNotificationsSystemBody: PostMessagingNotificationsSystemBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postMessagingNotificationsSystem<TData = PostMessagingNotificationsSystem201>(
    postMessagingNotificationsSystemBody: PostMessagingNotificationsSystemBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/messaging/notifications/system`,
      postMessagingNotificationsSystemBody,options
    );
  }
/**
 * Get notifications filtered by type with pagination
 * @summary Get notifications by type
 */
 getMessagingNotificationsTypeType<TData = GetMessagingNotificationsTypeType200>(
    type: 'message' | 'mention' | 'system' | 'chat_invite' | 'user_online' | 'user_offline',
    params?: GetMessagingNotificationsTypeTypeParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getMessagingNotificationsTypeType<TData = GetMessagingNotificationsTypeType200>(
    type: 'message' | 'mention' | 'system' | 'chat_invite' | 'user_online' | 'user_offline',
    params?: GetMessagingNotificationsTypeTypeParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getMessagingNotificationsTypeType<TData = GetMessagingNotificationsTypeType200>(
    type: 'message' | 'mention' | 'system' | 'chat_invite' | 'user_online' | 'user_offline',
    params?: GetMessagingNotificationsTypeTypeParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getMessagingNotificationsTypeType<TData = GetMessagingNotificationsTypeType200>(
    type: 'message' | 'mention' | 'system' | 'chat_invite' | 'user_online' | 'user_offline',
    params?: GetMessagingNotificationsTypeTypeParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/messaging/notifications/type/${type}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
};

export type GetMessagingChatsParticipantsUserIdClientResult = NonNullable<GetMessagingChatsParticipantsUserId200>
export type PostMessagingChatsChatIdResetUnreadClientResult = NonNullable<PostMessagingChatsChatIdResetUnread200>
export type GetMessagingChatsChatIdClientResult = NonNullable<GetMessagingChatsChatId200>
export type PatchMessagingChatsChatIdClientResult = NonNullable<PatchMessagingChatsChatId200>
export type DeleteMessagingChatsChatIdClientResult = NonNullable<DeleteMessagingChatsChatId200>
export type GetMessagingChatsClientResult = NonNullable<GetMessagingChats200>
export type PostMessagingChatsClientResult = NonNullable<PostMessagingChats201>
export type PostMessagingChatsChatIdReadClientResult = NonNullable<PostMessagingChatsChatIdRead200>
export type GetMessagingChatsChatIdMessagesClientResult = NonNullable<GetMessagingChatsChatIdMessages200>
export type GetMessagingMessagesClientResult = NonNullable<GetMessagingMessages200>
export type PostMessagingMessagesClientResult = NonNullable<PostMessagingMessages201>
export type PatchMessagingMessagesIdReadClientResult = NonNullable<PatchMessagingMessagesIdRead200>
export type PostMessagingMessagesMessageIdDeliveredClientResult = NonNullable<PostMessagingMessagesMessageIdDelivered200>
export type PatchMessagingMessagesMessageIdReadClientResult = NonNullable<PatchMessagingMessagesMessageIdRead200>
export type DeleteMessagingMessagesMessageIdClientResult = NonNullable<DeleteMessagingMessagesMessageId200>
export type GetMessagingIncomingUserIdClientResult = NonNullable<GetMessagingIncomingUserId200>
export type GetMessagingSentUserIdClientResult = NonNullable<GetMessagingSentUserId200>
export type PostMessagingMessagesIdReactionsClientResult = NonNullable<PostMessagingMessagesIdReactions201>
export type DeleteMessagingMessagesIdReactionsClientResult = NonNullable<DeleteMessagingMessagesIdReactions200>
export type PostMessagingAttachmentsUploadClientResult = NonNullable<PostMessagingAttachmentsUpload201>
export type GetMessagingAttachmentsChatChatIdClientResult = NonNullable<GetMessagingAttachmentsChatChatId200>
export type GetMessagingAttachmentsMessageMessageIdClientResult = NonNullable<GetMessagingAttachmentsMessageMessageId200>
export type GetMessagingAttachmentsIdClientResult = NonNullable<GetMessagingAttachmentsId200>
export type DeleteMessagingAttachmentsIdClientResult = NonNullable<DeleteMessagingAttachmentsId200>
export type GetMessagingAttachmentsIdDownloadClientResult = NonNullable<unknown>
export type PostMessagingAttachmentsStatusClientResult = NonNullable<PostMessagingAttachmentsStatus200>
export type GetMessagingNotificationsClientResult = NonNullable<GetMessagingNotifications200>
export type GetMessagingNotificationsUnreadCountClientResult = NonNullable<GetMessagingNotificationsUnreadCount200>
export type PatchMessagingNotificationsIdReadClientResult = NonNullable<PatchMessagingNotificationsIdRead200>
export type PostMessagingNotificationsReadAllClientResult = NonNullable<PostMessagingNotificationsReadAll200>
export type DeleteMessagingNotificationsIdClientResult = NonNullable<DeleteMessagingNotificationsId200>
export type PostMessagingNotificationsClearClientResult = NonNullable<PostMessagingNotificationsClear200>
export type PostMessagingNotificationsSystemClientResult = NonNullable<PostMessagingNotificationsSystem201>
export type GetMessagingNotificationsTypeTypeClientResult = NonNullable<GetMessagingNotificationsTypeType200>
