/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  GetAcademicPeriodsParams,
  PostAcademicPeriodsBody,
  PutAcademicPeriodsIdBody
} from '.././schemas';



type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class AcademicPeriodsService {
  constructor(
    private http: HttpClient,
  ) {}/**
 * Retrieve a list of all academic periods with optional filtering
 * @summary Get all academic periods
 */
 getAcademicPeriods<TData = void>(
    params?: GetAcademicPeriodsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAcademicPeriods<TData = void>(
    params?: GetAcademicPeriodsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAcademicPeriods<TData = void>(
    params?: GetAcademicPeriodsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAcademicPeriods<TData = void>(
    params?: GetAcademicPeriodsParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/academic-periods`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Create a new academic period with the given details
 * @summary Create a new academic period
 */
 postAcademicPeriods<TData = void>(
    postAcademicPeriodsBody: PostAcademicPeriodsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postAcademicPeriods<TData = void>(
    postAcademicPeriodsBody: PostAcademicPeriodsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postAcademicPeriods<TData = void>(
    postAcademicPeriodsBody: PostAcademicPeriodsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postAcademicPeriods<TData = void>(
    postAcademicPeriodsBody: PostAcademicPeriodsBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/academic-periods`,
      postAcademicPeriodsBody,options
    );
  }
/**
 * Retrieve details of a specific academic period by ID
 * @summary Get academic period by ID
 */
 getAcademicPeriodsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAcademicPeriodsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAcademicPeriodsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAcademicPeriodsId<TData = void>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/academic-periods/${id}`,options
    );
  }
/**
 * Update details of a specific academic period
 * @summary Update academic period
 */
 putAcademicPeriodsId<TData = void>(
    id: string,
    putAcademicPeriodsIdBody: PutAcademicPeriodsIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    putAcademicPeriodsId<TData = void>(
    id: string,
    putAcademicPeriodsIdBody: PutAcademicPeriodsIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    putAcademicPeriodsId<TData = void>(
    id: string,
    putAcademicPeriodsIdBody: PutAcademicPeriodsIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;putAcademicPeriodsId<TData = void>(
    id: string,
    putAcademicPeriodsIdBody: PutAcademicPeriodsIdBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.put<TData>(
      `http://localhost:3193/v1/academic-periods/${id}`,
      putAcademicPeriodsIdBody,options
    );
  }
/**
 * Delete a specific academic period
 * @summary Delete academic period
 */
 deleteAcademicPeriodsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    deleteAcademicPeriodsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    deleteAcademicPeriodsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;deleteAcademicPeriodsId<TData = void>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.delete<TData>(
      `http://localhost:3193/v1/academic-periods/${id}`,options
    );
  }
/**
 * Retrieve the current academic period
 * @summary Get current academic period
 */
 getAcademicPeriodsCurrent<TData = void>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAcademicPeriodsCurrent<TData = void>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAcademicPeriodsCurrent<TData = void>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAcademicPeriodsCurrent<TData = void>(
     options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/academic-periods/current`,options
    );
  }
};

export type GetAcademicPeriodsClientResult = NonNullable<void>
export type PostAcademicPeriodsClientResult = NonNullable<void>
export type GetAcademicPeriodsIdClientResult = NonNullable<void>
export type PutAcademicPeriodsIdClientResult = NonNullable<void>
export type DeleteAcademicPeriodsIdClientResult = NonNullable<void>
export type GetAcademicPeriodsCurrentClientResult = NonNullable<void>
