/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { AssetCondition } from './assetCondition';

/**
 * Asset model
 */
export interface Asset {
  id: string;
  name: string;
  category?: string;
  serial_number?: string;
  purchase_date?: string;
  condition?: AssetCondition;
  location?: string;
  assigned_to?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}
