/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { AssignedCustomActivityOneOfOneeightActivityType } from './assignedCustomActivityOneOfOneeightActivityType';
import type { AssignedCustomActivityOneOfOneeightSettings } from './assignedCustomActivityOneOfOneeightSettings';
import type { AssignedCustomActivityOneOfOneeightQuestionsItem } from './assignedCustomActivityOneOfOneeightQuestionsItem';
import type { AssignedCustomActivityOneOfOneeightStudentsItem } from './assignedCustomActivityOneOfOneeightStudentsItem';

/**
 * Custom activity model
 */
export type AssignedCustomActivityOneOfOneeight = {
  activityType: AssignedCustomActivityOneOfOneeightActivityType;
  typeString: string;
  playerMode: string;
  playerModeString: string;
  title: string;
  description: string;
  template: string;
  templateURL: string;
  userId: string;
  cefr: string;
  plays: number;
  totalDuration: number;
  tags: string[];
  settings: AssignedCustomActivityOneOfOneeightSettings;
  questions: AssignedCustomActivityOneOfOneeightQuestionsItem[];
  /** @minItems 1 */
  students: AssignedCustomActivityOneOfOneeightStudentsItem[];
};
