/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type AssignmentForStaffTasksItemResourceType = typeof AssignmentForStaffTasksItemResourceType[keyof typeof AssignmentForStaffTasksItemResourceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssignmentForStaffTasksItemResourceType = {
  ebook: 'ebook',
  'custom-activity': 'custom-activity',
  'open-task': 'open-task',
} as const;
