/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type AssignedCustomActivityOneOfSixActivityType = typeof AssignedCustomActivityOneOfSixActivityType[keyof typeof AssignedCustomActivityOneOfSixActivityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssignedCustomActivityOneOfSixActivityType = {
  fillInTheGaps: 'fillInTheGaps',
} as const;
