/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { AssignmentForStaffSchoolID } from './assignmentForStaffSchoolID';
import type { AssignmentForStaffBranchID } from './assignmentForStaffBranchID';
import type { AssignmentForStaffStaffID } from './assignmentForStaffStaffID';
import type { AssignmentForStaffStaffRole } from './assignmentForStaffStaffRole';
import type { AssignmentForStaffClassID } from './assignmentForStaffClassID';
import type { AssignmentForStaffStudentsIDsItem } from './assignmentForStaffStudentsIDsItem';
import type { AssignmentForStaffStartDate } from './assignmentForStaffStartDate';
import type { AssignmentForStaffEndDate } from './assignmentForStaffEndDate';
import type { AssignmentForStaffTasksItem } from './assignmentForStaffTasksItem';
import type { AssignmentForStaffAcademicTimeframe } from './assignmentForStaffAcademicTimeframe';
import type { AssignmentForStaffDraftDate } from './assignmentForStaffDraftDate';
import type { AssignmentForStaffDeletedForMeDate } from './assignmentForStaffDeletedForMeDate';
import type { AssignmentForStaffDeletedForEveryoneDate } from './assignmentForStaffDeletedForEveryoneDate';
import type { AssignmentForStaffCreatedAt } from './assignmentForStaffCreatedAt';
import type { AssignmentForStaffUpdatedAt } from './assignmentForStaffUpdatedAt';

/**
 * Assignment for staff model
 */
export interface AssignmentForStaff {
  _id: string;
  schoolID: AssignmentForStaffSchoolID;
  branchID: AssignmentForStaffBranchID;
  staffID: AssignmentForStaffStaffID;
  staffRole: AssignmentForStaffStaffRole;
  classID?: AssignmentForStaffClassID;
  studentsIDs?: AssignmentForStaffStudentsIDsItem[];
  title: string;
  startDate: AssignmentForStaffStartDate;
  endDate: AssignmentForStaffEndDate;
  description?: string;
  tasks?: AssignmentForStaffTasksItem[];
  /** Academic timeframe for an assignment */
  academicTimeframe: AssignmentForStaffAcademicTimeframe;
  isDrafted: boolean;
  draftDate?: AssignmentForStaffDraftDate;
  isDeletedForMe: boolean;
  deletedForMeDate?: AssignmentForStaffDeletedForMeDate;
  isDeletedForEveryone: boolean;
  deletedForEveryoneDate?: AssignmentForStaffDeletedForEveryoneDate;
  isPermanentlyDeleted: boolean;
  createdAt: AssignmentForStaffCreatedAt;
  updatedAt: AssignmentForStaffUpdatedAt;
}
