/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { AssignmentForStaffClassIDAnyOf } from './assignmentForStaffClassIDAnyOf';

export type AssignmentForStaffClassID = string | AssignmentForStaffClassIDAnyOf;
