/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { AssignedCustomActivityOneOfOneeightQuestionsItemAnswers } from './assignedCustomActivityOneOfOneeightQuestionsItemAnswers';

export type AssignedCustomActivityOneOfOneeightQuestionsItem = {
  id?: number;
  questionNumber: number;
  answers: AssignedCustomActivityOneOfOneeightQuestionsItemAnswers;
};
