/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { AssignmentForStudentSchoolID } from './assignmentForStudentSchoolID';
import type { AssignmentForStudentBranchID } from './assignmentForStudentBranchID';
import type { AssignmentForStudentStaffID } from './assignmentForStudentStaffID';
import type { AssignmentForStudentStaffRole } from './assignmentForStudentStaffRole';
import type { AssignmentForStudentClassID } from './assignmentForStudentClassID';
import type { AssignmentForStudentStudentID } from './assignmentForStudentStudentID';
import type { AssignmentForStudentStartDate } from './assignmentForStudentStartDate';
import type { AssignmentForStudentEndDate } from './assignmentForStudentEndDate';
import type { AssignmentForStudentTasksItem } from './assignmentForStudentTasksItem';
import type { AssignmentForStudentAssignmentStatus } from './assignmentForStudentAssignmentStatus';
import type { AssignmentForStudentAcademicTimeframe } from './assignmentForStudentAcademicTimeframe';
import type { AssignmentForStudentDeleteDateForMe } from './assignmentForStudentDeleteDateForMe';
import type { AssignmentForStudentDeleteDateForEveryone } from './assignmentForStudentDeleteDateForEveryone';
import type { AssignmentForStudentCreatedAt } from './assignmentForStudentCreatedAt';
import type { AssignmentForStudentUpdatedAt } from './assignmentForStudentUpdatedAt';

/**
 * Assignment for student model
 */
export interface AssignmentForStudent {
  _id: string;
  schoolID: AssignmentForStudentSchoolID;
  branchID: AssignmentForStudentBranchID;
  staffID: AssignmentForStudentStaffID;
  staffRole: AssignmentForStudentStaffRole;
  staffAssignmentID: string;
  classID?: AssignmentForStudentClassID;
  studentID?: AssignmentForStudentStudentID;
  title: string;
  startDate: AssignmentForStudentStartDate;
  endDate: AssignmentForStudentEndDate;
  description?: string;
  tasks?: AssignmentForStudentTasksItem[];
  assignmentStatus: AssignmentForStudentAssignmentStatus;
  /** Academic timeframe for an assignment */
  academicTimeframe: AssignmentForStudentAcademicTimeframe;
  isDeletedForMe: boolean;
  deleteDateForMe?: AssignmentForStudentDeleteDateForMe;
  isDeletedForEveryone: boolean;
  deleteDateForEveryone?: AssignmentForStudentDeleteDateForEveryone;
  isPermanentlyDeleted: boolean;
  createdAt: AssignmentForStudentCreatedAt;
  updatedAt: AssignmentForStudentUpdatedAt;
}
