/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { AssignmentForStudentTasksItemResourceType } from './assignmentForStudentTasksItemResourceType';
import type { AssignmentForStudentTasksItemOpenTaskType } from './assignmentForStudentTasksItemOpenTaskType';
import type { AssignmentForStudentTasksItemAssignedAs } from './assignmentForStudentTasksItemAssignedAs';
import type { AssignmentForStudentTasksItemTaskStatus } from './assignmentForStudentTasksItemTaskStatus';

/**
 * Task details for an assignment
 */
export type AssignmentForStudentTasksItem = {
  resourceType: AssignmentForStudentTasksItemResourceType;
  ebookID?: string;
  ebookActivityID?: string;
  customActivityID?: string;
  openTaskType?: AssignmentForStudentTasksItemOpenTaskType;
  openTaskTitle?: string;
  openTaskInstructions?: string;
  assignedAs: AssignmentForStudentTasksItemAssignedAs;
  instructions?: string;
  /** @minimum 0 */
  attempts: number;
  /** @minimum 0 */
  duration: number;
  /** @minimum 0 */
  score: number;
  taskStatus: AssignmentForStudentTasksItemTaskStatus;
  answers?: unknown;
  answersRevealed: boolean;
};
