/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type AssignmentForStudentAssignmentStatus = typeof AssignmentForStudentAssignmentStatus[keyof typeof AssignmentForStudentAssignmentStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssignmentForStudentAssignmentStatus = {
  new: 'new',
  'in-progress': 'in-progress',
  completed: 'completed',
} as const;
