/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type AssignedCustomActivityOneOfThreetwoActivityType = typeof AssignedCustomActivityOneOfThreetwoActivityType[keyof typeof AssignedCustomActivityOneOfThreetwoActivityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssignedCustomActivityOneOfThreetwoActivityType = {
  memoryMatchingPairs: 'memoryMatchingPairs',
} as const;
