/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { AssignedCustomActivityOneOfThreetwoActivityType } from './assignedCustomActivityOneOfThreetwoActivityType';
import type { AssignedCustomActivityOneOfThreetwoSettings } from './assignedCustomActivityOneOfThreetwoSettings';
import type { AssignedCustomActivityOneOfThreetwoQuestionsItem } from './assignedCustomActivityOneOfThreetwoQuestionsItem';
import type { AssignedCustomActivityOneOfThreetwoStudentsItem } from './assignedCustomActivityOneOfThreetwoStudentsItem';

/**
 * Custom activity model
 */
export type AssignedCustomActivityOneOfThreetwo = {
  activityType: AssignedCustomActivityOneOfThreetwoActivityType;
  typeString: string;
  playerMode: string;
  playerModeString: string;
  title: string;
  description: string;
  template: string;
  templateURL: string;
  userId: string;
  cefr: string;
  plays: number;
  totalDuration: number;
  tags: string[];
  settings: AssignedCustomActivityOneOfThreetwoSettings;
  questions: AssignedCustomActivityOneOfThreetwoQuestionsItem[];
  /** @minItems 1 */
  students: AssignedCustomActivityOneOfThreetwoStudentsItem[];
};
