/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type AssignmentForStudentTasksItemResourceType = typeof AssignmentForStudentTasksItemResourceType[keyof typeof AssignmentForStudentTasksItemResourceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssignmentForStudentTasksItemResourceType = {
  ebook: 'ebook',
  'custom-activity': 'custom-activity',
  'open-task': 'open-task',
} as const;
