/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type AssignmentForStudentTasksItemTaskStatus = typeof AssignmentForStudentTasksItemTaskStatus[keyof typeof AssignmentForStudentTasksItemTaskStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssignmentForStudentTasksItemTaskStatus = {
  new: 'new',
  'in-progress': 'in-progress',
  completed: 'completed',
} as const;
