/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { AssignedCustomActivityOneOfTwofourActivityType } from './assignedCustomActivityOneOfTwofourActivityType';
import type { AssignedCustomActivityOneOfTwofourSettings } from './assignedCustomActivityOneOfTwofourSettings';
import type { AssignedCustomActivityOneOfTwofourQuestionsItem } from './assignedCustomActivityOneOfTwofourQuestionsItem';
import type { AssignedCustomActivityOneOfTwofourStudentsItem } from './assignedCustomActivityOneOfTwofourStudentsItem';

/**
 * Custom activity model
 */
export type AssignedCustomActivityOneOfTwofour = {
  activityType: AssignedCustomActivityOneOfTwofourActivityType;
  typeString: string;
  playerMode: string;
  playerModeString: string;
  title: string;
  description: string;
  template: string;
  templateURL: string;
  userId: string;
  cefr: string;
  plays: number;
  totalDuration: number;
  tags: string[];
  settings: AssignedCustomActivityOneOfTwofourSettings;
  questions: AssignedCustomActivityOneOfTwofourQuestionsItem[];
  /** @minItems 1 */
  students: AssignedCustomActivityOneOfTwofourStudentsItem[];
};
