/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { AssignedCustomActivityOneOfOneoneActivityType } from './assignedCustomActivityOneOfOneoneActivityType';
import type { AssignedCustomActivityOneOfOneoneSettings } from './assignedCustomActivityOneOfOneoneSettings';
import type { AssignedCustomActivityOneOfOneoneQuestionsItem } from './assignedCustomActivityOneOfOneoneQuestionsItem';
import type { AssignedCustomActivityOneOfOneoneStudentsItem } from './assignedCustomActivityOneOfOneoneStudentsItem';

/**
 * Custom activity model
 */
export type AssignedCustomActivityOneOfOneone = {
  activityType: AssignedCustomActivityOneOfOneoneActivityType;
  typeString: string;
  playerMode: string;
  playerModeString: string;
  title: string;
  description: string;
  template: string;
  templateURL: string;
  userId: string;
  cefr: string;
  plays: number;
  totalDuration: number;
  tags: string[];
  settings: AssignedCustomActivityOneOfOneoneSettings;
  questions: AssignedCustomActivityOneOfOneoneQuestionsItem[];
  /** @minItems 1 */
  students: AssignedCustomActivityOneOfOneoneStudentsItem[];
};
