/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { ChatParticipantsDetailsItem } from './chatParticipantsDetailsItem';
import type { ChatType } from './chatType';
import type { ChatUnreadCount } from './chatUnreadCount';
import type { ChatUserSettings } from './chatUserSettings';

/**
 * Chat model
 */
export interface Chat {
  id: string;
  participants: string[];
  participantsDetails?: ChatParticipantsDetailsItem[];
  type: ChatType;
  name?: string;
  lastMessageId?: string;
  lastMessageContent?: string;
  lastMessagedAt?: string;
  lastMessageDate?: string;
  unreadCount?: ChatUnreadCount;
  isStarred?: boolean;
  isPinned?: boolean;
  isMuted?: boolean;
  isArchived?: boolean;
  userSettings?: ChatUserSettings;
  createdAt: string;
  updatedAt: string;
}
