/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type ClassroomType = typeof ClassroomType[keyof typeof ClassroomType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClassroomType = {
  standard: 'standard',
  computer_lab: 'computer_lab',
  science_lab: 'science_lab',
  art_studio: 'art_studio',
  music_room: 'music_room',
  gymnasium: 'gymnasium',
  library: 'library',
  conference_room: 'conference_room',
} as const;
