/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { ClassroomType } from './classroomType';
import type { ClassroomAvailability } from './classroomAvailability';

/**
 * Classroom model
 */
export interface Classroom {
  id: string;
  name: string;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  capacity?: number;
  location?: string;
  equipment?: string[];
  customer: string;
  type?: ClassroomType;
  description?: string;
  availability?: ClassroomAvailability;
  createdAt: string;
  updatedAt: string;
}
