/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { CustomActivityOneOf } from './customActivityOneOf';
import type { CustomActivityOneOfSix } from './customActivityOneOfSix';
import type { CustomActivityOneOfOneone } from './customActivityOneOfOneone';
import type { CustomActivityOneOfOneeight } from './customActivityOneOfOneeight';
import type { CustomActivityOneOfTwofour } from './customActivityOneOfTwofour';
import type { CustomActivityOneOfThreetwo } from './customActivityOneOfThreetwo';
import type { CustomActivityOneOfFourzero } from './customActivityOneOfFourzero';
import type { CustomActivityOneOfFoursix } from './customActivityOneOfFoursix';

/**
 * A union of all possible activity types validated by the activityType discriminator key
 */
export type CustomActivity = CustomActivityOneOf | CustomActivityOneOfSix | CustomActivityOneOfOneone | CustomActivityOneOfOneeight | CustomActivityOneOfTwofour | CustomActivityOneOfThreetwo | CustomActivityOneOfFourzero | CustomActivityOneOfFoursix;
