/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type CustomActivityOneOfFoursixActivityType = typeof CustomActivityOneOfFoursixActivityType[keyof typeof CustomActivityOneOfFoursixActivityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomActivityOneOfFoursixActivityType = {
  wordOrder: 'wordOrder',
} as const;
