/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { CustomActivityOneOfFourzeroActivityType } from './customActivityOneOfFourzeroActivityType';
import type { CustomActivityOneOfFourzeroTagsItem } from './customActivityOneOfFourzeroTagsItem';
import type { CustomActivityOneOfFourzeroSettings } from './customActivityOneOfFourzeroSettings';
import type { CustomActivityOneOfFourzeroQuestionsItem } from './customActivityOneOfFourzeroQuestionsItem';

/**
 * Custom activity model
 */
export type CustomActivityOneOfFourzero = {
  activityType: CustomActivityOneOfFourzeroActivityType;
  typeString: string;
  playerMode: string;
  playerModeString: string;
  title: string;
  description?: string;
  template: string;
  templateURL: string;
  userId: string;
  cefr: string;
  tags?: CustomActivityOneOfFourzeroTagsItem[];
  settings?: CustomActivityOneOfFourzeroSettings;
  questions: CustomActivityOneOfFourzeroQuestionsItem[];
};
