/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { CustomActivityOneOfThreetwoActivityType } from './customActivityOneOfThreetwoActivityType';
import type { CustomActivityOneOfThreetwoTagsItem } from './customActivityOneOfThreetwoTagsItem';
import type { CustomActivityOneOfThreetwoSettings } from './customActivityOneOfThreetwoSettings';
import type { CustomActivityOneOfThreetwoQuestionsItem } from './customActivityOneOfThreetwoQuestionsItem';

/**
 * Custom activity model
 */
export type CustomActivityOneOfThreetwo = {
  activityType: CustomActivityOneOfThreetwoActivityType;
  typeString: string;
  playerMode: string;
  playerModeString: string;
  title: string;
  description?: string;
  template: string;
  templateURL: string;
  userId: string;
  cefr: string;
  tags?: CustomActivityOneOfThreetwoTagsItem[];
  settings?: CustomActivityOneOfThreetwoSettings;
  questions: CustomActivityOneOfThreetwoQuestionsItem[];
};
