/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { CustomActivityOneOfThreenineActivityType } from './customActivityOneOfThreenineActivityType';
import type { CustomActivityOneOfThreenineSettings } from './customActivityOneOfThreenineSettings';
import type { CustomActivityOneOfThreenineQuestionsItem } from './customActivityOneOfThreenineQuestionsItem';

/**
 * Custom activity model
 */
export type CustomActivityOneOfThreenine = {
  activityType: CustomActivityOneOfThreenineActivityType;
  typeString: string;
  playerMode: string;
  playerModeString: string;
  title: string;
  description: string;
  template: string;
  templateURL: string;
  userId: string;
  cefr: string;
  plays: number;
  totalDuration: number;
  tags: string[];
  settings: CustomActivityOneOfThreenineSettings;
  questions: CustomActivityOneOfThreenineQuestionsItem[];
};
