/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { CustomActivityOneOfActivityType } from './customActivityOneOfActivityType';
import type { CustomActivityOneOfSettings } from './customActivityOneOfSettings';
import type { CustomActivityOneOfQuestionsItem } from './customActivityOneOfQuestionsItem';

/**
 * Custom activity model
 */
export type CustomActivityOneOf = {
  activityType: CustomActivityOneOfActivityType;
  typeString: string;
  playerMode: string;
  playerModeString: string;
  title: string;
  description: string;
  template: string;
  templateURL: string;
  userId: string;
  cefr: string;
  plays: number;
  totalDuration: number;
  tags: string[];
  settings: CustomActivityOneOfSettings;
  questions: CustomActivityOneOfQuestionsItem[];
};
