/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type CustomActivityOneOfFourzeroActivityType = typeof CustomActivityOneOfFourzeroActivityType[keyof typeof CustomActivityOneOfFourzeroActivityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomActivityOneOfFourzeroActivityType = {
  multipleChoiceQuiz: 'multipleChoiceQuiz',
} as const;
