/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { CustomActivityOneOfActivityType } from './customActivityOneOfActivityType';
import type { CustomActivityOneOfTagsItem } from './customActivityOneOfTagsItem';
import type { CustomActivityOneOfSettings } from './customActivityOneOfSettings';
import type { CustomActivityOneOfQuestionsItem } from './customActivityOneOfQuestionsItem';

/**
 * Custom activity model
 */
export type CustomActivityOneOf = {
  activityType: CustomActivityOneOfActivityType;
  typeString: string;
  playerMode: string;
  playerModeString: string;
  title: string;
  description?: string;
  template: string;
  templateURL: string;
  userId: string;
  cefr: string;
  tags?: CustomActivityOneOfTagsItem[];
  settings?: CustomActivityOneOfSettings;
  questions: CustomActivityOneOfQuestionsItem[];
};
