/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type CustomActivityOneOfActivityType = typeof CustomActivityOneOfActivityType[keyof typeof CustomActivityOneOfActivityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomActivityOneOfActivityType = {
  cloze: 'cloze',
} as const;
