/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { CustomActivityOneOfFiveActivityType } from './customActivityOneOfFiveActivityType';
import type { CustomActivityOneOfFiveSettings } from './customActivityOneOfFiveSettings';
import type { CustomActivityOneOfFiveQuestionsItem } from './customActivityOneOfFiveQuestionsItem';

/**
 * Custom activity model
 */
export type CustomActivityOneOfFive = {
  activityType: CustomActivityOneOfFiveActivityType;
  typeString: string;
  playerMode: string;
  playerModeString: string;
  title: string;
  description: string;
  template: string;
  templateURL: string;
  userId: string;
  cefr: string;
  plays: number;
  totalDuration: number;
  tags: string[];
  settings: CustomActivityOneOfFiveSettings;
  questions: CustomActivityOneOfFiveQuestionsItem[];
};
