/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { CustomActivityOneOfOneeightActivityType } from './customActivityOneOfOneeightActivityType';
import type { CustomActivityOneOfOneeightTagsItem } from './customActivityOneOfOneeightTagsItem';
import type { CustomActivityOneOfOneeightSettings } from './customActivityOneOfOneeightSettings';
import type { CustomActivityOneOfOneeightQuestionsItem } from './customActivityOneOfOneeightQuestionsItem';

/**
 * Custom activity model
 */
export type CustomActivityOneOfOneeight = {
  activityType: CustomActivityOneOfOneeightActivityType;
  typeString: string;
  playerMode: string;
  playerModeString: string;
  title: string;
  description?: string;
  template: string;
  templateURL: string;
  userId: string;
  cefr: string;
  tags?: CustomActivityOneOfOneeightTagsItem[];
  settings?: CustomActivityOneOfOneeightSettings;
  questions: CustomActivityOneOfOneeightQuestionsItem[];
};
