/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { CustomActivityOneOfThreefourQuestionsItemAnswersItem } from './customActivityOneOfThreefourQuestionsItemAnswersItem';

export type CustomActivityOneOfThreefourQuestionsItem = {
  id?: number;
  questionNumber: number;
  imageURL?: string;
  TTSText?: string;
  questionText: string;
  answers: CustomActivityOneOfThreefourQuestionsItemAnswersItem[];
};
