/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { CustomActivityOneOfOneoneQuestionsItemItemsItem } from './customActivityOneOfOneoneQuestionsItemItemsItem';

export type CustomActivityOneOfOneoneQuestionsItem = {
  id?: number;
  groupNumber: number;
  groupName: string;
  imageURL?: string;
  items: CustomActivityOneOfOneoneQuestionsItemItemsItem[];
};
