/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { CustomActivityOneOfFoursixActivityType } from './customActivityOneOfFoursixActivityType';
import type { CustomActivityOneOfFoursixTagsItem } from './customActivityOneOfFoursixTagsItem';
import type { CustomActivityOneOfFoursixSettings } from './customActivityOneOfFoursixSettings';
import type { CustomActivityOneOfFoursixQuestionsItem } from './customActivityOneOfFoursixQuestionsItem';

/**
 * Custom activity model
 */
export type CustomActivityOneOfFoursix = {
  activityType: CustomActivityOneOfFoursixActivityType;
  typeString: string;
  playerMode: string;
  playerModeString: string;
  title: string;
  description?: string;
  template: string;
  templateURL: string;
  userId: string;
  cefr: string;
  tags?: CustomActivityOneOfFoursixTagsItem[];
  settings?: CustomActivityOneOfFoursixSettings;
  questions: CustomActivityOneOfFoursixQuestionsItem[];
};
