/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { CustomActivityOneOfThreefourActivityType } from './customActivityOneOfThreefourActivityType';
import type { CustomActivityOneOfThreefourSettings } from './customActivityOneOfThreefourSettings';
import type { CustomActivityOneOfThreefourQuestionsItem } from './customActivityOneOfThreefourQuestionsItem';

/**
 * Custom activity model
 */
export type CustomActivityOneOfThreefour = {
  activityType: CustomActivityOneOfThreefourActivityType;
  typeString: string;
  playerMode: string;
  playerModeString: string;
  title: string;
  description: string;
  template: string;
  templateURL: string;
  userId: string;
  cefr: string;
  plays: number;
  totalDuration: number;
  tags: string[];
  settings: CustomActivityOneOfThreefourSettings;
  questions: CustomActivityOneOfThreefourQuestionsItem[];
};
