/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiV1AbsencesId200DataSessionAnyOf } from './deleteApiV1AbsencesId200DataSessionAnyOf';

export type DeleteApiV1AbsencesId200DataSession = string | DeleteApiV1AbsencesId200DataSessionAnyOf;
