/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteAbsencesId200Data } from './deleteAbsencesId200Data';

export type DeleteAbsencesId200 = {
  success: boolean;
  data: DeleteAbsencesId200Data;
};
