/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiV1AbsencesId200DataTaxiAnyOf } from './deleteApiV1AbsencesId200DataTaxiAnyOf';

export type DeleteApiV1AbsencesId200DataTaxi = string | DeleteApiV1AbsencesId200DataTaxiAnyOf;
