/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteMessagingMessagesMessageId200Data } from './deleteMessagingMessagesMessageId200Data';

export type DeleteMessagingMessagesMessageId200 = {
  success: boolean;
  message: string;
  data: DeleteMessagingMessagesMessageId200Data;
};
