/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteMessagingNotificationsId200Data } from './deleteMessagingNotificationsId200Data';

export type DeleteMessagingNotificationsId200 = {
  success: boolean;
  /** Chat notification */
  data: DeleteMessagingNotificationsId200Data;
};
