/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteAssignmentsStaffDeleteForEveryoneIdStaffRole } from './deleteAssignmentsStaffDeleteForEveryoneIdStaffRole';

export type DeleteAssignmentsStaffDeleteForEveryoneIdParams = {
/**
 * Staff member ID for authorization
 */
staffID: string;
/**
 * Staff role for authorization (admin, manager, or teacher)
 */
staffRole: DeleteAssignmentsStaffDeleteForEveryoneIdStaffRole;
/**
 * Branch ID for authorization
 */
branchID: string;
};
