/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteAbsencesId200DataSessionAnyOfStartDate } from './deleteAbsencesId200DataSessionAnyOfStartDate';
import type { DeleteAbsencesId200DataSessionAnyOfEndDate } from './deleteAbsencesId200DataSessionAnyOfEndDate';

export type DeleteAbsencesId200DataSessionAnyOf = {
  _id: string;
  start_date: DeleteAbsencesId200DataSessionAnyOfStartDate;
  end_date: DeleteAbsencesId200DataSessionAnyOfEndDate;
};
