/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export interface Error {
  /** HTTP status code */
  statusCode: number;
  /** Error message */
  message: string;
  /** Error type */
  error: string;
}
