/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { GetAbsences200DataItemAcademicPeriodAnyOf } from './getAbsences200DataItemAcademicPeriodAnyOf';

export type GetAbsences200DataItemAcademicPeriod = string | GetAbsences200DataItemAcademicPeriodAnyOf;
