/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { GetAbsencesReport200DataAbsencesByDateItem } from './getAbsencesReport200DataAbsencesByDateItem';
import type { GetAbsencesReport200DataAbsencesByTaxiItem } from './getAbsencesReport200DataAbsencesByTaxiItem';
import type { GetAbsencesReport200DataAbsencesByStudentItem } from './getAbsencesReport200DataAbsencesByStudentItem';

/**
 * Response schema for absence reports
 */
export type GetAbsencesReport200Data = {
  total_absences: number;
  unexcused_count: number;
  excused_count: number;
  justified_count: number;
  students_with_absences: number;
  absences_by_date: GetAbsencesReport200DataAbsencesByDateItem[];
  absences_by_taxi: GetAbsencesReport200DataAbsencesByTaxiItem[];
  absences_by_student: GetAbsencesReport200DataAbsencesByStudentItem[];
};
