/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type GetAbsencesReportStatus = typeof GetAbsencesReportStatus[keyof typeof GetAbsencesReportStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAbsencesReportStatus = {
  unexcused: 'unexcused',
  excused: 'excused',
  justified: 'justified',
} as const;
