/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1Absences200DataItemSessionAnyOfStartDate } from './getApiV1Absences200DataItemSessionAnyOfStartDate';
import type { GetApiV1Absences200DataItemSessionAnyOfEndDate } from './getApiV1Absences200DataItemSessionAnyOfEndDate';

export type GetApiV1Absences200DataItemSessionAnyOf = {
  _id: string;
  start_date: GetApiV1Absences200DataItemSessionAnyOfStartDate;
  end_date: GetApiV1Absences200DataItemSessionAnyOfEndDate;
};
