/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1Absences200DataItemStudentAnyOf } from './getApiV1Absences200DataItemStudentAnyOf';

export type GetApiV1Absences200DataItemStudent = string | GetApiV1Absences200DataItemStudentAnyOf;
