/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { GetAbsencesId200DataSession } from './getAbsencesId200DataSession';
import type { GetAbsencesId200DataStudent } from './getAbsencesId200DataStudent';
import type { GetAbsencesId200DataTaxi } from './getAbsencesId200DataTaxi';

export type GetAbsencesId200Data = {
  session: GetAbsencesId200DataSession;
  student: GetAbsencesId200DataStudent;
  date: string;
  reason: string;
  status: string;
  taxi: GetAbsencesId200DataTaxi;
  academic_period: string;
  notified_parent: boolean;
  createdAt: string;
  updatedAt: string;
  id: string;
  note?: string;
  notification_date?: string;
};
