/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { GetAssignmentsStaffStaffRole } from './getAssignmentsStaffStaffRole';

export type GetAssignmentsStaffParams = {
/**
 * Filter by branch ID
 */
branchID: string;
/**
 * Filter by staff role
 */
staffRole: GetAssignmentsStaffStaffRole;
/**
 * Filter by staff member ID (🙋🏻‍♂️ required if "staffRole" is "teacher")
 */
staffID?: string;
/**
 * Filter by class ID
 */
classID?: string;
/**
 * Filter by academic year ID
 */
academicYearID: string;
/**
 * Filter by academic period ID
 */
academicPeriodID?: string;
/**
 * Filter by academic subperiod ID
 */
academicSubperiodID?: string;
/**
 * Filter by draft status (true/false)
 */
isDrafted?: boolean;
/**
 * Filter by deleted for me status (true/false)
 */
isDeletedForMe?: boolean;
/**
 * Filter by deleted for everyone status (true/false)
 */
isDeletedForEveryone?: boolean;
};
