/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1AbsencesReport200DataAbsencesByDateItem } from './getApiV1AbsencesReport200DataAbsencesByDateItem';
import type { GetApiV1AbsencesReport200DataAbsencesByTaxiItem } from './getApiV1AbsencesReport200DataAbsencesByTaxiItem';
import type { GetApiV1AbsencesReport200DataAbsencesByStudentItem } from './getApiV1AbsencesReport200DataAbsencesByStudentItem';

/**
 * Response schema for absence reports
 */
export type GetApiV1AbsencesReport200Data = {
  total_absences: number;
  unexcused_count: number;
  excused_count: number;
  justified_count: number;
  students_with_absences: number;
  absences_by_date: GetApiV1AbsencesReport200DataAbsencesByDateItem[];
  absences_by_taxi: GetApiV1AbsencesReport200DataAbsencesByTaxiItem[];
  absences_by_student: GetApiV1AbsencesReport200DataAbsencesByStudentItem[];
};
