/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type GetAssetsParams = {
/**
 * Filter by category
 */
category?: string;
/**
 * Filter by condition
 */
condition?: string;
/**
 * Filter by location
 */
location?: string;
/**
 * Filter by assigned user ID
 */
assigned_to?: string;
/**
 * Search term for name, serial number, or category
 */
search?: string;
};
