/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { GetAssignmentsStudents200Pagination } from './getAssignmentsStudents200Pagination';
import type { AssignmentForStudent } from './assignmentForStudent';

export type GetAssignmentsStudents200 = {
  success: boolean;
  count: number;
  pagination: GetAssignmentsStudents200Pagination;
  data: AssignmentForStudent[];
};
