/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1Absences200DataItemStatus = typeof GetApiV1Absences200DataItemStatus[keyof typeof GetApiV1Absences200DataItemStatus];


 
export const GetApiV1Absences200DataItemStatus = {
  unexcused: 'unexcused',
  excused: 'excused',
  justified: 'justified',
} as const;
