/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { GetAbsences200Pagination } from './getAbsences200Pagination';
import type { GetAbsences200DataItem } from './getAbsences200DataItem';

export type GetAbsences200 = {
  success: boolean;
  count: number;
  pagination: GetAbsences200Pagination;
  data: GetAbsences200DataItem[];
};
