/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1AbsencesId200DataSessionAnyOfStartDate } from './getApiV1AbsencesId200DataSessionAnyOfStartDate';
import type { GetApiV1AbsencesId200DataSessionAnyOfEndDate } from './getApiV1AbsencesId200DataSessionAnyOfEndDate';

export type GetApiV1AbsencesId200DataSessionAnyOf = {
  _id: string;
  start_date: GetApiV1AbsencesId200DataSessionAnyOfStartDate;
  end_date: GetApiV1AbsencesId200DataSessionAnyOfEndDate;
};
