/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { GetActivityActionType } from './getActivityActionType';
import type { GetActivityEntityType } from './getActivityEntityType';

export type GetActivityParams = {
/**
 * Filter by action type
 */
action_type?: GetActivityActionType;
/**
 * Filter by entity type
 */
entity_type?: GetActivityEntityType;
/**
 * Filter by entity ID
 */
entity_id?: string;
/**
 * Filter by user who performed the action
 */
performed_by?: string;
/**
 * Filter by creation date (from)
 */
from_date?: string;
/**
 * Filter by creation date (to)
 */
to_date?: string;
/**
 * Limit the number of records returned
 */
limit?: number;
};
