/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type GetAssignmentsStudentsStatus = typeof GetAssignmentsStudentsStatus[keyof typeof GetAssignmentsStudentsStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAssignmentsStudentsStatus = {
  active: 'active',
  upcoming: 'upcoming',
  past: 'past',
} as const;
