/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1Absences200Pagination } from './getApiV1Absences200Pagination';
import type { GetApiV1Absences200DataItem } from './getApiV1Absences200DataItem';

export type GetApiV1Absences200 = {
  success: boolean;
  count: number;
  pagination: GetApiV1Absences200Pagination;
  data: GetApiV1Absences200DataItem[];
};
