/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { GetAbsences200DataItemSessionAnyOfStartDate } from './getAbsences200DataItemSessionAnyOfStartDate';
import type { GetAbsences200DataItemSessionAnyOfEndDate } from './getAbsences200DataItemSessionAnyOfEndDate';

export type GetAbsences200DataItemSessionAnyOf = {
  _id: string;
  start_date: GetAbsences200DataItemSessionAnyOfStartDate;
  end_date: GetAbsences200DataItemSessionAnyOfEndDate;
};
