/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1AbsencesId200DataStudentAnyOf } from './getApiV1AbsencesId200DataStudentAnyOf';

export type GetApiV1AbsencesId200DataStudent = string | GetApiV1AbsencesId200DataStudentAnyOf;
