/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { GetAssignmentsStudent200Pagination } from './getAssignmentsStudent200Pagination';
import type { AssignmentForStudent } from './assignmentForStudent';

export type GetAssignmentsStudent200 = {
  success: boolean;
  count: number;
  pagination: GetAssignmentsStudent200Pagination;
  data: AssignmentForStudent[];
};
