/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type GetAssignmentsStudentParams = {
/**
 * Filter by branch ID
 */
branchID: string;
/**
 * Filter by student ID
 */
studentID: string;
/**
 * Filter by academic year ID
 */
academicYearID: string;
/**
 * Filter by academic period ID
 */
academicPeriodID?: string;
/**
 * Filter by academic subperiod ID
 */
academicSubperiodID?: string;
/**
 * Filter by deleted for me status (true/false)
 */
isDeletedForMe?: boolean;
/**
 * Filter by deleted for everyone status (true/false)
 */
isDeletedForEveryone?: boolean;
};
