/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { GetCustomActivitiesPublicActivitiesUserId200DataResultsItem } from './getCustomActivitiesPublicActivitiesUserId200DataResultsItem';

export type GetCustomActivitiesPublicActivitiesUserId200Data = {
  results: GetCustomActivitiesPublicActivitiesUserId200DataResultsItem[];
  page: number;
  limit: number;
  totalPages: number;
  totalResults: number;
};
