/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { GetCustomers200Pagination } from './getCustomers200Pagination';
import type { Customer } from './customer';

export type GetCustomers200 = {
  success: boolean;
  count: number;
  pagination: GetCustomers200Pagination;
  data: Customer[];
};
