/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { GetCustomersTypeType200Pagination } from './getCustomersTypeType200Pagination';
import type { Customer } from './customer';

export type GetCustomersTypeType200 = {
  success: boolean;
  count: number;
  pagination: GetCustomersTypeType200Pagination;
  data: Customer[];
};
