/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { GetCustomActivitiesAssignedActivities200DataResultsItemDataSettings } from './getCustomActivitiesAssignedActivities200DataResultsItemDataSettings';
import type { GetCustomActivitiesAssignedActivities200DataResultsItemDataStudentsItem } from './getCustomActivitiesAssignedActivities200DataResultsItemDataStudentsItem';

/**
 * Custom activity model
 */
export type GetCustomActivitiesAssignedActivities200DataResultsItemData = {
  activityType: string;
  typeString: string;
  playerMode: string;
  playerModeString: string;
  title: string;
  description: string;
  template: string;
  templateURL: string;
  userId: string;
  cefr: string;
  plays: number;
  totalDuration: number;
  tags: string[];
  settings: GetCustomActivitiesAssignedActivities200DataResultsItemDataSettings;
  /** @minItems 1 */
  questions: unknown[];
  /** @minItems 1 */
  students: GetCustomActivitiesAssignedActivities200DataResultsItemDataStudentsItem[];
};
