/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { GetCustomActivitiesStudentActivityUserUserIdActivityActivityId200DataSettings } from './getCustomActivitiesStudentActivityUserUserIdActivityActivityId200DataSettings';
import type { GetCustomActivitiesStudentActivityUserUserIdActivityActivityId200DataStudentsItem } from './getCustomActivitiesStudentActivityUserUserIdActivityActivityId200DataStudentsItem';

/**
 * Custom activity model
 */
export type GetCustomActivitiesStudentActivityUserUserIdActivityActivityId200Data = {
  activityType: string;
  typeString: string;
  playerMode: string;
  playerModeString: string;
  title: string;
  description: string;
  template: string;
  templateURL: string;
  userId: string;
  cefr: string;
  plays: number;
  totalDuration: number;
  tags: string[];
  settings: GetCustomActivitiesStudentActivityUserUserIdActivityActivityId200DataSettings;
  /** @minItems 1 */
  questions: unknown[];
  /** @minItems 1 */
  students: GetCustomActivitiesStudentActivityUserUserIdActivityActivityId200DataStudentsItem[];
};
