/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { GetCustomActivitiesAssignedActivities200Data } from './getCustomActivitiesAssignedActivities200Data';

export type GetCustomActivitiesAssignedActivities200 = {
  success: boolean;
  data: GetCustomActivitiesAssignedActivities200Data;
};
