/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { GetDashboardCustomerId200DataCustomer } from './getDashboardCustomerId200DataCustomer';
import type { Activity } from './activity';

export type GetDashboardCustomerId200Data = {
  customer: GetDashboardCustomerId200DataCustomer;
  date: string;
  currentWeek: number;
  students_count: number;
  staff_count: number;
  taxis_count: number;
  ongoing_sessions: number;
  recent_activities: Activity[];
};
