/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type GetElibraryParams = {
/**
 * Filter by item type
 */
type?: string;
/**
 * Filter by author ID
 */
author?: string;
/**
 * Filter by tag
 */
tag?: string;
/**
 * Search term for title or description
 */
search?: string;
};
