/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { GetInventory200Pagination } from './getInventory200Pagination';
import type { Inventory } from './inventory';

export type GetInventory200 = {
  success: boolean;
  count: number;
  pagination: GetInventory200Pagination;
  data: Inventory[];
};
