/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { GetMessagingAttachmentsChatChatId200AttachmentsItemFileCategory } from './getMessagingAttachmentsChatChatId200AttachmentsItemFileCategory';
import type { GetMessagingAttachmentsChatChatId200AttachmentsItemStatus } from './getMessagingAttachmentsChatChatId200AttachmentsItemStatus';
import type { GetMessagingAttachmentsChatChatId200AttachmentsItemVirusScanStatus } from './getMessagingAttachmentsChatChatId200AttachmentsItemVirusScanStatus';
import type { GetMessagingAttachmentsChatChatId200AttachmentsItemMetadata } from './getMessagingAttachmentsChatChatId200AttachmentsItemMetadata';

/**
 * Message attachment model
 */
export type GetMessagingAttachmentsChatChatId200AttachmentsItem = {
  id: string;
  filename: string;
  originalName: string;
  mimeType: string;
  fileExtension?: string;
  fileSize: number;
  fileSizeFormatted?: string;
  fileCategory?: GetMessagingAttachmentsChatChatId200AttachmentsItemFileCategory;
  url?: string;
  uploadedBy: string;
  uploadedAt: string;
  chatId: string;
  messageId?: string;
  status: GetMessagingAttachmentsChatChatId200AttachmentsItemStatus;
  virusScanStatus: GetMessagingAttachmentsChatChatId200AttachmentsItemVirusScanStatus;
  metadata?: GetMessagingAttachmentsChatChatId200AttachmentsItemMetadata;
  createdAt: string;
  updatedAt: string;
};
