/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { GetMessagingAttachmentsMessageMessageId200AttachmentsItem } from './getMessagingAttachmentsMessageMessageId200AttachmentsItem';

export type GetMessagingAttachmentsMessageMessageId200 = {
  success: boolean;
  count: number;
  attachments: GetMessagingAttachmentsMessageMessageId200AttachmentsItem[];
};
