/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type GetMessagingAttachmentsId200AttachmentStatus = typeof GetMessagingAttachmentsId200AttachmentStatus[keyof typeof GetMessagingAttachmentsId200AttachmentStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetMessagingAttachmentsId200AttachmentStatus = {
  uploading: 'uploading',
  ready: 'ready',
  error: 'error',
} as const;
