/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { MoodVideo } from './moodVideo';

export type GetMoodsGetBestVideos200Data = {
  results: MoodVideo[];
  page: number;
  limit: number;
  totalPages: number;
  totalResults: number;
};
