/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { GetMessagingNotifications200NotificationsItemType } from './getMessagingNotifications200NotificationsItemType';

/**
 * Chat notification
 */
export type GetMessagingNotifications200NotificationsItem = {
  id: string;
  userId: string;
  type: GetMessagingNotifications200NotificationsItemType;
  title: string;
  content: string;
  relatedUserId?: string;
  relatedMessageId?: string;
  relatedChatId?: string;
  isRead: boolean;
  isDeleted: boolean;
  /** @nullable */
  readAt?: string;
  createdAt: string;
  updatedAt: string;
  relatedUser?: unknown;
  relatedChat?: unknown;
  relatedMessage?: unknown;
};
