/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { GetMessagingAttachmentsId200AttachmentFileCategory } from './getMessagingAttachmentsId200AttachmentFileCategory';
import type { GetMessagingAttachmentsId200AttachmentStatus } from './getMessagingAttachmentsId200AttachmentStatus';
import type { GetMessagingAttachmentsId200AttachmentVirusScanStatus } from './getMessagingAttachmentsId200AttachmentVirusScanStatus';
import type { GetMessagingAttachmentsId200AttachmentMetadata } from './getMessagingAttachmentsId200AttachmentMetadata';

/**
 * Message attachment model
 */
export type GetMessagingAttachmentsId200Attachment = {
  id: string;
  filename: string;
  originalName: string;
  mimeType: string;
  fileExtension?: string;
  fileSize: number;
  fileSizeFormatted?: string;
  fileCategory?: GetMessagingAttachmentsId200AttachmentFileCategory;
  url?: string;
  uploadedBy: string;
  uploadedAt: string;
  chatId: string;
  messageId?: string;
  status: GetMessagingAttachmentsId200AttachmentStatus;
  virusScanStatus: GetMessagingAttachmentsId200AttachmentVirusScanStatus;
  metadata?: GetMessagingAttachmentsId200AttachmentMetadata;
  createdAt: string;
  updatedAt: string;
};
