/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type GetMessagingAttachmentsChatChatId200AttachmentsItemStatus = typeof GetMessagingAttachmentsChatChatId200AttachmentsItemStatus[keyof typeof GetMessagingAttachmentsChatChatId200AttachmentsItemStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetMessagingAttachmentsChatChatId200AttachmentsItemStatus = {
  uploading: 'uploading',
  ready: 'ready',
  error: 'error',
} as const;
