/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type GetMessagingAttachmentsMessageMessageId200AttachmentsItemStatus = typeof GetMessagingAttachmentsMessageMessageId200AttachmentsItemStatus[keyof typeof GetMessagingAttachmentsMessageMessageId200AttachmentsItemStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetMessagingAttachmentsMessageMessageId200AttachmentsItemStatus = {
  uploading: 'uploading',
  ready: 'ready',
  error: 'error',
} as const;
