/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type GetMessagingAttachmentsMessageMessageId200AttachmentsItemVirusScanStatus = typeof GetMessagingAttachmentsMessageMessageId200AttachmentsItemVirusScanStatus[keyof typeof GetMessagingAttachmentsMessageMessageId200AttachmentsItemVirusScanStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetMessagingAttachmentsMessageMessageId200AttachmentsItemVirusScanStatus = {
  pending: 'pending',
  clean: 'clean',
  infected: 'infected',
} as const;
