/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { GetMessagingAttachmentsId200Attachment } from './getMessagingAttachmentsId200Attachment';

export type GetMessagingAttachmentsId200 = {
  success: boolean;
  /** Message attachment model */
  attachment: GetMessagingAttachmentsId200Attachment;
};
