/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { GetMessagingAttachmentsChatChatId200AttachmentsItemMetadataExif } from './getMessagingAttachmentsChatChatId200AttachmentsItemMetadataExif';

export type GetMessagingAttachmentsChatChatId200AttachmentsItemMetadata = {
  width?: number;
  height?: number;
  exif?: GetMessagingAttachmentsChatChatId200AttachmentsItemMetadataExif;
};
