/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type GetMessagingAttachmentsId200AttachmentVirusScanStatus = typeof GetMessagingAttachmentsId200AttachmentVirusScanStatus[keyof typeof GetMessagingAttachmentsId200AttachmentVirusScanStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetMessagingAttachmentsId200AttachmentVirusScanStatus = {
  pending: 'pending',
  clean: 'clean',
  infected: 'infected',
} as const;
