/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { GetMessagingIncomingUserId200Data } from './getMessagingIncomingUserId200Data';

export type GetMessagingIncomingUserId200 = {
  success: boolean;
  data: GetMessagingIncomingUserId200Data;
};
