/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { GetMessagingNotifications200NotificationsItem } from './getMessagingNotifications200NotificationsItem';

export type GetMessagingNotifications200 = {
  success: boolean;
  notifications: GetMessagingNotifications200NotificationsItem[];
  totalCount: number;
  unreadCount: number;
  currentPage: number;
  totalPages: number;
  hasMore: boolean;
};
