/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type GetMessagingAttachmentsChatChatId200AttachmentsItemFileCategory = typeof GetMessagingAttachmentsChatChatId200AttachmentsItemFileCategory[keyof typeof GetMessagingAttachmentsChatChatId200AttachmentsItemFileCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetMessagingAttachmentsChatChatId200AttachmentsItemFileCategory = {
  image: 'image',
  document: 'document',
  audio: 'audio',
  video: 'video',
  other: 'other',
} as const;
