/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { GetMessagingAttachmentsId200AttachmentMetadataExif } from './getMessagingAttachmentsId200AttachmentMetadataExif';

export type GetMessagingAttachmentsId200AttachmentMetadata = {
  width?: number;
  height?: number;
  exif?: GetMessagingAttachmentsId200AttachmentMetadataExif;
};
