/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { GetMoodsGetBestVideos200Data } from './getMoodsGetBestVideos200Data';

export type GetMoodsGetBestVideos200 = {
  success: boolean;
  data: GetMoodsGetBestVideos200Data;
};
