/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { Message } from './message';
import type { GetMessagingIncomingUserId200DataPagination } from './getMessagingIncomingUserId200DataPagination';

export type GetMessagingIncomingUserId200Data = {
  messages: Message[];
  pagination: GetMessagingIncomingUserId200DataPagination;
};
