/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { GetNotesAppId200ItemOwner } from './getNotesAppId200ItemOwner';
import type { GetNotesAppId200ItemData } from './getNotesAppId200ItemData';

/**
 * Ebook Note Response Schema
 */
export type GetNotesAppId200Item = {
  _id: string;
  appId: string;
  owner: GetNotesAppId200ItemOwner;
  data: GetNotesAppId200ItemData;
  createdAt: string;
  updatedAt: string;
};
