/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { GetSessionsPreviewDay } from './getSessionsPreviewDay';

export type GetSessionsPreviewParams = {
/**
 * Day of the week
 */
day: GetSessionsPreviewDay;
/**
 * Start date for the recurring sessions
 */
start_date: string;
/**
 * End date for the recurring sessions
 */
end_date: string;
/**
 * Frequency in weeks
 */
frequency: number;
/**
 * Start time in HH:MM format
 */
start_time: string;
/**
 * Duration in hours
 */
duration: number;
};
