/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { GetSessionsPreview200Data } from './getSessionsPreview200Data';

/**
 * Success response model
 */
export type GetSessionsPreview200 = {
  success: boolean;
  message: string;
  data: GetSessionsPreview200Data;
};
