/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { GetTaxis200Pagination } from './getTaxis200Pagination';
import type { Taxi } from './taxi';

export type GetTaxis200 = {
  success: boolean;
  count: number;
  pagination: GetTaxis200Pagination;
  data: Taxi[];
};
