/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type GetTaxis200Pagination = {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
};
