/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { GetTaxisIdAttendance200DataRowsItemAllOf } from './getTaxisIdAttendance200DataRowsItemAllOf';
import type { GetTaxisIdAttendance200DataRowsItemAllOfTwo } from './getTaxisIdAttendance200DataRowsItemAllOfTwo';

/**
 * Attendance row per student; dynamic date keys map to boolean (true=present, false=absent).
 */
export type GetTaxisIdAttendance200DataRowsItem = GetTaxisIdAttendance200DataRowsItemAllOf & GetTaxisIdAttendance200DataRowsItemAllOfTwo;
