/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type GetUsersStudentsParams = {
/**
 * Filter by active status
 */
is_active?: string;
/**
 * Filter by archived status
 */
archived?: string;
/**
 * Filter by branch ID. If not provided, returns all students
 */
branch?: string;
/**
 * Filter by role title (e.g., STUDENT). If not provided, returns all students
 */
role?: string;
/**
 * Page number for pagination
 */
page?: string;
/**
 * Number of items per page
 */
limit?: string;
};
