/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { GetUsers200Data } from './getUsers200Data';

/**
 * Paginated response model
 */
export type GetUsers200 = {
  data: GetUsers200Data;
  success: boolean;
  status: number;
};
