/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { GetUsersChildren200Data } from './getUsersChildren200Data';

/**
 * Paginated response model
 */
export type GetUsersChildren200 = {
  data: GetUsersChildren200Data;
  success: boolean;
  status: number;
};
