/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { GetUsersStaff200Data } from './getUsersStaff200Data';

/**
 * Paginated response model
 */
export type GetUsersStaff200 = {
  data: GetUsersStaff200Data;
  success: boolean;
  status: number;
};
