/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type GetUsersChildrenParams = {
/**
 * Page number for pagination
 */
page?: string;
/**
 * Number of items per page
 */
limit?: string;
/**
 * Sort field and direction (e.g., "createdAt:desc")
 */
sort?: string;
};
