/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

/**
 * Customer details in inventory response
 */
export type InventoryCustomer = {
  id: string;
  name: string;
  slug?: string;
  nickname?: string;
  afm?: string;
  email?: string;
  description?: string;
  address?: string;
  phone?: string;
  code?: string;
  vat?: string;
  customer_type: string;
  is_primary?: boolean;
  is_main_customer?: boolean;
  avatar?: string;
  website?: string;
};
