/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type MaterialComponentsItemAvatar = {
  id: string;
  file_name?: string;
  file_type?: string;
  file_path?: string;
};
