/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { MaterialComponentsItemAvatar } from './materialComponentsItemAvatar';
import type { MaterialComponentsItemAssetsItem } from './materialComponentsItemAssetsItem';

export type MaterialComponentsItem = {
  id: string;
  name: string;
  component_type?: string;
  category?: string;
  description?: string;
  json_data?: unknown;
  avatar?: MaterialComponentsItemAvatar;
  assets?: MaterialComponentsItemAssetsItem[];
};
