/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { MessageType } from './messageType';
import type { MessageDeliveredToItem } from './messageDeliveredToItem';
import type { MessageReadByItem } from './messageReadByItem';
import type { MessageReplyToMessage } from './messageReplyToMessage';

/**
 * Message model
 */
export interface Message {
  id: string;
  senderId: string;
  recipientIds: string[];
  chatId: string;
  content?: string;
  type: MessageType;
  timestamp: string;
  replyToMessageId?: string;
  deliveredTo?: MessageDeliveredToItem[];
  readBy?: MessageReadByItem[];
  read: boolean;
  /** @nullable */
  readAt?: string;
  senderUsername?: string;
  senderFullName?: string;
  /** @nullable */
  replyToMessage?: MessageReplyToMessage;
  createdAt: string;
  updatedAt: string;
}
