/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PatchCustomActivitiesAssignedActivitiesUpdateStatusActivityActivityIdStudentStudentId201DataSettings } from './patchCustomActivitiesAssignedActivitiesUpdateStatusActivityActivityIdStudentStudentId201DataSettings';
import type { PatchCustomActivitiesAssignedActivitiesUpdateStatusActivityActivityIdStudentStudentId201DataStudentsItem } from './patchCustomActivitiesAssignedActivitiesUpdateStatusActivityActivityIdStudentStudentId201DataStudentsItem';

/**
 * Custom activity model
 */
export type PatchCustomActivitiesAssignedActivitiesUpdateStatusActivityActivityIdStudentStudentId201Data = {
  activityType: string;
  typeString: string;
  playerMode: string;
  playerModeString: string;
  title: string;
  description: string;
  template: string;
  templateURL: string;
  userId: string;
  cefr: string;
  tags: string[];
  settings: PatchCustomActivitiesAssignedActivitiesUpdateStatusActivityActivityIdStudentStudentId201DataSettings;
  /** @minItems 1 */
  questions: unknown[];
  /** @minItems 1 */
  students: PatchCustomActivitiesAssignedActivitiesUpdateStatusActivityActivityIdStudentStudentId201DataStudentsItem[];
};
