/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PatchCustomActivitiesTaskAnswersAssignmentAssignmentIdStudentStudentIdActivityCustomActivityId200Data } from './patchCustomActivitiesTaskAnswersAssignmentAssignmentIdStudentStudentIdActivityCustomActivityId200Data';

export type PatchCustomActivitiesTaskAnswersAssignmentAssignmentIdStudentStudentIdActivityCustomActivityId200 = {
  success: boolean;
  data: PatchCustomActivitiesTaskAnswersAssignmentAssignmentIdStudentStudentIdActivityCustomActivityId200Data;
};
