/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PatchCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId200Data } from './patchCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId200Data';

export type PatchCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId200 = {
  success: boolean;
  data: PatchCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId200Data;
};
