/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PatchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityId200Data } from './patchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityId200Data';

export type PatchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityId200 = {
  success: boolean;
  /** Custom activity model */
  data: PatchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityId200Data;
};
