/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

/**
 * Update chat settings
 */
export type PatchMessagingChatsChatIdBody = {
  name?: string;
  isStarred?: boolean;
  isPinned?: boolean;
  isMuted?: boolean;
  isArchived?: boolean;
};
