/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { Customer } from './customer';
import type { User } from './user';

export type PostInternalSchools201Data = {
  mainCustomer: Customer;
  branchCustomer: Customer;
  user: User;
};
