/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for creating a new mood
 */
export type PostMoodsBody = {
  userId: string;
  taxisId: string;
  academic_subperiod: string;
  mood: string;
  date: string;
};
