/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type PostActivityBodyEntityType = typeof PostActivityBodyEntityType[keyof typeof PostActivityBodyEntityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostActivityBodyEntityType = {
  user: 'user',
  student: 'student',
  taxi: 'taxi',
  post: 'post',
  session: 'session',
  classroom: 'classroom',
  absence: 'absence',
} as const;
