/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for adding a tag to a post
 */
export type PostPostsAddTagBody = {
  /** @minLength 1 */
  post_id: string;
  /** @minLength 1 */
  tag: string;
};
