/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PostAssignmentsStaffBodyStaffRole } from './postAssignmentsStaffBodyStaffRole';
import type { PostAssignmentsStaffBodyStartDate } from './postAssignmentsStaffBodyStartDate';
import type { PostAssignmentsStaffBodyEndDate } from './postAssignmentsStaffBodyEndDate';
import type { PostAssignmentsStaffBodyTasksItem } from './postAssignmentsStaffBodyTasksItem';
import type { PostAssignmentsStaffBodyAcademicTimeframe } from './postAssignmentsStaffBodyAcademicTimeframe';

/**
 * Schema for creating a new assignment for staff
 */
export type PostAssignmentsStaffBody = {
  /** @minLength 1 */
  schoolID: string;
  /** @minLength 1 */
  branchID: string;
  /** @minLength 1 */
  staffID: string;
  staffRole: PostAssignmentsStaffBodyStaffRole;
  classID?: string;
  studentsIDs?: string[];
  /**
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  startDate: PostAssignmentsStaffBodyStartDate;
  endDate: PostAssignmentsStaffBodyEndDate;
  description?: string;
  tasks?: PostAssignmentsStaffBodyTasksItem[];
  academicTimeframe: PostAssignmentsStaffBodyAcademicTimeframe;
  isDrafted?: boolean;
};
