/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1Absences201Data } from './postApiV1Absences201Data';

export type PostApiV1Absences201 = {
  success: boolean;
  /** Absence model */
  data: PostApiV1Absences201Data;
};
