/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';

/**
 * Authentication response model
 */
export type PostAuthImpersonateStudentId200Data = {
  token: string;
  refreshToken: string;
  user: User;
  authHeader?: string;
};
