/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

/**
 * Create system notification for multiple users
 */
export type PostMessagingNotificationsSystemBody = {
  /** @minItems 1 */
  userIds: string[];
  /** @maxLength 100 */
  title: string;
  /** @maxLength 500 */
  content: string;
};
