/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PostMessagingChatsChatIdResetUnread200Data } from './postMessagingChatsChatIdResetUnread200Data';

export type PostMessagingChatsChatIdResetUnread200 = {
  success: boolean;
  message: string;
  data: PostMessagingChatsChatIdResetUnread200Data;
};
