/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PostAbsences201DataAcademicPeriodAnyOf } from './postAbsences201DataAcademicPeriodAnyOf';

export type PostAbsences201DataAcademicPeriod = string | PostAbsences201DataAcademicPeriodAnyOf;
