/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PostClassroomsBodyType } from './postClassroomsBodyType';
import type { PostClassroomsBodyAvailability } from './postClassroomsBodyAvailability';

/**
 * Schema for creating a new classroom
 */
export type PostClassroomsBody = {
  /** @minLength 1 */
  name: string;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  capacity?: number;
  location?: string;
  equipment?: string[];
  /** @minLength 1 */
  customer: string;
  type?: PostClassroomsBodyType;
  description?: string;
  availability?: PostClassroomsBodyAvailability;
};
