/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type PostAssignmentsStudentBodyTasksItemOpenTaskType = typeof PostAssignmentsStudentBodyTasksItemOpenTaskType[keyof typeof PostAssignmentsStudentBodyTasksItemOpenTaskType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostAssignmentsStudentBodyTasksItemOpenTaskType = {
  speaking: 'speaking',
  writing: 'writing',
} as const;
