/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type PostApiV1Absences201DataStatus = typeof PostApiV1Absences201DataStatus[keyof typeof PostApiV1Absences201DataStatus];


 
export const PostApiV1Absences201DataStatus = {
  unexcused: 'unexcused',
  excused: 'excused',
  justified: 'justified',
} as const;
