/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PostClassroomsBodyAvailabilityItemDay } from './postClassroomsBodyAvailabilityItemDay';

export type PostClassroomsBodyAvailabilityItem = {
  day: PostClassroomsBodyAvailabilityItemDay;
  /** @pattern ^([0-1][0-9]|2[0-3]):[0-5][0-9]$ */
  start_time: string;
  /** @pattern ^([0-1][0-9]|2[0-3]):[0-5][0-9]$ */
  end_time: string;
};
