/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PostAbsences201DataSessionAnyOfStartDate } from './postAbsences201DataSessionAnyOfStartDate';
import type { PostAbsences201DataSessionAnyOfEndDate } from './postAbsences201DataSessionAnyOfEndDate';

export type PostAbsences201DataSessionAnyOf = {
  _id: string;
  start_date: PostAbsences201DataSessionAnyOfStartDate;
  end_date: PostAbsences201DataSessionAnyOfEndDate;
};
