/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for adding a student to a session
 */
export type PostSessionsAddStudentBody = {
  /** @minLength 1 */
  session_id: string;
  /** @minLength 1 */
  student_id: string;
};
