/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PostInternalSchoolsBodyMainCustomer } from './postInternalSchoolsBodyMainCustomer';
import type { PostInternalSchoolsBodyBranchCustomer } from './postInternalSchoolsBodyBranchCustomer';
import type { PostInternalSchoolsBodyUser } from './postInternalSchoolsBodyUser';

/**
 * Schema for internally creating a school (main customer, branch, user)
 */
export type PostInternalSchoolsBody = {
  main_customer: PostInternalSchoolsBodyMainCustomer;
  branch_customer: PostInternalSchoolsBodyBranchCustomer;
  user: PostInternalSchoolsBodyUser;
};
