/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { Session } from './session';

/**
 * Success response model
 */
export type PostSessions201 = {
  success: boolean;
  message: string;
  data: Session;
};
