/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PostAbsences201DataSession } from './postAbsences201DataSession';
import type { PostAbsences201DataStudent } from './postAbsences201DataStudent';
import type { PostAbsences201DataTaxi } from './postAbsences201DataTaxi';

export type PostAbsences201Data = {
  session: PostAbsences201DataSession;
  student: PostAbsences201DataStudent;
  date: string;
  reason: string;
  status: string;
  taxi: PostAbsences201DataTaxi;
  academic_period: string;
  notified_parent: boolean;
  createdAt: string;
  updatedAt: string;
  id: string;
  note?: string;
  notification_date?: string;
};
