/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PostSessionsOnlineSessionToken200Data } from './postSessionsOnlineSessionToken200Data';

/**
 * Success response model
 */
export type PostSessionsOnlineSessionToken200 = {
  success: boolean;
  message: string;
  data: PostSessionsOnlineSessionToken200Data;
};
