/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type PostElibraryBodyType = typeof PostElibraryBodyType[keyof typeof PostElibraryBodyType];


 
export const PostElibraryBodyType = {
  document: 'document',
  video: 'video',
  audio: 'audio',
  link: 'link',
} as const;
