/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PostNotesAppId200Owner } from './postNotesAppId200Owner';
import type { PostNotesAppId200Data } from './postNotesAppId200Data';

/**
 * Ebook Note Response Schema
 */
export type PostNotesAppId200 = {
  _id: string;
  appId: string;
  owner: PostNotesAppId200Owner;
  data: PostNotesAppId200Data;
  createdAt: string;
  updatedAt: string;
};
