/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type PostCustomActivitiesFindOnPexels200 = {
  success: boolean;
  /** @nullable */
  imagesData: string;
  /** @nullable */
  messageType: string;
  /** @nullable */
  message: string;
};
