/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1Absences201DataSession } from './postApiV1Absences201DataSession';
import type { PostApiV1Absences201DataStudent } from './postApiV1Absences201DataStudent';
import type { PostApiV1Absences201DataDate } from './postApiV1Absences201DataDate';
import type { PostApiV1Absences201DataStatus } from './postApiV1Absences201DataStatus';
import type { PostApiV1Absences201DataTaxi } from './postApiV1Absences201DataTaxi';
import type { PostApiV1Absences201DataAcademicPeriod } from './postApiV1Absences201DataAcademicPeriod';
import type { PostApiV1Absences201DataNotificationDate } from './postApiV1Absences201DataNotificationDate';
import type { PostApiV1Absences201DataCreatedAt } from './postApiV1Absences201DataCreatedAt';
import type { PostApiV1Absences201DataUpdatedAt } from './postApiV1Absences201DataUpdatedAt';

/**
 * Absence model
 */
export type PostApiV1Absences201Data = {
  _id: string;
  session: PostApiV1Absences201DataSession;
  student: PostApiV1Absences201DataStudent;
  date: PostApiV1Absences201DataDate;
  reason?: string;
  status: PostApiV1Absences201DataStatus;
  justification_document?: string;
  taxi: PostApiV1Absences201DataTaxi;
  academic_period: PostApiV1Absences201DataAcademicPeriod;
  note?: string;
  notified_parent: boolean;
  notification_date?: PostApiV1Absences201DataNotificationDate;
  createdAt: PostApiV1Absences201DataCreatedAt;
  updatedAt: PostApiV1Absences201DataUpdatedAt;
};
