/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

/**
 * Success response model
 */
export type PostAuthLogout200 = {
  success: boolean;
  message: string;
  data?: unknown;
};
