/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PostCustomActivitiesAssignedActivitiesCreateActivityActivityId201DataSettings } from './postCustomActivitiesAssignedActivitiesCreateActivityActivityId201DataSettings';
import type { PostCustomActivitiesAssignedActivitiesCreateActivityActivityId201DataStudentsItem } from './postCustomActivitiesAssignedActivitiesCreateActivityActivityId201DataStudentsItem';

/**
 * Custom activity model
 */
export type PostCustomActivitiesAssignedActivitiesCreateActivityActivityId201Data = {
  activityType: string;
  typeString: string;
  playerMode: string;
  playerModeString: string;
  title: string;
  description: string;
  template: string;
  templateURL: string;
  userId: string;
  cefr: string;
  plays: number;
  totalDuration: number;
  tags: string[];
  settings: PostCustomActivitiesAssignedActivitiesCreateActivityActivityId201DataSettings;
  /** @minItems 1 */
  questions: unknown[];
  /** @minItems 1 */
  students: PostCustomActivitiesAssignedActivitiesCreateActivityActivityId201DataStudentsItem[];
};
