/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthRegisterBodyCustomer } from './postAuthRegisterBodyCustomer';

export type PostAuthRegisterBody = {
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  firstname: string;
  /** @minLength 1 */
  lastname: string;
  email: string;
  /**
   * @minLength 10
   * @maxLength 10
   */
  phone: string;
  password: string;
  confirmPassword: string;
  mobile: string;
  customer: PostAuthRegisterBodyCustomer;
};
