/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

/**
 * Add reaction to a message
 */
export type PostMessagingMessagesIdReactionsBody = {
  /** @minLength 1 */
  emoji: string;
};
