/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type PostCustomActivitiesAssignedActivitiesCreateActivityActivityIdBody = {
  /** Array of student IDs (ObjectId) to assign during creation */
  students: string[];
  /** Class id to assign during creation */
  classId: string;
  /** assignmentBundle to assign during creation */
  assignmentBundle: string;
};
