/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PostNotesAppIdBodyLocation } from './postNotesAppIdBodyLocation';

export type PostNotesAppIdBody = {
  recipients: string[];
  location: PostNotesAppIdBodyLocation;
  y?: number;
  x?: number;
  text?: string;
  /** @nullable */
  image?: string;
  /** @nullable */
  audio?: string;
};
