/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PostStatus } from './postStatus';

/**
 * Post model
 */
export interface Post {
  id: string;
  title: string;
  content: string;
  author: string;
  tags?: string[];
  status: PostStatus;
  featured_image?: string;
  published_at?: string;
  createdAt: string;
  updatedAt: string;
}
