/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for requesting a token using for online session
 */
export type PostSessionsOnlineSessionTokenBody = {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  roomName: string;
  /** @minLength 1 */
  currentRoleTitle: string;
};
