/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthLogin200Data } from './postAuthLogin200Data';

/**
 * Success response model
 */
export type PostAuthLogin200 = {
  success: boolean;
  message: string;
  /** Authentication response model */
  data: PostAuthLogin200Data;
};
