/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PostAssignmentsStaffBodyTasksItemResourceType } from './postAssignmentsStaffBodyTasksItemResourceType';
import type { PostAssignmentsStaffBodyTasksItemOpenTaskType } from './postAssignmentsStaffBodyTasksItemOpenTaskType';
import type { PostAssignmentsStaffBodyTasksItemAssignedAs } from './postAssignmentsStaffBodyTasksItemAssignedAs';

/**
 * Task details for an assignment
 */
export type PostAssignmentsStaffBodyTasksItem = {
  resourceType: PostAssignmentsStaffBodyTasksItemResourceType;
  ebookID?: string;
  ebookActivityID?: string;
  customActivityID?: string;
  openTaskType?: PostAssignmentsStaffBodyTasksItemOpenTaskType;
  openTaskTitle?: string;
  openTaskInstructions?: string;
  assignedAs: PostAssignmentsStaffBodyTasksItemAssignedAs;
  instructions?: string;
};
