/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type PostUsersStaffBodyUserType = typeof PostUsersStaffBodyUserType[keyof typeof PostUsersStaffBodyUserType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostUsersStaffBodyUserType = {
  admin: 'admin',
  manager: 'manager',
  teacher: 'teacher',
  student: 'student',
  parent: 'parent',
} as const;
