/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for adding a user to a customer
 */
export type PostCustomersIdUsersBody = {
  /** @minLength 1 */
  userId: string;
};
