/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type PostCustomActivitiesUploadFromURL201Data = {
  /** Public path to the uploaded image */
  path: string;
  /** Generated unique filename */
  filename: string;
  /** Original filename or URL basename */
  originalname: string;
  /** MIME type of the image */
  mimetype: string;
};
