/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PostMessagingMessagesMessageIdDelivered200Data } from './postMessagingMessagesMessageIdDelivered200Data';

export type PostMessagingMessagesMessageIdDelivered200 = {
  success: boolean;
  message: string;
  data: PostMessagingMessagesMessageIdDelivered200Data;
};
