/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PostUsersBodyUserType } from './postUsersBodyUserType';
import type { PostUsersBodyContactsItem } from './postUsersBodyContactsItem';
import type { PostUsersBodySiblingAttending } from './postUsersBodySiblingAttending';

/**
 * Schema for creating a new user
 */
export type PostUsersBody = {
  id: string;
  username: string;
  code: string;
  firstname: string;
  lastname: string;
  email: string;
  /** @minLength 1 */
  phone: string;
  mobile?: string;
  city?: string;
  region?: string;
  country?: string;
  address?: string;
  zipcode?: string;
  birthday?: string;
  is_active: boolean;
  customers?: string[];
  roles?: string[];
  taxis?: string[];
  user_type?: PostUsersBodyUserType;
  avatar?: string;
  branches?: string[];
  default_branch?: string;
  role_title?: string;
  status?: boolean;
  hire_date?: string;
  registration_date?: string;
  facebook_link?: string;
  twitter_link?: string;
  linkedin_link?: string;
  documents?: string[];
  notes?: string;
  contacts?: PostUsersBodyContactsItem[];
  siblingAttending?: PostUsersBodySiblingAttending;
  hasAllergies?: boolean;
  healthDetails?: string;
  generalNotes?: string;
  createdAt: string;
  updatedAt: string;
  on_live_session?: boolean;
  class?: string;
};
