/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PostAssetsBodyCondition } from './postAssetsBodyCondition';

/**
 * Schema for creating a new asset
 */
export type PostAssetsBody = {
  /**
   * @minLength 1
   * @maxLength 200
   */
  name: string;
  category?: string;
  serial_number?: string;
  purchase_date?: string;
  condition?: PostAssetsBodyCondition;
  location?: string;
  assigned_to?: string;
  notes?: string;
};
