/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PostMessagingMessagesBodyType } from './postMessagingMessagesBodyType';

/**
 * Send a message
 */
export type PostMessagingMessagesBody = {
  /** @minLength 1 */
  senderId: string;
  chatId?: string;
  recipientIds?: string[];
  content?: string;
  type?: PostMessagingMessagesBodyType;
  replyToMessageId?: string;
};
