/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PostUsersStudentsBodyUserType } from './postUsersStudentsBodyUserType';
import type { PostUsersStudentsBodyContactsItem } from './postUsersStudentsBodyContactsItem';
import type { PostUsersStudentsBodySiblingAttending } from './postUsersStudentsBodySiblingAttending';

/**
 * Schema for creating a new user
 */
export type PostUsersStudentsBody = {
  id: string;
  username: string;
  code: string;
  firstname: string;
  lastname: string;
  email: string;
  phone: string;
  /** @minLength 1 */
  mobile: string;
  city?: string;
  region?: string;
  country?: string;
  address?: string;
  zipcode?: string;
  birthday?: string;
  is_active: boolean;
  customers?: string[];
  roles?: string[];
  taxis?: string[];
  user_type?: PostUsersStudentsBodyUserType;
  avatar?: string;
  branches?: string[];
  default_branch?: string;
  role_title?: string;
  status?: boolean;
  hire_date?: string;
  facebook_link?: string;
  twitter_link?: string;
  linkedin_link?: string;
  documents?: string[];
  notes?: string;
  contacts?: PostUsersStudentsBodyContactsItem[];
  siblingAttending?: PostUsersStudentsBodySiblingAttending;
  hasAllergies?: boolean;
  healthDetails?: string;
  generalNotes?: string;
  createdAt: string;
  updatedAt: string;
  on_live_session?: boolean;
  class?: string;
};
