/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for removing a user from a taxi
 */
export type PostTaxisRemoveUserBody = {
  /** @minLength 1 */
  taxi_id: string;
  /** @minLength 1 */
  user_id: string;
};
