/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PostStatus } from './postStatus';
import type { PostPriority } from './postPriority';
import type { PostRecipients } from './postRecipients';
import type { PostPoll } from './postPoll';

/**
 * Post model
 */
export interface Post {
  id: string;
  title: string;
  content: string;
  author: string;
  tags?: string[];
  status: PostStatus;
  priority?: PostPriority;
  pinned?: boolean;
  likedBy?: string[];
  recipients?: PostRecipients;
  scheduled_at?: string;
  expires_at?: string;
  allow_reactions?: boolean;
  allow_replies?: boolean;
  poll?: PostPoll;
  featured_image?: string;
  published_at?: string;
  createdAt: string;
  updatedAt: string;
}
