/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PostErrorBodyLocation } from './postErrorBodyLocation';

/**
 * Schema for creating a new error item
 */
export type PostErrorBody = {
  title: string;
  message: string;
  location: PostErrorBodyLocation;
  status_code: number;
};
