/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type PostMessagingNotificationsReadAll200 = {
  success: boolean;
  modifiedCount: number;
  message: string;
};
