/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type PostInternalSchoolsBodyUser = {
  /** @minLength 3 */
  username: string;
  /** @minLength 1 */
  firstname: string;
  /** @minLength 1 */
  lastname: string;
  email: string;
  /** @minLength 10 */
  phone: string;
  /** @minLength 6 */
  password: string;
};
