/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type PostMessagingMessagesBodyType = typeof PostMessagingMessagesBodyType[keyof typeof PostMessagingMessagesBodyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostMessagingMessagesBodyType = {
  text: 'text',
  image: 'image',
  file: 'file',
  voice: 'voice',
  system: 'system',
} as const;
