/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthImpersonateStudentId200Data } from './postAuthImpersonateStudentId200Data';

/**
 * Success response model
 */
export type PostAuthImpersonateStudentId200 = {
  success: boolean;
  message: string;
  /** Authentication response model */
  data: PostAuthImpersonateStudentId200Data;
};
