/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PostMessagingMessagesBodyType } from './postMessagingMessagesBodyType';
import type { PostMessagingMessagesBodyTimestamp } from './postMessagingMessagesBodyTimestamp';
import type { PostMessagingMessagesBodyAttachmentsItem } from './postMessagingMessagesBodyAttachmentsItem';

export type PostMessagingMessagesBody = {
  /** @minLength 1 */
  senderId: string;
  chatId?: string;
  recipientIds?: string[];
  content?: string;
  type?: PostMessagingMessagesBodyType;
  replyToMessageId?: string;
  timestamp?: PostMessagingMessagesBodyTimestamp;
  attachments?: PostMessagingMessagesBodyAttachmentsItem[];
};
