/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PostActivityBodyActionType } from './postActivityBodyActionType';
import type { PostActivityBodyEntityType } from './postActivityBodyEntityType';

/**
 * Schema for creating a new activity record
 */
export type PostActivityBody = {
  action_type: PostActivityBodyActionType;
  entity_type: PostActivityBodyEntityType;
  /** @minLength 1 */
  entity_id: string;
  /** @minLength 1 */
  entity_name: string;
  /** @minLength 1 */
  performed_by: string;
  details?: string;
};
