/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PostMessagingChatsChatIdRead200Data } from './postMessagingChatsChatIdRead200Data';

export type PostMessagingChatsChatIdRead200 = {
  success: boolean;
  message: string;
  data: PostMessagingChatsChatIdRead200Data;
};
