/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PostMessagingAttachmentsUpload201AttachmentsItem } from './postMessagingAttachmentsUpload201AttachmentsItem';

export type PostMessagingAttachmentsUpload201 = {
  success: boolean;
  message: string;
  attachments: PostMessagingAttachmentsUpload201AttachmentsItem[];
  processing: boolean;
  errors?: string[];
};
