/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for removing a teacher from a session
 */
export type PostSessionsRemoveTeacherBody = {
  /** @minLength 1 */
  session_id: string;
  /** @minLength 1 */
  teacher_id: string;
};
