/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PostTaxisBodyCefrLevel } from './postTaxisBodyCefrLevel';

/**
 * Schema for creating a new taxi
 */
export type PostTaxisBody = {
  /** @minLength 1 */
  name: string;
  color?: string;
  branch?: string;
  subject?: string;
  level?: string;
  /** @minLength 1 */
  academic_year: string;
  /** @minLength 1 */
  academic_period: string;
  academic_subperiods?: string[];
  cefr_level?: PostTaxisBodyCefrLevel;
  users?: string[];
  scap_products?: string[];
};
