/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiV1AbsencesId200DataStudentAnyOf } from './putApiV1AbsencesId200DataStudentAnyOf';

export type PutApiV1AbsencesId200DataStudent = string | PutApiV1AbsencesId200DataStudentAnyOf;
