/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiV1AbsencesId200DataSessionAnyOfStartDate } from './putApiV1AbsencesId200DataSessionAnyOfStartDate';
import type { PutApiV1AbsencesId200DataSessionAnyOfEndDate } from './putApiV1AbsencesId200DataSessionAnyOfEndDate';

export type PutApiV1AbsencesId200DataSessionAnyOf = {
  _id: string;
  start_date: PutApiV1AbsencesId200DataSessionAnyOfStartDate;
  end_date: PutApiV1AbsencesId200DataSessionAnyOfEndDate;
};
