/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type PutApiV1AbsencesIdBodyStatus = typeof PutApiV1AbsencesIdBodyStatus[keyof typeof PutApiV1AbsencesIdBodyStatus];


 
export const PutApiV1AbsencesIdBodyStatus = {
  unexcused: 'unexcused',
  excused: 'excused',
  justified: 'justified',
} as const;
