/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type PutAcademicPeriodsIdBody = {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  name?: string;
  start_date?: string;
  end_date?: string;
  /** @minLength 1 */
  academic_year?: string;
};
