/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiV1AbsencesId200DataSession } from './putApiV1AbsencesId200DataSession';
import type { PutApiV1AbsencesId200DataStudent } from './putApiV1AbsencesId200DataStudent';
import type { PutApiV1AbsencesId200DataDate } from './putApiV1AbsencesId200DataDate';
import type { PutApiV1AbsencesId200DataStatus } from './putApiV1AbsencesId200DataStatus';
import type { PutApiV1AbsencesId200DataTaxi } from './putApiV1AbsencesId200DataTaxi';
import type { PutApiV1AbsencesId200DataAcademicPeriod } from './putApiV1AbsencesId200DataAcademicPeriod';
import type { PutApiV1AbsencesId200DataNotificationDate } from './putApiV1AbsencesId200DataNotificationDate';
import type { PutApiV1AbsencesId200DataCreatedAt } from './putApiV1AbsencesId200DataCreatedAt';
import type { PutApiV1AbsencesId200DataUpdatedAt } from './putApiV1AbsencesId200DataUpdatedAt';

/**
 * Absence model
 */
export type PutApiV1AbsencesId200Data = {
  _id: string;
  session: PutApiV1AbsencesId200DataSession;
  student: PutApiV1AbsencesId200DataStudent;
  date: PutApiV1AbsencesId200DataDate;
  reason?: string;
  status: PutApiV1AbsencesId200DataStatus;
  justification_document?: string;
  taxi: PutApiV1AbsencesId200DataTaxi;
  academic_period: PutApiV1AbsencesId200DataAcademicPeriod;
  note?: string;
  notified_parent: boolean;
  notification_date?: PutApiV1AbsencesId200DataNotificationDate;
  createdAt: PutApiV1AbsencesId200DataCreatedAt;
  updatedAt: PutApiV1AbsencesId200DataUpdatedAt;
};
