/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PutAbsencesId200DataSession } from './putAbsencesId200DataSession';
import type { PutAbsencesId200DataStudent } from './putAbsencesId200DataStudent';
import type { PutAbsencesId200DataTaxi } from './putAbsencesId200DataTaxi';

export type PutAbsencesId200Data = {
  session: PutAbsencesId200DataSession;
  student: PutAbsencesId200DataStudent;
  date: string;
  reason: string;
  status: string;
  taxi: PutAbsencesId200DataTaxi;
  academic_period: string;
  notified_parent: boolean;
  createdAt: string;
  updatedAt: string;
  id: string;
  note?: string;
  notification_date?: string;
};
