/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PutAssignmentsStaffIdBodyTasksItemResourceType } from './putAssignmentsStaffIdBodyTasksItemResourceType';
import type { PutAssignmentsStaffIdBodyTasksItemOpenTaskType } from './putAssignmentsStaffIdBodyTasksItemOpenTaskType';
import type { PutAssignmentsStaffIdBodyTasksItemAssignedAs } from './putAssignmentsStaffIdBodyTasksItemAssignedAs';

/**
 * Task details for an assignment
 */
export type PutAssignmentsStaffIdBodyTasksItem = {
  resourceType: PutAssignmentsStaffIdBodyTasksItemResourceType;
  ebookID?: string;
  ebookActivityID?: string;
  customActivityID?: string;
  openTaskType?: PutAssignmentsStaffIdBodyTasksItemOpenTaskType;
  openTaskTitle?: string;
  openTaskInstructions?: string;
  assignedAs: PutAssignmentsStaffIdBodyTasksItemAssignedAs;
  instructions?: string;
};
