/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PutAssignmentsStaffIdBodyStaffRole } from './putAssignmentsStaffIdBodyStaffRole';
import type { PutAssignmentsStaffIdBodyStartDate } from './putAssignmentsStaffIdBodyStartDate';
import type { PutAssignmentsStaffIdBodyEndDate } from './putAssignmentsStaffIdBodyEndDate';
import type { PutAssignmentsStaffIdBodyTasksItem } from './putAssignmentsStaffIdBodyTasksItem';
import type { PutAssignmentsStaffIdBodyAcademicTimeframe } from './putAssignmentsStaffIdBodyAcademicTimeframe';

/**
 * Schema for updating an existing assignment for staff
 */
export type PutAssignmentsStaffIdBody = {
  schoolID?: string;
  branchID?: string;
  staffID?: string;
  staffRole?: PutAssignmentsStaffIdBodyStaffRole;
  classID?: string;
  studentsIDs?: string[];
  /**
   * @minLength 1
   * @maxLength 200
   */
  title?: string;
  startDate?: PutAssignmentsStaffIdBodyStartDate;
  endDate?: PutAssignmentsStaffIdBodyEndDate;
  description?: string;
  tasks?: PutAssignmentsStaffIdBodyTasksItem[];
  academicTimeframe?: PutAssignmentsStaffIdBodyAcademicTimeframe;
  isDrafted?: boolean;
  isDeletedForMe?: boolean;
  isDeletedForEveryone?: boolean;
  isPermanentlyDeleted?: boolean;
};
