/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type PutAbsencesIdBodyStatus = typeof PutAbsencesIdBodyStatus[keyof typeof PutAbsencesIdBodyStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutAbsencesIdBodyStatus = {
  unexcused: 'unexcused',
  excused: 'excused',
  justified: 'justified',
} as const;
