/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type PutAbsencesId200DataStudent = {
  firstname: string;
  lastname: string;
  email: string;
  phone: string;
  user_type: string;
  primaryRoleTitle: string;
  class: string;
  id: string;
};
