/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type PutAcademicYearsIdBody = {
  /** @minLength 1 */
  name?: string;
  start_date?: string;
  end_date?: string;
  is_manual_active?: boolean;
  notes?: string;
};
