/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type PutApiV1AbsencesId200DataStatus = typeof PutApiV1AbsencesId200DataStatus[keyof typeof PutApiV1AbsencesId200DataStatus];


 
export const PutApiV1AbsencesId200DataStatus = {
  unexcused: 'unexcused',
  excused: 'excused',
  justified: 'justified',
} as const;
