/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

export type PutAssignmentsStudentIdBodyTasksItemAssignedAs = typeof PutAssignmentsStudentIdBodyTasksItemAssignedAs[keyof typeof PutAssignmentsStudentIdBodyTasksItemAssignedAs];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutAssignmentsStudentIdBodyTasksItemAssignedAs = {
  exercise: 'exercise',
  exam: 'exam',
} as const;
