/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type PutCustomersIdBodyCustomerType = typeof PutCustomersIdBodyCustomerType[keyof typeof PutCustomersIdBodyCustomerType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutCustomersIdBodyCustomerType = {
  PRIVATE_SCHOOL: 'PRIVATE_SCHOOL',
  PRIVATE_TUTORING: 'PRIVATE_TUTORING',
  PUBLIC_SCHOOL: 'PUBLIC_SCHOOL',
  PRIVATE_PROFESSOR: 'PRIVATE_PROFESSOR',
  SELF_TAUGHT_PROFESSOR: 'SELF_TAUGHT_PROFESSOR',
  SUB_STORE: 'SUB_STORE',
} as const;
