/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PutClassroomsIdBodyType } from './putClassroomsIdBodyType';
import type { PutClassroomsIdBodyAvailability } from './putClassroomsIdBodyAvailability';

/**
 * Schema for updating an existing classroom
 */
export type PutClassroomsIdBody = {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  name?: string;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  capacity?: number;
  location?: string;
  equipment?: string[];
  customer?: string;
  type?: PutClassroomsIdBodyType;
  description?: string;
  availability?: PutClassroomsIdBodyAvailability;
};
