/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PutCustomersMainBodyCustomerType } from './putCustomersMainBodyCustomerType';

/**
 * Schema for updating an existing customer
 */
export type PutCustomersMainBody = {
  /** @minLength 1 */
  name?: string;
  /** @minLength 1 */
  slug?: string;
  nickname?: string;
  afm?: string;
  facebook?: string;
  instagram?: string;
  twitter?: string;
  youtube?: string;
  avatar?: string;
  website?: string;
  customer_type?: PutCustomersMainBodyCustomerType;
  erp_code?: string;
  scrap_id?: string;
  is_primary?: boolean;
  is_main_customer?: boolean;
  email?: string;
  description?: string;
  order?: number;
  administrator?: string;
  manager?: string;
  address?: string;
  phone?: string;
  code?: string;
  vat?: string;
  mapLocation?: string;
};
