/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PutElibraryIdBodyType } from './putElibraryIdBodyType';

/**
 * Schema for updating an existing E-Library item
 */
export type PutElibraryIdBody = {
  /** @minLength 1 */
  id: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  title?: string;
  description?: string;
  type?: PutElibraryIdBodyType;
  url?: string;
  file?: string;
  author?: string;
  tags?: string[];
  published_at?: string;
};
