/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PutInventoryIdBodyItemType } from './putInventoryIdBodyItemType';

/**
 * Schema for updating an existing inventory item
 */
export type PutInventoryIdBody = {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  user?: string;
  /** @minLength 1 */
  title?: string;
  billing_date?: string;
  return_date?: string;
  notes?: string;
  /** @minLength 1 */
  customer?: string;
  item_type?: PutInventoryIdBodyItemType;
};
