/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { PutPostsIdBodyStatus } from './putPostsIdBodyStatus';

/**
 * Schema for updating an existing post
 */
export type PutPostsIdBody = {
  /** @minLength 1 */
  id: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  title?: string;
  /** @minLength 1 */
  content?: string;
  /** @minLength 1 */
  author?: string;
  tags?: string[];
  status?: PutPostsIdBodyStatus;
  featured_image?: string;
};
