/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type PutSessionsIdBodyMode = typeof PutSessionsIdBodyMode[keyof typeof PutSessionsIdBodyMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutSessionsIdBodyMode = {
  in_person: 'in_person',
  online: 'online',
  hybrid: 'hybrid',
} as const;
