/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type PutSessionsIdBodyDay = typeof PutSessionsIdBodyDay[keyof typeof PutSessionsIdBodyDay];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutSessionsIdBodyDay = {
  monday: 'monday',
  tuesday: 'tuesday',
  wednesday: 'wednesday',
  thursday: 'thursday',
  friday: 'friday',
  saturday: 'saturday',
  sunday: 'sunday',
} as const;
