/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PutTaxisIdBodyCefrLevel } from './putTaxisIdBodyCefrLevel';

/**
 * Schema for updating an existing taxi
 */
export type PutTaxisIdBody = {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  name?: string;
  code?: string;
  color?: string;
  branch?: string;
  subject?: string;
  level?: string;
  /** @minLength 1 */
  academic_year?: string;
  /** @minLength 1 */
  academic_period?: string;
  academic_subperiods?: string[];
  cefr_level?: PutTaxisIdBodyCefrLevel;
  users?: string[];
  scap_products?: string[];
  archived?: boolean;
  notes?: string;
};
