/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PutUsersStaffIdBodyFacebookLink } from './putUsersStaffIdBodyFacebookLink';
import type { PutUsersStaffIdBodyTwitterLink } from './putUsersStaffIdBodyTwitterLink';
import type { PutUsersStaffIdBodyLinkedinLink } from './putUsersStaffIdBodyLinkedinLink';

export type PutUsersStaffIdBody = {
  id: string;
  /** @minLength 3 */
  username?: string;
  /** @minLength 1 */
  firstname?: string;
  /** @minLength 1 */
  lastname?: string;
  email?: string;
  /** @minLength 1 */
  phone?: string;
  mobile?: string;
  /** @minLength 6 */
  password?: string;
  city?: string;
  region?: string;
  country?: string;
  address?: string;
  zipcode?: string;
  birthday?: string;
  is_active?: boolean;
  branches?: string[];
  roles?: string[];
  role_title?: string;
  status?: boolean;
  hire_date?: string;
  registration_date?: string;
  facebook_link?: PutUsersStaffIdBodyFacebookLink;
  twitter_link?: PutUsersStaffIdBodyTwitterLink;
  linkedin_link?: PutUsersStaffIdBodyLinkedinLink;
  documents?: string[];
  notes?: string;
  avatar?: string;
};
