/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

/**
 * Contact model
 */
export type PutUsersStudentsIdBodyContactsItem = {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  phone: string;
  email: string;
  /** @minLength 1 */
  relationship: string;
  isPrimaryContact?: boolean;
};
