/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { PutUsersStudentsIdBodyUserType } from './putUsersStudentsIdBodyUserType';
import type { PutUsersStudentsIdBodyContactsItem } from './putUsersStudentsIdBodyContactsItem';
import type { PutUsersStudentsIdBodySiblingAttending } from './putUsersStudentsIdBodySiblingAttending';

export type PutUsersStudentsIdBody = {
  id: string;
  /** @minLength 3 */
  username?: string;
  /** @minLength 1 */
  firstname?: string;
  /** @minLength 1 */
  lastname?: string;
  email?: string;
  /** @minLength 1 */
  phone?: string;
  mobile?: string;
  /** @minLength 6 */
  password?: string;
  city?: string;
  region?: string;
  country?: string;
  address?: string;
  zipcode?: string;
  birthday?: string;
  is_active?: boolean;
  customers?: string[];
  roles?: string[];
  branches?: string[];
  user_type?: PutUsersStudentsIdBodyUserType;
  contacts?: PutUsersStudentsIdBodyContactsItem[];
  siblingAttending?: PutUsersStudentsIdBodySiblingAttending;
  hasAllergies?: boolean;
  healthDetails?: string;
  generalNotes?: string;
  default_branch?: string;
  avatar?: string;
  documents?: string[];
  notes?: string;
};
