/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';

/**
 * Success response model
 */
export type PutUsersSingleId200 = {
  data: User;
  success: boolean;
  status: number;
};
