/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

/**
 * Details of a populated academic subperiod object
 */
export type SessionAcademicSubperiod = {
  id: string;
  name: string;
};
