/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type TaxiTeachersItem = {
  id: string;
  firstname: string;
  lastname: string;
  email?: string;
  phone?: string;
  user_type?: string;
  code?: string;
  birthday?: string;
};
