/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { TaxiSessionsItemClassroom } from './taxiSessionsItemClassroom';
import type { TaxiSessionsItemTeachersItem } from './taxiSessionsItemTeachersItem';
import type { TaxiSessionsItemStudentsItem } from './taxiSessionsItemStudentsItem';

export type TaxiSessionsItem = {
  id: string;
  start_date: string;
  end_date: string;
  classroom?: TaxiSessionsItemClassroom;
  teachers?: TaxiSessionsItemTeachersItem[];
  students?: TaxiSessionsItemStudentsItem[];
};
