/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */

export type TaxiCefrLevel = typeof TaxiCefrLevel[keyof typeof TaxiCefrLevel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaxiCefrLevel = {
  A1: 'A1',
  A2: 'A2',
  B1: 'B1',
  B2: 'B2',
  C1: 'C1',
  C2: 'C2',
} as const;
