/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import type { TaxiAcademicYear } from './taxiAcademicYear';
import type { TaxiAcademicPeriod } from './taxiAcademicPeriod';
import type { TaxiCefrLevel } from './taxiCefrLevel';
import type { TaxiUsersItem } from './taxiUsersItem';
import type { TaxiSessionsItem } from './taxiSessionsItem';
import type { TaxiSessionStats } from './taxiSessionStats';
import type { TaxiTeachersItem } from './taxiTeachersItem';
import type { TaxiStudentsItem } from './taxiStudentsItem';

/**
 * Taxi model with populated session statistics and user data
 */
export interface Taxi {
  id: string;
  name: string;
  code: string;
  color?: string;
  branch?: string;
  subject?: string;
  level?: string;
  academic_year?: TaxiAcademicYear;
  academic_period?: TaxiAcademicPeriod;
  academic_subperiods?: string[];
  cefr_level?: TaxiCefrLevel;
  users?: TaxiUsersItem[];
  scap_products?: string[];
  archived?: boolean;
  notes?: string;
  sessions?: TaxiSessionsItem[];
  sessionStats?: TaxiSessionStats;
  teachers?: TaxiTeachersItem[];
  students?: TaxiStudentsItem[];
  teacherCount?: number;
  studentCount?: number;
  createdAt: string;
  updatedAt: string;
}
