/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */

/**
 * Branch model
 */
export type UserBranchesItem = {
  name: string;
  slug: string;
  customer_type: string;
  is_primary: boolean;
  is_main_customer: boolean;
  email: string;
  users: string[];
  administrator?: string;
  manager?: string;
  address?: string;
  phone?: string;
  code?: string;
  vat?: string;
  mapLocation?: string;
  createdAt: string;
  updatedAt: string;
  id: string;
};
