/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  PostAcademicYearsBody,
  PutAcademicYearsIdBody
} from '.././schemas';



type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class AcademicYearsService {
  constructor(
    private http: HttpClient,
  ) {}/**
 * Retrieve a list of all academic years
 * @summary Get all academic years
 */
 getAcademicYears<TData = void>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAcademicYears<TData = void>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAcademicYears<TData = void>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAcademicYears<TData = void>(
     options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/academic-years`,options
    );
  }
/**
 * Create a new academic year with the given details
 * @summary Create a new academic year
 */
 postAcademicYears<TData = void>(
    postAcademicYearsBody: PostAcademicYearsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postAcademicYears<TData = void>(
    postAcademicYearsBody: PostAcademicYearsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postAcademicYears<TData = void>(
    postAcademicYearsBody: PostAcademicYearsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postAcademicYears<TData = void>(
    postAcademicYearsBody: PostAcademicYearsBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/academic-years`,
      postAcademicYearsBody,options
    );
  }
/**
 * Retrieve details of a specific academic year by ID
 * @summary Get academic year by ID
 */
 getAcademicYearsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAcademicYearsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAcademicYearsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAcademicYearsId<TData = void>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/academic-years/${id}`,options
    );
  }
/**
 * Update details of a specific academic year
 * @summary Update academic year
 */
 putAcademicYearsId<TData = void>(
    id: string,
    putAcademicYearsIdBody: PutAcademicYearsIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    putAcademicYearsId<TData = void>(
    id: string,
    putAcademicYearsIdBody: PutAcademicYearsIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    putAcademicYearsId<TData = void>(
    id: string,
    putAcademicYearsIdBody: PutAcademicYearsIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;putAcademicYearsId<TData = void>(
    id: string,
    putAcademicYearsIdBody: PutAcademicYearsIdBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.put<TData>(
      `http://localhost:3193/v1/academic-years/${id}`,
      putAcademicYearsIdBody,options
    );
  }
/**
 * Delete a specific academic year
 * @summary Delete academic year
 */
 deleteAcademicYearsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    deleteAcademicYearsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    deleteAcademicYearsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;deleteAcademicYearsId<TData = void>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.delete<TData>(
      `http://localhost:3193/v1/academic-years/${id}`,options
    );
  }
/**
 * Retrieve the current academic year
 * @summary Get current academic year
 */
 getAcademicYearsCurrent<TData = void>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAcademicYearsCurrent<TData = void>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAcademicYearsCurrent<TData = void>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAcademicYearsCurrent<TData = void>(
     options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/academic-years/current`,options
    );
  }
};

export type GetAcademicYearsClientResult = NonNullable<void>
export type PostAcademicYearsClientResult = NonNullable<void>
export type GetAcademicYearsIdClientResult = NonNullable<void>
export type PutAcademicYearsIdClientResult = NonNullable<void>
export type DeleteAcademicYearsIdClientResult = NonNullable<void>
export type GetAcademicYearsCurrentClientResult = NonNullable<void>
