/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  DeleteAssignmentsStaffDeleteForEveryoneId200,
  DeleteAssignmentsStaffDeleteForMeId200,
  GetAssignmentsStaff200,
  GetAssignmentsStaffId200,
  GetAssignmentsStaffParams,
  PatchAssignmentsStaffDeleteForEveryoneId200,
  PatchAssignmentsStaffDeleteForMeId200,
  PatchAssignmentsStaffDraftId200,
  PatchAssignmentsStaffRestoreForEveryoneId200,
  PatchAssignmentsStaffRestoreForMeId200,
  PatchAssignmentsStaffUndraftId200,
  PostAssignmentsStaff201,
  PostAssignmentsStaffBody,
  PutAssignmentsStaffId200,
  PutAssignmentsStaffIdBody
} from '.././schemas';



type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class AssignmentsForStaffService {
  constructor(
    private http: HttpClient,
  ) {}/**
 * Retrieve a list of all assignments created by staff members with optional filtering.
 * @summary Get all assignments
 */
 getAssignmentsStaff<TData = GetAssignmentsStaff200>(
    params: GetAssignmentsStaffParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAssignmentsStaff<TData = GetAssignmentsStaff200>(
    params: GetAssignmentsStaffParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAssignmentsStaff<TData = GetAssignmentsStaff200>(
    params: GetAssignmentsStaffParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAssignmentsStaff<TData = GetAssignmentsStaff200>(
    params: GetAssignmentsStaffParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/assignments/staff`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Create a new assignment by staff member (admin, manager, teacher).
 * @summary Create a new assignment
 */
 postAssignmentsStaff<TData = PostAssignmentsStaff201>(
    postAssignmentsStaffBody: PostAssignmentsStaffBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postAssignmentsStaff<TData = PostAssignmentsStaff201>(
    postAssignmentsStaffBody: PostAssignmentsStaffBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postAssignmentsStaff<TData = PostAssignmentsStaff201>(
    postAssignmentsStaffBody: PostAssignmentsStaffBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postAssignmentsStaff<TData = PostAssignmentsStaff201>(
    postAssignmentsStaffBody: PostAssignmentsStaffBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/assignments/staff`,
      postAssignmentsStaffBody,options
    );
  }
/**
 * Retrieve details of a specific assignment by its ID.
 * @summary Get assignment by ID
 */
 getAssignmentsStaffId<TData = GetAssignmentsStaffId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAssignmentsStaffId<TData = GetAssignmentsStaffId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAssignmentsStaffId<TData = GetAssignmentsStaffId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAssignmentsStaffId<TData = GetAssignmentsStaffId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/assignments/staff/${id}`,options
    );
  }
/**
 * Update details of a specific assignment by its ID.
 * @summary Update assignment by ID
 */
 putAssignmentsStaffId<TData = PutAssignmentsStaffId200>(
    id: string,
    putAssignmentsStaffIdBody: PutAssignmentsStaffIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    putAssignmentsStaffId<TData = PutAssignmentsStaffId200>(
    id: string,
    putAssignmentsStaffIdBody: PutAssignmentsStaffIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    putAssignmentsStaffId<TData = PutAssignmentsStaffId200>(
    id: string,
    putAssignmentsStaffIdBody: PutAssignmentsStaffIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;putAssignmentsStaffId<TData = PutAssignmentsStaffId200>(
    id: string,
    putAssignmentsStaffIdBody: PutAssignmentsStaffIdBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.put<TData>(
      `http://localhost:3193/v1/assignments/staff/${id}`,
      putAssignmentsStaffIdBody,options
    );
  }
/**
 * Toggle the draft status of a assignment to drafted.
 * @summary Toggle draft status to drafted.
 */
 patchAssignmentsStaffDraftId<TData = PatchAssignmentsStaffDraftId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchAssignmentsStaffDraftId<TData = PatchAssignmentsStaffDraftId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchAssignmentsStaffDraftId<TData = PatchAssignmentsStaffDraftId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchAssignmentsStaffDraftId<TData = PatchAssignmentsStaffDraftId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/assignments/staff/draft/${id}`,undefined,options
    );
  }
/**
 * Toggle the draft status of a assignment to undrafted.
 * @summary Toggle draft status to undrafted.
 */
 patchAssignmentsStaffUndraftId<TData = PatchAssignmentsStaffUndraftId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchAssignmentsStaffUndraftId<TData = PatchAssignmentsStaffUndraftId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchAssignmentsStaffUndraftId<TData = PatchAssignmentsStaffUndraftId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchAssignmentsStaffUndraftId<TData = PatchAssignmentsStaffUndraftId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/assignments/staff/undraft/${id}`,undefined,options
    );
  }
/**
 * Mark assignment as deleted for the current user (soft delete for me).
 * @summary Delete assignment for me.
 */
 patchAssignmentsStaffDeleteForMeId<TData = PatchAssignmentsStaffDeleteForMeId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchAssignmentsStaffDeleteForMeId<TData = PatchAssignmentsStaffDeleteForMeId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchAssignmentsStaffDeleteForMeId<TData = PatchAssignmentsStaffDeleteForMeId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchAssignmentsStaffDeleteForMeId<TData = PatchAssignmentsStaffDeleteForMeId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/assignments/staff/delete-for-me/${id}`,undefined,options
    );
  }
/**
 * Permanently delete assignment for the current user.
 * @summary Delete assignment permanently for me.
 */
 deleteAssignmentsStaffDeleteForMeId<TData = DeleteAssignmentsStaffDeleteForMeId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    deleteAssignmentsStaffDeleteForMeId<TData = DeleteAssignmentsStaffDeleteForMeId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    deleteAssignmentsStaffDeleteForMeId<TData = DeleteAssignmentsStaffDeleteForMeId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;deleteAssignmentsStaffDeleteForMeId<TData = DeleteAssignmentsStaffDeleteForMeId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.delete<TData>(
      `http://localhost:3193/v1/assignments/staff/delete-for-me/${id}`,options
    );
  }
/**
 * Restore a previously deleted assignment for the current user.
 * @summary Restore assignment for me.
 */
 patchAssignmentsStaffRestoreForMeId<TData = PatchAssignmentsStaffRestoreForMeId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchAssignmentsStaffRestoreForMeId<TData = PatchAssignmentsStaffRestoreForMeId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchAssignmentsStaffRestoreForMeId<TData = PatchAssignmentsStaffRestoreForMeId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchAssignmentsStaffRestoreForMeId<TData = PatchAssignmentsStaffRestoreForMeId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/assignments/staff/restore-for-me/${id}`,undefined,options
    );
  }
/**
 * Mark assignment as deleted for all users (soft delete for everyone).
 * @summary Delete assignment for everyone.
 */
 patchAssignmentsStaffDeleteForEveryoneId<TData = PatchAssignmentsStaffDeleteForEveryoneId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchAssignmentsStaffDeleteForEveryoneId<TData = PatchAssignmentsStaffDeleteForEveryoneId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchAssignmentsStaffDeleteForEveryoneId<TData = PatchAssignmentsStaffDeleteForEveryoneId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchAssignmentsStaffDeleteForEveryoneId<TData = PatchAssignmentsStaffDeleteForEveryoneId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/assignments/staff/delete-for-everyone/${id}`,undefined,options
    );
  }
/**
 * Permanently delete assignment for all users.
 * @summary Delete assignment permanently for everyone.
 */
 deleteAssignmentsStaffDeleteForEveryoneId<TData = DeleteAssignmentsStaffDeleteForEveryoneId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    deleteAssignmentsStaffDeleteForEveryoneId<TData = DeleteAssignmentsStaffDeleteForEveryoneId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    deleteAssignmentsStaffDeleteForEveryoneId<TData = DeleteAssignmentsStaffDeleteForEveryoneId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;deleteAssignmentsStaffDeleteForEveryoneId<TData = DeleteAssignmentsStaffDeleteForEveryoneId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.delete<TData>(
      `http://localhost:3193/v1/assignments/staff/delete-for-everyone/${id}`,options
    );
  }
/**
 * Restore a previously deleted assignment for all users.
 * @summary Restore assignment for everyone.
 */
 patchAssignmentsStaffRestoreForEveryoneId<TData = PatchAssignmentsStaffRestoreForEveryoneId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchAssignmentsStaffRestoreForEveryoneId<TData = PatchAssignmentsStaffRestoreForEveryoneId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchAssignmentsStaffRestoreForEveryoneId<TData = PatchAssignmentsStaffRestoreForEveryoneId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchAssignmentsStaffRestoreForEveryoneId<TData = PatchAssignmentsStaffRestoreForEveryoneId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/assignments/staff/restore-for-everyone/${id}`,undefined,options
    );
  }
};

export type GetAssignmentsStaffClientResult = NonNullable<GetAssignmentsStaff200>
export type PostAssignmentsStaffClientResult = NonNullable<PostAssignmentsStaff201>
export type GetAssignmentsStaffIdClientResult = NonNullable<GetAssignmentsStaffId200>
export type PutAssignmentsStaffIdClientResult = NonNullable<PutAssignmentsStaffId200>
export type PatchAssignmentsStaffDraftIdClientResult = NonNullable<PatchAssignmentsStaffDraftId200>
export type PatchAssignmentsStaffUndraftIdClientResult = NonNullable<PatchAssignmentsStaffUndraftId200>
export type PatchAssignmentsStaffDeleteForMeIdClientResult = NonNullable<PatchAssignmentsStaffDeleteForMeId200>
export type DeleteAssignmentsStaffDeleteForMeIdClientResult = NonNullable<DeleteAssignmentsStaffDeleteForMeId200>
export type PatchAssignmentsStaffRestoreForMeIdClientResult = NonNullable<PatchAssignmentsStaffRestoreForMeId200>
export type PatchAssignmentsStaffDeleteForEveryoneIdClientResult = NonNullable<PatchAssignmentsStaffDeleteForEveryoneId200>
export type DeleteAssignmentsStaffDeleteForEveryoneIdClientResult = NonNullable<DeleteAssignmentsStaffDeleteForEveryoneId200>
export type PatchAssignmentsStaffRestoreForEveryoneIdClientResult = NonNullable<PatchAssignmentsStaffRestoreForEveryoneId200>
