/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  GetInventory200,
  GetInventoryId200,
  GetInventoryParams,
  PostInventory201,
  PostInventoryBody,
  PutInventoryId200,
  PutInventoryIdBody
} from '.././schemas';



type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class InventoryService {
  constructor(
    private http: HttpClient,
  ) {}/**
 * Retrieve a list of all inventory items with optional filtering
 * @summary Get all inventory items
 */
 getInventory<TData = GetInventory200>(
    params?: GetInventoryParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getInventory<TData = GetInventory200>(
    params?: GetInventoryParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getInventory<TData = GetInventory200>(
    params?: GetInventoryParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getInventory<TData = GetInventory200>(
    params?: GetInventoryParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/inventory`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Create a new inventory item with the given details
 * @summary Create a new inventory item
 */
 postInventory<TData = PostInventory201>(
    postInventoryBody: PostInventoryBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postInventory<TData = PostInventory201>(
    postInventoryBody: PostInventoryBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postInventory<TData = PostInventory201>(
    postInventoryBody: PostInventoryBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postInventory<TData = PostInventory201>(
    postInventoryBody: PostInventoryBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/inventory`,
      postInventoryBody,options
    );
  }
/**
 * Retrieve details of a specific inventory item by ID
 * @summary Get inventory item by ID
 */
 getInventoryId<TData = GetInventoryId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getInventoryId<TData = GetInventoryId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getInventoryId<TData = GetInventoryId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getInventoryId<TData = GetInventoryId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/inventory/${id}`,options
    );
  }
/**
 * Update details of a specific inventory item
 * @summary Update inventory item
 */
 putInventoryId<TData = PutInventoryId200>(
    id: string,
    putInventoryIdBody: PutInventoryIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    putInventoryId<TData = PutInventoryId200>(
    id: string,
    putInventoryIdBody: PutInventoryIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    putInventoryId<TData = PutInventoryId200>(
    id: string,
    putInventoryIdBody: PutInventoryIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;putInventoryId<TData = PutInventoryId200>(
    id: string,
    putInventoryIdBody: PutInventoryIdBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.put<TData>(
      `http://localhost:3193/v1/inventory/${id}`,
      putInventoryIdBody,options
    );
  }
/**
 * Delete a specific inventory item
 * @summary Delete inventory item
 */
 deleteInventoryId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    deleteInventoryId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    deleteInventoryId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;deleteInventoryId<TData = void>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.delete<TData>(
      `http://localhost:3193/v1/inventory/${id}`,options
    );
  }
/**
 * Mark a specific inventory item as returned
 * @summary Mark inventory item as returned
 */
 patchInventoryIdMarkReturned<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchInventoryIdMarkReturned<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchInventoryIdMarkReturned<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchInventoryIdMarkReturned<TData = void>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/inventory/${id}/mark-returned`,undefined,options
    );
  }
};

export type GetInventoryClientResult = NonNullable<GetInventory200>
export type PostInventoryClientResult = NonNullable<PostInventory201>
export type GetInventoryIdClientResult = NonNullable<GetInventoryId200>
export type PutInventoryIdClientResult = NonNullable<PutInventoryId200>
export type DeleteInventoryIdClientResult = NonNullable<void>
export type PatchInventoryIdMarkReturnedClientResult = NonNullable<void>
