/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  DeleteAssignmentsStudentDeleteForEveryoneId200,
  DeleteAssignmentsStudentDeleteForMeId200,
  GetAssignmentsStudent200,
  GetAssignmentsStudentEbookAssignmentIdActivityId200,
  GetAssignmentsStudentId200,
  GetAssignmentsStudentParams,
  PatchAssignmentsStudentDeleteForEveryoneId200,
  PatchAssignmentsStudentDeleteForMeId200,
  PatchAssignmentsStudentDraftId200,
  PatchAssignmentsStudentEbookAssignmentIdActivityIdBody,
  PatchAssignmentsStudentRestoreForEveryoneId200,
  PatchAssignmentsStudentRestoreForMeId200,
  PatchAssignmentsStudentUndraftId200,
  PostAssignmentsStudent201,
  PostAssignmentsStudentBody,
  PutAssignmentsStudentId200,
  PutAssignmentsStudentIdBody
} from '.././schemas';



type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class AssignmentsForStudentsService {
  constructor(
    private http: HttpClient,
  ) {}/**
 * Retrieve a list of all assignments assigned to students with optional filtering.
 * @summary Get all student assignments
 */
 getAssignmentsStudent<TData = GetAssignmentsStudent200>(
    params: GetAssignmentsStudentParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAssignmentsStudent<TData = GetAssignmentsStudent200>(
    params: GetAssignmentsStudentParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAssignmentsStudent<TData = GetAssignmentsStudent200>(
    params: GetAssignmentsStudentParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAssignmentsStudent<TData = GetAssignmentsStudent200>(
    params: GetAssignmentsStudentParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/assignments/student`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Create a new assignment for a specific student or class.
 * @summary Create a new student assignment
 */
 postAssignmentsStudent<TData = PostAssignmentsStudent201>(
    postAssignmentsStudentBody: PostAssignmentsStudentBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postAssignmentsStudent<TData = PostAssignmentsStudent201>(
    postAssignmentsStudentBody: PostAssignmentsStudentBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postAssignmentsStudent<TData = PostAssignmentsStudent201>(
    postAssignmentsStudentBody: PostAssignmentsStudentBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postAssignmentsStudent<TData = PostAssignmentsStudent201>(
    postAssignmentsStudentBody: PostAssignmentsStudentBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/assignments/student`,
      postAssignmentsStudentBody,options
    );
  }
/**
 * Retrieve details of a specific student assignment by its ID.
 * @summary Get student assignment by ID
 */
 getAssignmentsStudentId<TData = GetAssignmentsStudentId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAssignmentsStudentId<TData = GetAssignmentsStudentId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAssignmentsStudentId<TData = GetAssignmentsStudentId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAssignmentsStudentId<TData = GetAssignmentsStudentId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/assignments/student/${id}`,options
    );
  }
/**
 * Update details of a specific student assignment by its ID.
 * @summary Update student assignment by ID
 */
 putAssignmentsStudentId<TData = PutAssignmentsStudentId200>(
    id: string,
    putAssignmentsStudentIdBody: PutAssignmentsStudentIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    putAssignmentsStudentId<TData = PutAssignmentsStudentId200>(
    id: string,
    putAssignmentsStudentIdBody: PutAssignmentsStudentIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    putAssignmentsStudentId<TData = PutAssignmentsStudentId200>(
    id: string,
    putAssignmentsStudentIdBody: PutAssignmentsStudentIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;putAssignmentsStudentId<TData = PutAssignmentsStudentId200>(
    id: string,
    putAssignmentsStudentIdBody: PutAssignmentsStudentIdBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.put<TData>(
      `http://localhost:3193/v1/assignments/student/${id}`,
      putAssignmentsStudentIdBody,options
    );
  }
/**
 * Toggle the draft status of a student assignment to drafted.
 * @summary Toggle draft status to drafted.
 */
 patchAssignmentsStudentDraftId<TData = PatchAssignmentsStudentDraftId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchAssignmentsStudentDraftId<TData = PatchAssignmentsStudentDraftId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchAssignmentsStudentDraftId<TData = PatchAssignmentsStudentDraftId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchAssignmentsStudentDraftId<TData = PatchAssignmentsStudentDraftId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/assignments/student/draft/${id}`,undefined,options
    );
  }
/**
 * Toggle the draft status of a student assignment to undrafted.
 * @summary Toggle draft status to undrafted.
 */
 patchAssignmentsStudentUndraftId<TData = PatchAssignmentsStudentUndraftId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchAssignmentsStudentUndraftId<TData = PatchAssignmentsStudentUndraftId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchAssignmentsStudentUndraftId<TData = PatchAssignmentsStudentUndraftId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchAssignmentsStudentUndraftId<TData = PatchAssignmentsStudentUndraftId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/assignments/student/undraft/${id}`,undefined,options
    );
  }
/**
 * Mark assignment as deleted for the current student (soft delete for me).
 * @summary Delete assignment for me.
 */
 patchAssignmentsStudentDeleteForMeId<TData = PatchAssignmentsStudentDeleteForMeId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchAssignmentsStudentDeleteForMeId<TData = PatchAssignmentsStudentDeleteForMeId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchAssignmentsStudentDeleteForMeId<TData = PatchAssignmentsStudentDeleteForMeId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchAssignmentsStudentDeleteForMeId<TData = PatchAssignmentsStudentDeleteForMeId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/assignments/student/delete-for-me/${id}`,undefined,options
    );
  }
/**
 * Permanently delete assignment for the current student.
 * @summary Delete assignment permanently for me.
 */
 deleteAssignmentsStudentDeleteForMeId<TData = DeleteAssignmentsStudentDeleteForMeId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    deleteAssignmentsStudentDeleteForMeId<TData = DeleteAssignmentsStudentDeleteForMeId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    deleteAssignmentsStudentDeleteForMeId<TData = DeleteAssignmentsStudentDeleteForMeId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;deleteAssignmentsStudentDeleteForMeId<TData = DeleteAssignmentsStudentDeleteForMeId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.delete<TData>(
      `http://localhost:3193/v1/assignments/student/delete-for-me/${id}`,options
    );
  }
/**
 * Restore a previously deleted assignment for the current student.
 * @summary Restore assignment for me.
 */
 patchAssignmentsStudentRestoreForMeId<TData = PatchAssignmentsStudentRestoreForMeId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchAssignmentsStudentRestoreForMeId<TData = PatchAssignmentsStudentRestoreForMeId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchAssignmentsStudentRestoreForMeId<TData = PatchAssignmentsStudentRestoreForMeId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchAssignmentsStudentRestoreForMeId<TData = PatchAssignmentsStudentRestoreForMeId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/assignments/student/restore-for-me/${id}`,undefined,options
    );
  }
/**
 * Mark assignment as deleted for all users (soft delete for everyone).
 * @summary Delete assignment for everyone.
 */
 patchAssignmentsStudentDeleteForEveryoneId<TData = PatchAssignmentsStudentDeleteForEveryoneId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchAssignmentsStudentDeleteForEveryoneId<TData = PatchAssignmentsStudentDeleteForEveryoneId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchAssignmentsStudentDeleteForEveryoneId<TData = PatchAssignmentsStudentDeleteForEveryoneId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchAssignmentsStudentDeleteForEveryoneId<TData = PatchAssignmentsStudentDeleteForEveryoneId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/assignments/student/delete-for-everyone/${id}`,undefined,options
    );
  }
/**
 * Permanently delete assignment for all users.
 * @summary Delete assignment permanently for everyone.
 */
 deleteAssignmentsStudentDeleteForEveryoneId<TData = DeleteAssignmentsStudentDeleteForEveryoneId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    deleteAssignmentsStudentDeleteForEveryoneId<TData = DeleteAssignmentsStudentDeleteForEveryoneId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    deleteAssignmentsStudentDeleteForEveryoneId<TData = DeleteAssignmentsStudentDeleteForEveryoneId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;deleteAssignmentsStudentDeleteForEveryoneId<TData = DeleteAssignmentsStudentDeleteForEveryoneId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.delete<TData>(
      `http://localhost:3193/v1/assignments/student/delete-for-everyone/${id}`,options
    );
  }
/**
 * Restore a previously deleted assignment for all users.
 * @summary Restore assignment for everyone.
 */
 patchAssignmentsStudentRestoreForEveryoneId<TData = PatchAssignmentsStudentRestoreForEveryoneId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchAssignmentsStudentRestoreForEveryoneId<TData = PatchAssignmentsStudentRestoreForEveryoneId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchAssignmentsStudentRestoreForEveryoneId<TData = PatchAssignmentsStudentRestoreForEveryoneId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchAssignmentsStudentRestoreForEveryoneId<TData = PatchAssignmentsStudentRestoreForEveryoneId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/assignments/student/restore-for-everyone/${id}`,undefined,options
    );
  }
/**
 * Retrieve an ebook assignment
 * @summary Get ebook assignment
 */
 getAssignmentsStudentEbookAssignmentIdActivityId<TData = GetAssignmentsStudentEbookAssignmentIdActivityId200>(
    assignmentId: string,
    activityId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAssignmentsStudentEbookAssignmentIdActivityId<TData = GetAssignmentsStudentEbookAssignmentIdActivityId200>(
    assignmentId: string,
    activityId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAssignmentsStudentEbookAssignmentIdActivityId<TData = GetAssignmentsStudentEbookAssignmentIdActivityId200>(
    assignmentId: string,
    activityId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAssignmentsStudentEbookAssignmentIdActivityId<TData = GetAssignmentsStudentEbookAssignmentIdActivityId200>(
    assignmentId: string,
    activityId: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/assignments/student/ebook/${assignmentId}/${activityId}`,options
    );
  }
/**
 * Update a task of an ebook assignment
 * @summary Update ebook assignment
 */
 patchAssignmentsStudentEbookAssignmentIdActivityId<TData = void>(
    assignmentId: string,
    activityId: string,
    patchAssignmentsStudentEbookAssignmentIdActivityIdBody: PatchAssignmentsStudentEbookAssignmentIdActivityIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchAssignmentsStudentEbookAssignmentIdActivityId<TData = void>(
    assignmentId: string,
    activityId: string,
    patchAssignmentsStudentEbookAssignmentIdActivityIdBody: PatchAssignmentsStudentEbookAssignmentIdActivityIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchAssignmentsStudentEbookAssignmentIdActivityId<TData = void>(
    assignmentId: string,
    activityId: string,
    patchAssignmentsStudentEbookAssignmentIdActivityIdBody: PatchAssignmentsStudentEbookAssignmentIdActivityIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchAssignmentsStudentEbookAssignmentIdActivityId<TData = void>(
    assignmentId: string,
    activityId: string,
    patchAssignmentsStudentEbookAssignmentIdActivityIdBody: PatchAssignmentsStudentEbookAssignmentIdActivityIdBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/assignments/student/ebook/${assignmentId}/${activityId}`,
      patchAssignmentsStudentEbookAssignmentIdActivityIdBody,options
    );
  }
};

export type GetAssignmentsStudentClientResult = NonNullable<GetAssignmentsStudent200>
export type PostAssignmentsStudentClientResult = NonNullable<PostAssignmentsStudent201>
export type GetAssignmentsStudentIdClientResult = NonNullable<GetAssignmentsStudentId200>
export type PutAssignmentsStudentIdClientResult = NonNullable<PutAssignmentsStudentId200>
export type PatchAssignmentsStudentDraftIdClientResult = NonNullable<PatchAssignmentsStudentDraftId200>
export type PatchAssignmentsStudentUndraftIdClientResult = NonNullable<PatchAssignmentsStudentUndraftId200>
export type PatchAssignmentsStudentDeleteForMeIdClientResult = NonNullable<PatchAssignmentsStudentDeleteForMeId200>
export type DeleteAssignmentsStudentDeleteForMeIdClientResult = NonNullable<DeleteAssignmentsStudentDeleteForMeId200>
export type PatchAssignmentsStudentRestoreForMeIdClientResult = NonNullable<PatchAssignmentsStudentRestoreForMeId200>
export type PatchAssignmentsStudentDeleteForEveryoneIdClientResult = NonNullable<PatchAssignmentsStudentDeleteForEveryoneId200>
export type DeleteAssignmentsStudentDeleteForEveryoneIdClientResult = NonNullable<DeleteAssignmentsStudentDeleteForEveryoneId200>
export type PatchAssignmentsStudentRestoreForEveryoneIdClientResult = NonNullable<PatchAssignmentsStudentRestoreForEveryoneId200>
export type GetAssignmentsStudentEbookAssignmentIdActivityIdClientResult = NonNullable<GetAssignmentsStudentEbookAssignmentIdActivityId200>
export type PatchAssignmentsStudentEbookAssignmentIdActivityIdClientResult = NonNullable<void>
