/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  GetAssignmentsStudents200,
  GetAssignmentsStudentsId200,
  GetAssignmentsStudentsParams
} from '.././schemas';



type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class AssignmentsForStudentsService {
  constructor(
    private http: HttpClient,
  ) {}/**
 * Retrieve a list of all assignments assigned to students with optional filtering.
 * @summary Get all student assignments
 */
 getAssignmentsStudents<TData = GetAssignmentsStudents200>(
    params: GetAssignmentsStudentsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAssignmentsStudents<TData = GetAssignmentsStudents200>(
    params: GetAssignmentsStudentsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAssignmentsStudents<TData = GetAssignmentsStudents200>(
    params: GetAssignmentsStudentsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAssignmentsStudents<TData = GetAssignmentsStudents200>(
    params: GetAssignmentsStudentsParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/assignments/students`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Retrieve details of a specific student assignment by its ID.
 * @summary Get student assignment by ID
 */
 getAssignmentsStudentsId<TData = GetAssignmentsStudentsId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAssignmentsStudentsId<TData = GetAssignmentsStudentsId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAssignmentsStudentsId<TData = GetAssignmentsStudentsId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAssignmentsStudentsId<TData = GetAssignmentsStudentsId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/assignments/students/${id}`,options
    );
  }
};

export type GetAssignmentsStudentsClientResult = NonNullable<GetAssignmentsStudents200>
export type GetAssignmentsStudentsIdClientResult = NonNullable<GetAssignmentsStudentsId200>
