/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  Absence,
  DeleteAbsencesId200,
  GetAbsences200,
  GetAbsencesId200,
  GetAbsencesReport200,
  GetAbsencesReportParams,
  PostAbsences201,
  PostAbsencesIdNotify200,
  PutAbsencesId200,
  PutAbsencesIdBody
} from '.././schemas';



type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class AbsencesService {
  constructor(
    private http: HttpClient,
  ) {}/**
 * @summary Get all absences
 */
 getAbsences<TData = GetAbsences200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAbsences<TData = GetAbsences200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAbsences<TData = GetAbsences200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAbsences<TData = GetAbsences200>(
     options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/absences`,options
    );
  }
/**
 * @summary Create a new absence
 */
 postAbsences<TData = PostAbsences201>(
    absence: Absence, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postAbsences<TData = PostAbsences201>(
    absence: Absence, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postAbsences<TData = PostAbsences201>(
    absence: Absence, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postAbsences<TData = PostAbsences201>(
    absence: Absence, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/absences`,
      absence,options
    );
  }
/**
 * @summary Get single absence
 */
 getAbsencesId<TData = GetAbsencesId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAbsencesId<TData = GetAbsencesId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAbsencesId<TData = GetAbsencesId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAbsencesId<TData = GetAbsencesId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/absences/${id}`,options
    );
  }
/**
 * @summary Update absence
 */
 putAbsencesId<TData = PutAbsencesId200>(
    id: string,
    putAbsencesIdBody: PutAbsencesIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    putAbsencesId<TData = PutAbsencesId200>(
    id: string,
    putAbsencesIdBody: PutAbsencesIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    putAbsencesId<TData = PutAbsencesId200>(
    id: string,
    putAbsencesIdBody: PutAbsencesIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;putAbsencesId<TData = PutAbsencesId200>(
    id: string,
    putAbsencesIdBody: PutAbsencesIdBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.put<TData>(
      `http://localhost:3193/v1/absences/${id}`,
      putAbsencesIdBody,options
    );
  }
/**
 * @summary Delete absence
 */
 deleteAbsencesId<TData = DeleteAbsencesId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    deleteAbsencesId<TData = DeleteAbsencesId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    deleteAbsencesId<TData = DeleteAbsencesId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;deleteAbsencesId<TData = DeleteAbsencesId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.delete<TData>(
      `http://localhost:3193/v1/absences/${id}`,options
    );
  }
/**
 * @summary Get absence report
 */
 getAbsencesReport<TData = GetAbsencesReport200>(
    params?: GetAbsencesReportParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAbsencesReport<TData = GetAbsencesReport200>(
    params?: GetAbsencesReportParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAbsencesReport<TData = GetAbsencesReport200>(
    params?: GetAbsencesReportParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAbsencesReport<TData = GetAbsencesReport200>(
    params?: GetAbsencesReportParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/absences/report`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary Notify parent about absence
 */
 postAbsencesIdNotify<TData = PostAbsencesIdNotify200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postAbsencesIdNotify<TData = PostAbsencesIdNotify200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postAbsencesIdNotify<TData = PostAbsencesIdNotify200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postAbsencesIdNotify<TData = PostAbsencesIdNotify200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/absences/${id}/notify`,undefined,options
    );
  }
};

export type GetAbsencesClientResult = NonNullable<GetAbsences200>
export type PostAbsencesClientResult = NonNullable<PostAbsences201>
export type GetAbsencesIdClientResult = NonNullable<GetAbsencesId200>
export type PutAbsencesIdClientResult = NonNullable<PutAbsencesId200>
export type DeleteAbsencesIdClientResult = NonNullable<DeleteAbsencesId200>
export type GetAbsencesReportClientResult = NonNullable<GetAbsencesReport200>
export type PostAbsencesIdNotifyClientResult = NonNullable<PostAbsencesIdNotify200>
