/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  GetAcademicSubperiodsParams,
  PostAcademicSubperiodsBody,
  PutAcademicSubperiodsIdBody
} from '.././schemas';



type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class AcademicSubperiodsService {
  constructor(
    private http: HttpClient,
  ) {}/**
 * Retrieve a list of all academic subperiods
 * @summary Get all academic subperiods
 */
 getAcademicSubperiods<TData = void>(
    params?: GetAcademicSubperiodsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAcademicSubperiods<TData = void>(
    params?: GetAcademicSubperiodsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAcademicSubperiods<TData = void>(
    params?: GetAcademicSubperiodsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAcademicSubperiods<TData = void>(
    params?: GetAcademicSubperiodsParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/academic-subperiods`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Create a new academic subperiod with the given details
 * @summary Create a new academic subperiod
 */
 postAcademicSubperiods<TData = void>(
    postAcademicSubperiodsBody: PostAcademicSubperiodsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postAcademicSubperiods<TData = void>(
    postAcademicSubperiodsBody: PostAcademicSubperiodsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postAcademicSubperiods<TData = void>(
    postAcademicSubperiodsBody: PostAcademicSubperiodsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postAcademicSubperiods<TData = void>(
    postAcademicSubperiodsBody: PostAcademicSubperiodsBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/academic-subperiods`,
      postAcademicSubperiodsBody,options
    );
  }
/**
 * Retrieve details of a specific academic subperiod by ID
 * @summary Get academic subperiod by ID
 */
 getAcademicSubperiodsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAcademicSubperiodsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAcademicSubperiodsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAcademicSubperiodsId<TData = void>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/academic-subperiods/${id}`,options
    );
  }
/**
 * Update details of a specific academic subperiod
 * @summary Update academic subperiod
 */
 putAcademicSubperiodsId<TData = void>(
    id: string,
    putAcademicSubperiodsIdBody: PutAcademicSubperiodsIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    putAcademicSubperiodsId<TData = void>(
    id: string,
    putAcademicSubperiodsIdBody: PutAcademicSubperiodsIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    putAcademicSubperiodsId<TData = void>(
    id: string,
    putAcademicSubperiodsIdBody: PutAcademicSubperiodsIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;putAcademicSubperiodsId<TData = void>(
    id: string,
    putAcademicSubperiodsIdBody: PutAcademicSubperiodsIdBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.put<TData>(
      `http://localhost:3193/v1/academic-subperiods/${id}`,
      putAcademicSubperiodsIdBody,options
    );
  }
/**
 * Delete a specific academic subperiod
 * @summary Delete academic subperiod
 */
 deleteAcademicSubperiodsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    deleteAcademicSubperiodsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    deleteAcademicSubperiodsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;deleteAcademicSubperiodsId<TData = void>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.delete<TData>(
      `http://localhost:3193/v1/academic-subperiods/${id}`,options
    );
  }
/**
 * Retrieve the current academic subperiod
 * @summary Get current academic subperiod
 */
 getAcademicSubperiodsCurrent<TData = void>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAcademicSubperiodsCurrent<TData = void>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAcademicSubperiodsCurrent<TData = void>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAcademicSubperiodsCurrent<TData = void>(
     options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/academic-subperiods/current`,options
    );
  }
};

export type GetAcademicSubperiodsClientResult = NonNullable<void>
export type PostAcademicSubperiodsClientResult = NonNullable<void>
export type GetAcademicSubperiodsIdClientResult = NonNullable<void>
export type PutAcademicSubperiodsIdClientResult = NonNullable<void>
export type DeleteAcademicSubperiodsIdClientResult = NonNullable<void>
export type GetAcademicSubperiodsCurrentClientResult = NonNullable<void>
