/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  GetActivity200,
  GetActivityDashboard200,
  GetActivityDashboardParams,
  GetActivityEntityEntityId200,
  GetActivityEntityEntityIdEntityType200,
  GetActivityId200,
  GetActivityParams,
  GetActivityRecent200,
  GetActivityRecentParams,
  GetActivityUserUserId200,
  GetActivityUserUserIdParams,
  PostActivity201,
  PostActivityBody
} from '.././schemas';



type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class ActivityService {
  constructor(
    private http: HttpClient,
  ) {}/**
 * Retrieve a list of all activity records with optional filtering
 * @summary Get all activities
 */
 getActivity<TData = GetActivity200>(
    params?: GetActivityParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getActivity<TData = GetActivity200>(
    params?: GetActivityParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getActivity<TData = GetActivity200>(
    params?: GetActivityParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getActivity<TData = GetActivity200>(
    params?: GetActivityParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/activity`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Create a new activity record with the given details
 * @summary Create a new activity record
 */
 postActivity<TData = PostActivity201>(
    postActivityBody: PostActivityBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postActivity<TData = PostActivity201>(
    postActivityBody: PostActivityBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postActivity<TData = PostActivity201>(
    postActivityBody: PostActivityBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postActivity<TData = PostActivity201>(
    postActivityBody: PostActivityBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/activity`,
      postActivityBody,options
    );
  }
/**
 * Retrieve details of a specific activity record by ID
 * @summary Get activity by ID
 */
 getActivityId<TData = GetActivityId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getActivityId<TData = GetActivityId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getActivityId<TData = GetActivityId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getActivityId<TData = GetActivityId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/activity/${id}`,options
    );
  }
/**
 * Retrieve a list of recent activity records
 * @summary Get recent activities
 */
 getActivityRecent<TData = GetActivityRecent200>(
    params?: GetActivityRecentParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getActivityRecent<TData = GetActivityRecent200>(
    params?: GetActivityRecentParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getActivityRecent<TData = GetActivityRecent200>(
    params?: GetActivityRecentParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getActivityRecent<TData = GetActivityRecent200>(
    params?: GetActivityRecentParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/activity/recent`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Retrieve a list of activity records for the dashboard
 * @summary Get dashboard activities
 */
 getActivityDashboard<TData = GetActivityDashboard200>(
    params?: GetActivityDashboardParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getActivityDashboard<TData = GetActivityDashboard200>(
    params?: GetActivityDashboardParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getActivityDashboard<TData = GetActivityDashboard200>(
    params?: GetActivityDashboardParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getActivityDashboard<TData = GetActivityDashboard200>(
    params?: GetActivityDashboardParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/activity/dashboard`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Retrieve a list of activity records for a specific entity
 * @summary Get activities by entity ID
 */
 getActivityEntityEntityId<TData = GetActivityEntityEntityId200>(
    entityId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getActivityEntityEntityId<TData = GetActivityEntityEntityId200>(
    entityId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getActivityEntityEntityId<TData = GetActivityEntityEntityId200>(
    entityId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getActivityEntityEntityId<TData = GetActivityEntityEntityId200>(
    entityId: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/activity/entity/${entityId}`,options
    );
  }
/**
 * Retrieve a list of activity records for a specific entity and type
 * @summary Get activities by entity ID and type
 */
 getActivityEntityEntityIdEntityType<TData = GetActivityEntityEntityIdEntityType200>(
    entityId: string,
    entityType: 'user' | 'student' | 'taxi' | 'post' | 'session' | 'classroom' | 'absence', options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getActivityEntityEntityIdEntityType<TData = GetActivityEntityEntityIdEntityType200>(
    entityId: string,
    entityType: 'user' | 'student' | 'taxi' | 'post' | 'session' | 'classroom' | 'absence', options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getActivityEntityEntityIdEntityType<TData = GetActivityEntityEntityIdEntityType200>(
    entityId: string,
    entityType: 'user' | 'student' | 'taxi' | 'post' | 'session' | 'classroom' | 'absence', options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getActivityEntityEntityIdEntityType<TData = GetActivityEntityEntityIdEntityType200>(
    entityId: string,
    entityType: 'user' | 'student' | 'taxi' | 'post' | 'session' | 'classroom' | 'absence', options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/activity/entity/${entityId}/${entityType}`,options
    );
  }
/**
 * Retrieve a list of activity records performed by a specific user
 * @summary Get activities by user
 */
 getActivityUserUserId<TData = GetActivityUserUserId200>(
    userId: string,
    params?: GetActivityUserUserIdParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getActivityUserUserId<TData = GetActivityUserUserId200>(
    userId: string,
    params?: GetActivityUserUserIdParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getActivityUserUserId<TData = GetActivityUserUserId200>(
    userId: string,
    params?: GetActivityUserUserIdParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getActivityUserUserId<TData = GetActivityUserUserId200>(
    userId: string,
    params?: GetActivityUserUserIdParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/activity/user/${userId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
};

export type GetActivityClientResult = NonNullable<GetActivity200>
export type PostActivityClientResult = NonNullable<PostActivity201>
export type GetActivityIdClientResult = NonNullable<GetActivityId200>
export type GetActivityRecentClientResult = NonNullable<GetActivityRecent200>
export type GetActivityDashboardClientResult = NonNullable<GetActivityDashboard200>
export type GetActivityEntityEntityIdClientResult = NonNullable<GetActivityEntityEntityId200>
export type GetActivityEntityEntityIdEntityTypeClientResult = NonNullable<GetActivityEntityEntityIdEntityType200>
export type GetActivityUserUserIdClientResult = NonNullable<GetActivityUserUserId200>
