/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  GetClassrooms200,
  GetClassroomsId200,
  GetClassroomsParams,
  PostClassrooms201,
  PostClassroomsBody,
  PutClassroomsId200,
  PutClassroomsIdBody
} from '.././schemas';



type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class ClassroomsService {
  constructor(
    private http: HttpClient,
  ) {}/**
 * Retrieve a list of all classrooms with optional filtering
 * @summary Get all classrooms
 */
 getClassrooms<TData = GetClassrooms200>(
    params?: GetClassroomsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getClassrooms<TData = GetClassrooms200>(
    params?: GetClassroomsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getClassrooms<TData = GetClassrooms200>(
    params?: GetClassroomsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getClassrooms<TData = GetClassrooms200>(
    params?: GetClassroomsParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/classrooms`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Create a new classroom with the given details
 * @summary Create a new classroom
 */
 postClassrooms<TData = PostClassrooms201>(
    postClassroomsBody: PostClassroomsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postClassrooms<TData = PostClassrooms201>(
    postClassroomsBody: PostClassroomsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postClassrooms<TData = PostClassrooms201>(
    postClassroomsBody: PostClassroomsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postClassrooms<TData = PostClassrooms201>(
    postClassroomsBody: PostClassroomsBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/classrooms`,
      postClassroomsBody,options
    );
  }
/**
 * Retrieve details of a specific classroom by ID
 * @summary Get classroom by ID
 */
 getClassroomsId<TData = GetClassroomsId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getClassroomsId<TData = GetClassroomsId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getClassroomsId<TData = GetClassroomsId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getClassroomsId<TData = GetClassroomsId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/classrooms/${id}`,options
    );
  }
/**
 * Update details of a specific classroom
 * @summary Update classroom
 */
 putClassroomsId<TData = PutClassroomsId200>(
    id: string,
    putClassroomsIdBody: PutClassroomsIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    putClassroomsId<TData = PutClassroomsId200>(
    id: string,
    putClassroomsIdBody: PutClassroomsIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    putClassroomsId<TData = PutClassroomsId200>(
    id: string,
    putClassroomsIdBody: PutClassroomsIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;putClassroomsId<TData = PutClassroomsId200>(
    id: string,
    putClassroomsIdBody: PutClassroomsIdBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.put<TData>(
      `http://localhost:3193/v1/classrooms/${id}`,
      putClassroomsIdBody,options
    );
  }
/**
 * Delete a specific classroom
 * @summary Delete classroom
 */
 deleteClassroomsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    deleteClassroomsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    deleteClassroomsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;deleteClassroomsId<TData = void>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.delete<TData>(
      `http://localhost:3193/v1/classrooms/${id}`,options
    );
  }
};

export type GetClassroomsClientResult = NonNullable<GetClassrooms200>
export type PostClassroomsClientResult = NonNullable<PostClassrooms201>
export type GetClassroomsIdClientResult = NonNullable<GetClassroomsId200>
export type PutClassroomsIdClientResult = NonNullable<PutClassroomsId200>
export type DeleteClassroomsIdClientResult = NonNullable<void>
