/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  GetStorageFilesPrefix200,
  GetStorageGetFilePrefix200,
  GetStorageGetFilePrefixParams,
  GetStorageSize200,
  GetStorageSizeParams,
  PostStorageCreateFolder200,
  PostStorageCreateFolderParams,
  PostStorageDelete200,
  PostStorageDeleteParams,
  PostStorageUpload200,
  PostStorageUploadBody,
  PostStorageUploadParams
} from '.././schemas';



type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class StorageService {
  constructor(
    private http: HttpClient,
  ) {}/**
 * Get list of files owned by user in a specific path
 * @summary List files in a specific path
 */
 getStorageFilesPrefix<TData = GetStorageFilesPrefix200 | void>(
    prefix: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getStorageFilesPrefix<TData = GetStorageFilesPrefix200 | void>(
    prefix: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getStorageFilesPrefix<TData = GetStorageFilesPrefix200 | void>(
    prefix: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getStorageFilesPrefix<TData = GetStorageFilesPrefix200 | void>(
    prefix: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/storage/files/${prefix}`,options
    );
  }
/**
 * Get presigned url for a specific file
 * @summary Get a file in a specific path
 */
 getStorageGetFilePrefix<TData = GetStorageGetFilePrefix200 | void>(
    prefix: string,
    params?: GetStorageGetFilePrefixParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getStorageGetFilePrefix<TData = GetStorageGetFilePrefix200 | void>(
    prefix: string,
    params?: GetStorageGetFilePrefixParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getStorageGetFilePrefix<TData = GetStorageGetFilePrefix200 | void>(
    prefix: string,
    params?: GetStorageGetFilePrefixParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getStorageGetFilePrefix<TData = GetStorageGetFilePrefix200 | void>(
    prefix: string,
    params?: GetStorageGetFilePrefixParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/storage/getFile/${prefix}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Get used storage by quota in a specific path
 * @summary Get used/quota info in a specific path
 */
 getStorageSize<TData = GetStorageSize200 | void>(
    params: GetStorageSizeParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getStorageSize<TData = GetStorageSize200 | void>(
    params: GetStorageSizeParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getStorageSize<TData = GetStorageSize200 | void>(
    params: GetStorageSizeParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getStorageSize<TData = GetStorageSize200 | void>(
    params: GetStorageSizeParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/storage/size`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Upload file
 * @summary Upload file
 */
 postStorageUpload<TData = PostStorageUpload200>(
    postStorageUploadBody: PostStorageUploadBody,
    params: PostStorageUploadParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postStorageUpload<TData = PostStorageUpload200>(
    postStorageUploadBody: PostStorageUploadBody,
    params: PostStorageUploadParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postStorageUpload<TData = PostStorageUpload200>(
    postStorageUploadBody: PostStorageUploadBody,
    params: PostStorageUploadParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postStorageUpload<TData = PostStorageUpload200>(
    postStorageUploadBody: PostStorageUploadBody,
    params: PostStorageUploadParams, options?: HttpClientOptions
  ): Observable<TData>  {const formData = new FormData();
if(postStorageUploadBody.file !== undefined) {
 formData.append('file', postStorageUploadBody.file)
 }

    return this.http.post<TData>(
      `http://localhost:3193/v1/storage/upload`,
      formData,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Create folder
 * @summary Create folder
 */
 postStorageCreateFolder<TData = PostStorageCreateFolder200>(
    params: PostStorageCreateFolderParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postStorageCreateFolder<TData = PostStorageCreateFolder200>(
    params: PostStorageCreateFolderParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postStorageCreateFolder<TData = PostStorageCreateFolder200>(
    params: PostStorageCreateFolderParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postStorageCreateFolder<TData = PostStorageCreateFolder200>(
    params: PostStorageCreateFolderParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/storage/create-folder`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Delete object
 * @summary Delete object
 */
 postStorageDelete<TData = PostStorageDelete200>(
    params: PostStorageDeleteParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postStorageDelete<TData = PostStorageDelete200>(
    params: PostStorageDeleteParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postStorageDelete<TData = PostStorageDelete200>(
    params: PostStorageDeleteParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postStorageDelete<TData = PostStorageDelete200>(
    params: PostStorageDeleteParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/storage/delete`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
};

export type GetStorageFilesPrefixClientResult = NonNullable<GetStorageFilesPrefix200 | void>
export type GetStorageGetFilePrefixClientResult = NonNullable<GetStorageGetFilePrefix200 | void>
export type GetStorageSizeClientResult = NonNullable<GetStorageSize200 | void>
export type PostStorageUploadClientResult = NonNullable<PostStorageUpload200>
export type PostStorageCreateFolderClientResult = NonNullable<PostStorageCreateFolder200>
export type PostStorageDeleteClientResult = NonNullable<PostStorageDelete200>
