/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  GetUsers200,
  GetUsersChildren200,
  GetUsersChildrenParams,
  GetUsersParams,
  GetUsersSingleId200,
  GetUsersStaff200,
  GetUsersStaffId200,
  GetUsersStaffParams,
  GetUsersStudents200,
  GetUsersStudentsId200,
  GetUsersStudentsParams,
  PatchUsersArchive200,
  PatchUsersArchiveBody,
  PostUsers201,
  PostUsersBody,
  PostUsersMakePrimaryContact200,
  PostUsersMakePrimaryContactBody,
  PostUsersResendPasswordEmailId200,
  PostUsersStaff201,
  PostUsersStaffBody,
  PostUsersStudents201,
  PostUsersStudentsBody,
  PutUsersSingleId200,
  PutUsersSingleIdBody,
  PutUsersStaffId200,
  PutUsersStaffIdBody,
  PutUsersStudentsId200,
  PutUsersStudentsIdBody
} from '.././schemas';



type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class UsersService {
  constructor(
    private http: HttpClient,
  ) {}/**
 * Retrieve a list of all users with optional filtering and pagination
 * @summary Get all users
 */
 getUsers<TData = GetUsers200>(
    params?: GetUsersParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getUsers<TData = GetUsers200>(
    params?: GetUsersParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getUsers<TData = GetUsers200>(
    params?: GetUsersParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getUsers<TData = GetUsers200>(
    params?: GetUsersParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/users`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Create a new user with the given details
 * @summary Create a new user
 */
 postUsers<TData = PostUsers201>(
    postUsersBody: PostUsersBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postUsers<TData = PostUsers201>(
    postUsersBody: PostUsersBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postUsers<TData = PostUsers201>(
    postUsersBody: PostUsersBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postUsers<TData = PostUsers201>(
    postUsersBody: PostUsersBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/users`,
      postUsersBody,options
    );
  }
/**
 * Retrieve details of a specific user by ID
 * @summary Get a single user
 */
 getUsersSingleId<TData = GetUsersSingleId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getUsersSingleId<TData = GetUsersSingleId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getUsersSingleId<TData = GetUsersSingleId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getUsersSingleId<TData = GetUsersSingleId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/users/single/${id}`,options
    );
  }
/**
 * Update details of a specific user
 * @summary Update a user
 */
 putUsersSingleId<TData = PutUsersSingleId200>(
    id: string,
    putUsersSingleIdBody: PutUsersSingleIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    putUsersSingleId<TData = PutUsersSingleId200>(
    id: string,
    putUsersSingleIdBody: PutUsersSingleIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    putUsersSingleId<TData = PutUsersSingleId200>(
    id: string,
    putUsersSingleIdBody: PutUsersSingleIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;putUsersSingleId<TData = PutUsersSingleId200>(
    id: string,
    putUsersSingleIdBody: PutUsersSingleIdBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.put<TData>(
      `http://localhost:3193/v1/users/single/${id}`,
      putUsersSingleIdBody,options
    );
  }
/**
 * Archive or unarchive a user
 * @summary Archive a user
 */
 patchUsersArchive<TData = PatchUsersArchive200>(
    patchUsersArchiveBody: PatchUsersArchiveBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchUsersArchive<TData = PatchUsersArchive200>(
    patchUsersArchiveBody: PatchUsersArchiveBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchUsersArchive<TData = PatchUsersArchive200>(
    patchUsersArchiveBody: PatchUsersArchiveBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchUsersArchive<TData = PatchUsersArchive200>(
    patchUsersArchiveBody: PatchUsersArchiveBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/users/archive`,
      patchUsersArchiveBody,options
    );
  }
/**
 * Set a user as the primary contact for a customer
 * @summary Make user primary contact
 */
 postUsersMakePrimaryContact<TData = PostUsersMakePrimaryContact200>(
    postUsersMakePrimaryContactBody: PostUsersMakePrimaryContactBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postUsersMakePrimaryContact<TData = PostUsersMakePrimaryContact200>(
    postUsersMakePrimaryContactBody: PostUsersMakePrimaryContactBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postUsersMakePrimaryContact<TData = PostUsersMakePrimaryContact200>(
    postUsersMakePrimaryContactBody: PostUsersMakePrimaryContactBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postUsersMakePrimaryContact<TData = PostUsersMakePrimaryContact200>(
    postUsersMakePrimaryContactBody: PostUsersMakePrimaryContactBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/users/make-primary-contact`,
      postUsersMakePrimaryContactBody,options
    );
  }
/**
 * Resend password creation email to a user
 * @summary Resend password email
 */
 postUsersResendPasswordEmailId<TData = PostUsersResendPasswordEmailId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postUsersResendPasswordEmailId<TData = PostUsersResendPasswordEmailId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postUsersResendPasswordEmailId<TData = PostUsersResendPasswordEmailId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postUsersResendPasswordEmailId<TData = PostUsersResendPasswordEmailId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/users/resend-password-email/${id}`,undefined,options
    );
  }
/**
 * Retrieve a list of all staff members
 * @summary Get all staff members
 */
 getUsersStaff<TData = GetUsersStaff200>(
    params?: GetUsersStaffParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getUsersStaff<TData = GetUsersStaff200>(
    params?: GetUsersStaffParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getUsersStaff<TData = GetUsersStaff200>(
    params?: GetUsersStaffParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getUsersStaff<TData = GetUsersStaff200>(
    params?: GetUsersStaffParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/users/staff`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Create a new staff member with the given details
 * @summary Create a new staff member
 */
 postUsersStaff<TData = PostUsersStaff201>(
    postUsersStaffBody: PostUsersStaffBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postUsersStaff<TData = PostUsersStaff201>(
    postUsersStaffBody: PostUsersStaffBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postUsersStaff<TData = PostUsersStaff201>(
    postUsersStaffBody: PostUsersStaffBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postUsersStaff<TData = PostUsersStaff201>(
    postUsersStaffBody: PostUsersStaffBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/users/staff`,
      postUsersStaffBody,options
    );
  }
/**
 * Retrieve details of a specific staff member by ID
 * @summary Get a single staff member
 */
 getUsersStaffId<TData = GetUsersStaffId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getUsersStaffId<TData = GetUsersStaffId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getUsersStaffId<TData = GetUsersStaffId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getUsersStaffId<TData = GetUsersStaffId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/users/staff/${id}`,options
    );
  }
/**
 * Update details of a specific staff member
 * @summary Update a staff member
 */
 putUsersStaffId<TData = PutUsersStaffId200>(
    id: string,
    putUsersStaffIdBody: PutUsersStaffIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    putUsersStaffId<TData = PutUsersStaffId200>(
    id: string,
    putUsersStaffIdBody: PutUsersStaffIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    putUsersStaffId<TData = PutUsersStaffId200>(
    id: string,
    putUsersStaffIdBody: PutUsersStaffIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;putUsersStaffId<TData = PutUsersStaffId200>(
    id: string,
    putUsersStaffIdBody: PutUsersStaffIdBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.put<TData>(
      `http://localhost:3193/v1/users/staff/${id}`,
      putUsersStaffIdBody,options
    );
  }
/**
 * Delete a specific staff member
 * @summary Delete a staff member
 */
 deleteUsersStaffId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    deleteUsersStaffId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    deleteUsersStaffId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;deleteUsersStaffId<TData = void>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.delete<TData>(
      `http://localhost:3193/v1/users/staff/${id}`,options
    );
  }
/**
 * Retrieve a list of all students
 * @summary Get all students
 */
 getUsersStudents<TData = GetUsersStudents200>(
    params?: GetUsersStudentsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getUsersStudents<TData = GetUsersStudents200>(
    params?: GetUsersStudentsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getUsersStudents<TData = GetUsersStudents200>(
    params?: GetUsersStudentsParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getUsersStudents<TData = GetUsersStudents200>(
    params?: GetUsersStudentsParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/users/students`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Create a new student with the given details
 * @summary Create a new student
 */
 postUsersStudents<TData = PostUsersStudents201>(
    postUsersStudentsBody: PostUsersStudentsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postUsersStudents<TData = PostUsersStudents201>(
    postUsersStudentsBody: PostUsersStudentsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postUsersStudents<TData = PostUsersStudents201>(
    postUsersStudentsBody: PostUsersStudentsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postUsersStudents<TData = PostUsersStudents201>(
    postUsersStudentsBody: PostUsersStudentsBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/users/students`,
      postUsersStudentsBody,options
    );
  }
/**
 * Retrieve details of a specific student by ID
 * @summary Get a single student
 */
 getUsersStudentsId<TData = GetUsersStudentsId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getUsersStudentsId<TData = GetUsersStudentsId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getUsersStudentsId<TData = GetUsersStudentsId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getUsersStudentsId<TData = GetUsersStudentsId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/users/students/${id}`,options
    );
  }
/**
 * Update details of a specific student
 * @summary Update a student
 */
 putUsersStudentsId<TData = PutUsersStudentsId200>(
    id: string,
    putUsersStudentsIdBody: PutUsersStudentsIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    putUsersStudentsId<TData = PutUsersStudentsId200>(
    id: string,
    putUsersStudentsIdBody: PutUsersStudentsIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    putUsersStudentsId<TData = PutUsersStudentsId200>(
    id: string,
    putUsersStudentsIdBody: PutUsersStudentsIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;putUsersStudentsId<TData = PutUsersStudentsId200>(
    id: string,
    putUsersStudentsIdBody: PutUsersStudentsIdBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.put<TData>(
      `http://localhost:3193/v1/users/students/${id}`,
      putUsersStudentsIdBody,options
    );
  }
/**
 * Delete a specific student
 * @summary Delete a student
 */
 deleteUsersStudentsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    deleteUsersStudentsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    deleteUsersStudentsId<TData = void>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;deleteUsersStudentsId<TData = void>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.delete<TData>(
      `http://localhost:3193/v1/users/students/${id}`,options
    );
  }
/**
 * Returns students whose contacts include the authenticated user's email
 * @summary Get children for authenticated parent
 */
 getUsersChildren<TData = GetUsersChildren200>(
    params?: GetUsersChildrenParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getUsersChildren<TData = GetUsersChildren200>(
    params?: GetUsersChildrenParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getUsersChildren<TData = GetUsersChildren200>(
    params?: GetUsersChildrenParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getUsersChildren<TData = GetUsersChildren200>(
    params?: GetUsersChildrenParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/users/children`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
};

export type GetUsersClientResult = NonNullable<GetUsers200>
export type PostUsersClientResult = NonNullable<PostUsers201>
export type GetUsersSingleIdClientResult = NonNullable<GetUsersSingleId200>
export type PutUsersSingleIdClientResult = NonNullable<PutUsersSingleId200>
export type PatchUsersArchiveClientResult = NonNullable<PatchUsersArchive200>
export type PostUsersMakePrimaryContactClientResult = NonNullable<PostUsersMakePrimaryContact200>
export type PostUsersResendPasswordEmailIdClientResult = NonNullable<PostUsersResendPasswordEmailId200>
export type GetUsersStaffClientResult = NonNullable<GetUsersStaff200>
export type PostUsersStaffClientResult = NonNullable<PostUsersStaff201>
export type GetUsersStaffIdClientResult = NonNullable<GetUsersStaffId200>
export type PutUsersStaffIdClientResult = NonNullable<PutUsersStaffId200>
export type DeleteUsersStaffIdClientResult = NonNullable<void>
export type GetUsersStudentsClientResult = NonNullable<GetUsersStudents200>
export type PostUsersStudentsClientResult = NonNullable<PostUsersStudents201>
export type GetUsersStudentsIdClientResult = NonNullable<GetUsersStudentsId200>
export type PutUsersStudentsIdClientResult = NonNullable<PutUsersStudentsId200>
export type DeleteUsersStudentsIdClientResult = NonNullable<void>
export type GetUsersChildrenClientResult = NonNullable<GetUsersChildren200>
