/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  CustomActivity,
  DeleteCustomActivitiesActivityId201,
  GetCustomActivities200,
  GetCustomActivitiesActivityId200,
  GetCustomActivitiesAssignedActivities200,
  GetCustomActivitiesPublicActivitiesUserId200,
  GetCustomActivitiesStudentActivitiesUserUserId200,
  GetCustomActivitiesStudentActivityUserUserIdActivityActivityId200,
  GetCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId200,
  GetCustomActivitiesUserUserId200,
  GetCustomActivitiesUserUserIdTagTag200,
  PatchCustomActivitiesActivityId200,
  PatchCustomActivitiesActivityIdBody,
  PatchCustomActivitiesAssignedActivitiesAddStudentsActivityActivityId201,
  PatchCustomActivitiesAssignedActivitiesAddStudentsActivityActivityIdBody,
  PatchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityId200,
  PatchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityIdBody,
  PatchCustomActivitiesAssignedActivitiesUpdateStatusActivityIdStudentId201,
  PatchCustomActivitiesAssignedActivitiesUpdateStatusActivityIdStudentIdBody,
  PatchCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId200,
  PostCustomActivities201,
  PostCustomActivitiesAssignedActivitiesCreateActivityActivityId201,
  PostCustomActivitiesAssignedActivitiesCreateActivityActivityIdBody,
  PostCustomActivitiesDeleteImage200,
  PostCustomActivitiesDeleteImageBody,
  PostCustomActivitiesDuplicateActivityId201,
  PostCustomActivitiesDuplicatePublicActivityIdUserUserId201,
  PostCustomActivitiesFindOnPexels200,
  PostCustomActivitiesFindOnPexelsBody,
  PostCustomActivitiesGenerateFromAI200,
  PostCustomActivitiesGenerateFromAIBody,
  PostCustomActivitiesSaveImage201,
  PostCustomActivitiesSaveImageBody,
  PostCustomActivitiesUploadFromURL201,
  PostCustomActivitiesUploadFromURLBody,
  PutCustomActivitiesActivityId201
} from '.././schemas';



type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class CustomActivitiesService {
  constructor(
    private http: HttpClient,
  ) {}/**
 * Retrieve a list of all custom activities
 * @summary Get all custom activities
 */
 getCustomActivities<TData = GetCustomActivities200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getCustomActivities<TData = GetCustomActivities200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getCustomActivities<TData = GetCustomActivities200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getCustomActivities<TData = GetCustomActivities200>(
     options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/custom-activities`,options
    );
  }
/**
 * Create a new custom activity with the given details
 * @summary Create a new custom activity
 */
 postCustomActivities<TData = PostCustomActivities201>(
    customActivity: CustomActivity, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postCustomActivities<TData = PostCustomActivities201>(
    customActivity: CustomActivity, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postCustomActivities<TData = PostCustomActivities201>(
    customActivity: CustomActivity, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postCustomActivities<TData = PostCustomActivities201>(
    customActivity: CustomActivity, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/custom-activities`,
      customActivity,options
    );
  }
/**
 * Uploads an image from a custom activity
 * @summary Save an image from a custom activity
 */
 postCustomActivitiesSaveImage<TData = PostCustomActivitiesSaveImage201>(
    postCustomActivitiesSaveImageBody: PostCustomActivitiesSaveImageBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postCustomActivitiesSaveImage<TData = PostCustomActivitiesSaveImage201>(
    postCustomActivitiesSaveImageBody: PostCustomActivitiesSaveImageBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postCustomActivitiesSaveImage<TData = PostCustomActivitiesSaveImage201>(
    postCustomActivitiesSaveImageBody: PostCustomActivitiesSaveImageBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postCustomActivitiesSaveImage<TData = PostCustomActivitiesSaveImage201>(
    postCustomActivitiesSaveImageBody: PostCustomActivitiesSaveImageBody, options?: HttpClientOptions
  ): Observable<TData>  {const formData = new FormData();
if(postCustomActivitiesSaveImageBody.media !== undefined) {
 formData.append('media', postCustomActivitiesSaveImageBody.media)
 }

    return this.http.post<TData>(
      `http://localhost:3193/v1/custom-activities/saveImage`,
      formData,options
    );
  }
/**
 * Deletes a file given its full public URL
 * @summary Delete an image from a custom activity
 */
 postCustomActivitiesDeleteImage<TData = PostCustomActivitiesDeleteImage200>(
    postCustomActivitiesDeleteImageBody: PostCustomActivitiesDeleteImageBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postCustomActivitiesDeleteImage<TData = PostCustomActivitiesDeleteImage200>(
    postCustomActivitiesDeleteImageBody: PostCustomActivitiesDeleteImageBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postCustomActivitiesDeleteImage<TData = PostCustomActivitiesDeleteImage200>(
    postCustomActivitiesDeleteImageBody: PostCustomActivitiesDeleteImageBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postCustomActivitiesDeleteImage<TData = PostCustomActivitiesDeleteImage200>(
    postCustomActivitiesDeleteImageBody: PostCustomActivitiesDeleteImageBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/custom-activities/deleteImage`,
      postCustomActivitiesDeleteImageBody,options
    );
  }
/**
 * Uploads an image from a custom activity
 * @summary Save an image from a custom activity
 */
 postCustomActivitiesUploadFromURL<TData = PostCustomActivitiesUploadFromURL201>(
    postCustomActivitiesUploadFromURLBody: PostCustomActivitiesUploadFromURLBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postCustomActivitiesUploadFromURL<TData = PostCustomActivitiesUploadFromURL201>(
    postCustomActivitiesUploadFromURLBody: PostCustomActivitiesUploadFromURLBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postCustomActivitiesUploadFromURL<TData = PostCustomActivitiesUploadFromURL201>(
    postCustomActivitiesUploadFromURLBody: PostCustomActivitiesUploadFromURLBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postCustomActivitiesUploadFromURL<TData = PostCustomActivitiesUploadFromURL201>(
    postCustomActivitiesUploadFromURLBody: PostCustomActivitiesUploadFromURLBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/custom-activities/uploadFromURL`,
      postCustomActivitiesUploadFromURLBody,options
    );
  }
/**
 * Generates an image using AI (DALL-E) from a provided prompt.
 * @summary Generate an image from AI based on a prompt
 */
 postCustomActivitiesGenerateFromAI<TData = PostCustomActivitiesGenerateFromAI200>(
    postCustomActivitiesGenerateFromAIBody: PostCustomActivitiesGenerateFromAIBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postCustomActivitiesGenerateFromAI<TData = PostCustomActivitiesGenerateFromAI200>(
    postCustomActivitiesGenerateFromAIBody: PostCustomActivitiesGenerateFromAIBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postCustomActivitiesGenerateFromAI<TData = PostCustomActivitiesGenerateFromAI200>(
    postCustomActivitiesGenerateFromAIBody: PostCustomActivitiesGenerateFromAIBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postCustomActivitiesGenerateFromAI<TData = PostCustomActivitiesGenerateFromAI200>(
    postCustomActivitiesGenerateFromAIBody: PostCustomActivitiesGenerateFromAIBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/custom-activities/generateFromAI`,
      postCustomActivitiesGenerateFromAIBody,options
    );
  }
/**
 * Find an image on pexels from a provided prompt.
 * @summary Find an image on pexels based on a prompt
 */
 postCustomActivitiesFindOnPexels<TData = PostCustomActivitiesFindOnPexels200>(
    postCustomActivitiesFindOnPexelsBody: PostCustomActivitiesFindOnPexelsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postCustomActivitiesFindOnPexels<TData = PostCustomActivitiesFindOnPexels200>(
    postCustomActivitiesFindOnPexelsBody: PostCustomActivitiesFindOnPexelsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postCustomActivitiesFindOnPexels<TData = PostCustomActivitiesFindOnPexels200>(
    postCustomActivitiesFindOnPexelsBody: PostCustomActivitiesFindOnPexelsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postCustomActivitiesFindOnPexels<TData = PostCustomActivitiesFindOnPexels200>(
    postCustomActivitiesFindOnPexelsBody: PostCustomActivitiesFindOnPexelsBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/custom-activities/findOnPexels`,
      postCustomActivitiesFindOnPexelsBody,options
    );
  }
/**
 * Retrieve a list of all custom activities
 * @summary Get custom activities by id
 */
 getCustomActivitiesActivityId<TData = GetCustomActivitiesActivityId200>(
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getCustomActivitiesActivityId<TData = GetCustomActivitiesActivityId200>(
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getCustomActivitiesActivityId<TData = GetCustomActivitiesActivityId200>(
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getCustomActivitiesActivityId<TData = GetCustomActivitiesActivityId200>(
    activityId?: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/custom-activities/${activityId}`,options
    );
  }
/**
 * Update a custom activity with the given details
 * @summary Update a custom activity
 */
 putCustomActivitiesActivityId<TData = PutCustomActivitiesActivityId201>(
    customActivity: CustomActivity,
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    putCustomActivitiesActivityId<TData = PutCustomActivitiesActivityId201>(
    customActivity: CustomActivity,
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    putCustomActivitiesActivityId<TData = PutCustomActivitiesActivityId201>(
    customActivity: CustomActivity,
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;putCustomActivitiesActivityId<TData = PutCustomActivitiesActivityId201>(
    customActivity: CustomActivity,
    activityId?: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.put<TData>(
      `http://localhost:3193/v1/custom-activities/${activityId}`,
      customActivity,options
    );
  }
/**
 * Update a custom activity plays with the given details
 * @summary Update a custom activity plays
 */
 patchCustomActivitiesActivityId<TData = PatchCustomActivitiesActivityId200>(
    patchCustomActivitiesActivityIdBody: PatchCustomActivitiesActivityIdBody,
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchCustomActivitiesActivityId<TData = PatchCustomActivitiesActivityId200>(
    patchCustomActivitiesActivityIdBody: PatchCustomActivitiesActivityIdBody,
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchCustomActivitiesActivityId<TData = PatchCustomActivitiesActivityId200>(
    patchCustomActivitiesActivityIdBody: PatchCustomActivitiesActivityIdBody,
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchCustomActivitiesActivityId<TData = PatchCustomActivitiesActivityId200>(
    patchCustomActivitiesActivityIdBody: PatchCustomActivitiesActivityIdBody,
    activityId?: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/custom-activities/${activityId}`,
      patchCustomActivitiesActivityIdBody,options
    );
  }
/**
 * Delete a custom activity with the given details
 * @summary Delete a custom activity
 */
 deleteCustomActivitiesActivityId<TData = DeleteCustomActivitiesActivityId201>(
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    deleteCustomActivitiesActivityId<TData = DeleteCustomActivitiesActivityId201>(
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    deleteCustomActivitiesActivityId<TData = DeleteCustomActivitiesActivityId201>(
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;deleteCustomActivitiesActivityId<TData = DeleteCustomActivitiesActivityId201>(
    activityId?: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.delete<TData>(
      `http://localhost:3193/v1/custom-activities/${activityId}`,options
    );
  }
/**
 * Retrieve a list of all custom activities by user id
 * @summary Get custom activities by user id
 */
 getCustomActivitiesUserUserId<TData = GetCustomActivitiesUserUserId200>(
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getCustomActivitiesUserUserId<TData = GetCustomActivitiesUserUserId200>(
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getCustomActivitiesUserUserId<TData = GetCustomActivitiesUserUserId200>(
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getCustomActivitiesUserUserId<TData = GetCustomActivitiesUserUserId200>(
    userId?: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/custom-activities/user/${userId}`,options
    );
  }
/**
 * Retrieve a list of all single player custom activities by user id and cefr
 * @summary Get custom activities by user id and cefr
 */
 getCustomActivitiesUserUserIdTagTag<TData = GetCustomActivitiesUserUserIdTagTag200>(
    userId?: string,
    tag?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getCustomActivitiesUserUserIdTagTag<TData = GetCustomActivitiesUserUserIdTagTag200>(
    userId?: string,
    tag?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getCustomActivitiesUserUserIdTagTag<TData = GetCustomActivitiesUserUserIdTagTag200>(
    userId?: string,
    tag?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getCustomActivitiesUserUserIdTagTag<TData = GetCustomActivitiesUserUserIdTagTag200>(
    userId?: string,
    tag?: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/custom-activities/user/${userId}/tag/${tag}`,options
    );
  }
/**
 * Retrieve a list of public custom activities excluding the userId's
 * @summary Get all public custom activities
 */
 getCustomActivitiesPublicActivitiesUserId<TData = GetCustomActivitiesPublicActivitiesUserId200>(
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getCustomActivitiesPublicActivitiesUserId<TData = GetCustomActivitiesPublicActivitiesUserId200>(
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getCustomActivitiesPublicActivitiesUserId<TData = GetCustomActivitiesPublicActivitiesUserId200>(
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getCustomActivitiesPublicActivitiesUserId<TData = GetCustomActivitiesPublicActivitiesUserId200>(
    userId?: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/custom-activities/public-activities/${userId}`,options
    );
  }
/**
 * Duplicate a custom activity by the activity id and branch id
 * @summary Duplicate a custom activity
 */
 postCustomActivitiesDuplicateActivityId<TData = PostCustomActivitiesDuplicateActivityId201>(
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postCustomActivitiesDuplicateActivityId<TData = PostCustomActivitiesDuplicateActivityId201>(
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postCustomActivitiesDuplicateActivityId<TData = PostCustomActivitiesDuplicateActivityId201>(
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postCustomActivitiesDuplicateActivityId<TData = PostCustomActivitiesDuplicateActivityId201>(
    activityId?: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/custom-activities/duplicate/${activityId}`,undefined,options
    );
  }
/**
 * Duplicate a public custom activity by the activity id and the user id
 * @summary Duplicate a public custom activity
 */
 postCustomActivitiesDuplicatePublicActivityIdUserUserId<TData = PostCustomActivitiesDuplicatePublicActivityIdUserUserId201>(
    activityId?: string,
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postCustomActivitiesDuplicatePublicActivityIdUserUserId<TData = PostCustomActivitiesDuplicatePublicActivityIdUserUserId201>(
    activityId?: string,
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postCustomActivitiesDuplicatePublicActivityIdUserUserId<TData = PostCustomActivitiesDuplicatePublicActivityIdUserUserId201>(
    activityId?: string,
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postCustomActivitiesDuplicatePublicActivityIdUserUserId<TData = PostCustomActivitiesDuplicatePublicActivityIdUserUserId201>(
    activityId?: string,
    userId?: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/custom-activities/duplicate-public/${activityId}/user/${userId}`,undefined,options
    );
  }
/**
 * Retrieve a list of students custom activities
 * @summary Get student's custom activities by id
 */
 getCustomActivitiesStudentActivitiesUserUserId<TData = GetCustomActivitiesStudentActivitiesUserUserId200>(
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getCustomActivitiesStudentActivitiesUserUserId<TData = GetCustomActivitiesStudentActivitiesUserUserId200>(
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getCustomActivitiesStudentActivitiesUserUserId<TData = GetCustomActivitiesStudentActivitiesUserUserId200>(
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getCustomActivitiesStudentActivitiesUserUserId<TData = GetCustomActivitiesStudentActivitiesUserUserId200>(
    userId?: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/custom-activities/student-activities/user/${userId}`,options
    );
  }
/**
 * Retrieve a students custom activity
 * @summary Get student's custom activitiy by userId and activityId
 */
 getCustomActivitiesStudentActivityUserUserIdActivityActivityId<TData = GetCustomActivitiesStudentActivityUserUserIdActivityActivityId200>(
    userId?: string,
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getCustomActivitiesStudentActivityUserUserIdActivityActivityId<TData = GetCustomActivitiesStudentActivityUserUserIdActivityActivityId200>(
    userId?: string,
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getCustomActivitiesStudentActivityUserUserIdActivityActivityId<TData = GetCustomActivitiesStudentActivityUserUserIdActivityActivityId200>(
    userId?: string,
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getCustomActivitiesStudentActivityUserUserIdActivityActivityId<TData = GetCustomActivitiesStudentActivityUserUserIdActivityActivityId200>(
    userId?: string,
    activityId?: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/custom-activities/student-activity/user/${userId}/activity/${activityId}`,options
    );
  }
/**
 * Retrieve all the assigned activities
 * @summary Get assigned custom activitiies
 */
 getCustomActivitiesAssignedActivities<TData = GetCustomActivitiesAssignedActivities200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getCustomActivitiesAssignedActivities<TData = GetCustomActivitiesAssignedActivities200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getCustomActivitiesAssignedActivities<TData = GetCustomActivitiesAssignedActivities200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getCustomActivitiesAssignedActivities<TData = GetCustomActivitiesAssignedActivities200>(
     options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/custom-activities/assigned-activities`,options
    );
  }
/**
 * Duplicates a custom activity into an assigned custom activity by pass a list of students to assign at creation.
 * @summary Create an assigned activity from a custom activity
 */
 postCustomActivitiesAssignedActivitiesCreateActivityActivityId<TData = PostCustomActivitiesAssignedActivitiesCreateActivityActivityId201>(
    activityId: string,
    postCustomActivitiesAssignedActivitiesCreateActivityActivityIdBody: PostCustomActivitiesAssignedActivitiesCreateActivityActivityIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postCustomActivitiesAssignedActivitiesCreateActivityActivityId<TData = PostCustomActivitiesAssignedActivitiesCreateActivityActivityId201>(
    activityId: string,
    postCustomActivitiesAssignedActivitiesCreateActivityActivityIdBody: PostCustomActivitiesAssignedActivitiesCreateActivityActivityIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postCustomActivitiesAssignedActivitiesCreateActivityActivityId<TData = PostCustomActivitiesAssignedActivitiesCreateActivityActivityId201>(
    activityId: string,
    postCustomActivitiesAssignedActivitiesCreateActivityActivityIdBody: PostCustomActivitiesAssignedActivitiesCreateActivityActivityIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postCustomActivitiesAssignedActivitiesCreateActivityActivityId<TData = PostCustomActivitiesAssignedActivitiesCreateActivityActivityId201>(
    activityId: string,
    postCustomActivitiesAssignedActivitiesCreateActivityActivityIdBody: PostCustomActivitiesAssignedActivitiesCreateActivityActivityIdBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/custom-activities/assigned-activities/create/activity/${activityId}`,
      postCustomActivitiesAssignedActivitiesCreateActivityActivityIdBody,options
    );
  }
/**
 * Update the `completed` status of a specific student in an assigned custom activity.
 * @summary Update a student's activity status
 */
 patchCustomActivitiesAssignedActivitiesUpdateStatusActivityIdStudentId<TData = PatchCustomActivitiesAssignedActivitiesUpdateStatusActivityIdStudentId201>(
    activityId: string,
    studentId: string,
    patchCustomActivitiesAssignedActivitiesUpdateStatusActivityIdStudentIdBody: PatchCustomActivitiesAssignedActivitiesUpdateStatusActivityIdStudentIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchCustomActivitiesAssignedActivitiesUpdateStatusActivityIdStudentId<TData = PatchCustomActivitiesAssignedActivitiesUpdateStatusActivityIdStudentId201>(
    activityId: string,
    studentId: string,
    patchCustomActivitiesAssignedActivitiesUpdateStatusActivityIdStudentIdBody: PatchCustomActivitiesAssignedActivitiesUpdateStatusActivityIdStudentIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchCustomActivitiesAssignedActivitiesUpdateStatusActivityIdStudentId<TData = PatchCustomActivitiesAssignedActivitiesUpdateStatusActivityIdStudentId201>(
    activityId: string,
    studentId: string,
    patchCustomActivitiesAssignedActivitiesUpdateStatusActivityIdStudentIdBody: PatchCustomActivitiesAssignedActivitiesUpdateStatusActivityIdStudentIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchCustomActivitiesAssignedActivitiesUpdateStatusActivityIdStudentId<TData = PatchCustomActivitiesAssignedActivitiesUpdateStatusActivityIdStudentId201>(
    activityId: string,
    studentId: string,
    patchCustomActivitiesAssignedActivitiesUpdateStatusActivityIdStudentIdBody: PatchCustomActivitiesAssignedActivitiesUpdateStatusActivityIdStudentIdBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/custom-activities/assigned-activities/update-status/${activityId}/${studentId}`,
      patchCustomActivitiesAssignedActivitiesUpdateStatusActivityIdStudentIdBody,options
    );
  }
/**
 * Update an assigned activity by adding students
 * @summary Update an assigned activity
 */
 patchCustomActivitiesAssignedActivitiesAddStudentsActivityActivityId<TData = PatchCustomActivitiesAssignedActivitiesAddStudentsActivityActivityId201>(
    patchCustomActivitiesAssignedActivitiesAddStudentsActivityActivityIdBody: PatchCustomActivitiesAssignedActivitiesAddStudentsActivityActivityIdBody,
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchCustomActivitiesAssignedActivitiesAddStudentsActivityActivityId<TData = PatchCustomActivitiesAssignedActivitiesAddStudentsActivityActivityId201>(
    patchCustomActivitiesAssignedActivitiesAddStudentsActivityActivityIdBody: PatchCustomActivitiesAssignedActivitiesAddStudentsActivityActivityIdBody,
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchCustomActivitiesAssignedActivitiesAddStudentsActivityActivityId<TData = PatchCustomActivitiesAssignedActivitiesAddStudentsActivityActivityId201>(
    patchCustomActivitiesAssignedActivitiesAddStudentsActivityActivityIdBody: PatchCustomActivitiesAssignedActivitiesAddStudentsActivityActivityIdBody,
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchCustomActivitiesAssignedActivitiesAddStudentsActivityActivityId<TData = PatchCustomActivitiesAssignedActivitiesAddStudentsActivityActivityId201>(
    patchCustomActivitiesAssignedActivitiesAddStudentsActivityActivityIdBody: PatchCustomActivitiesAssignedActivitiesAddStudentsActivityActivityIdBody,
    activityId?: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/custom-activities/assigned-activities-add-students/activity/${activityId}`,
      patchCustomActivitiesAssignedActivitiesAddStudentsActivityActivityIdBody,options
    );
  }
/**
 * Removes one or more students from an existing assigned custom activity.
 * @summary Remove students from an assigned activity
 */
 patchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityId<TData = PatchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityId200>(
    activityId: string,
    patchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityIdBody: PatchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityId<TData = PatchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityId200>(
    activityId: string,
    patchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityIdBody: PatchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityId<TData = PatchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityId200>(
    activityId: string,
    patchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityIdBody: PatchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityIdBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityId<TData = PatchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityId200>(
    activityId: string,
    patchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityIdBody: PatchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityIdBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/custom-activities/assigned-activities-remove-students/activity/${activityId}`,
      patchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityIdBody,options
    );
  }
/**
 * Retrieve the answers for a specific task (custom activity) assigned to a student.
 * @summary Get assigned task answers
 */
 getCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId<TData = GetCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId200>(
    assignmentId: string,
    studentId: string,
    customActivityId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId<TData = GetCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId200>(
    assignmentId: string,
    studentId: string,
    customActivityId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId<TData = GetCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId200>(
    assignmentId: string,
    studentId: string,
    customActivityId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId<TData = GetCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId200>(
    assignmentId: string,
    studentId: string,
    customActivityId: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/custom-activities/task-answers/${assignmentId}/${studentId}/${customActivityId}`,options
    );
  }
/**
 * Submit or update the answers for a specific assigned custom activity task.
 * @summary Update assigned task answers
 */
 patchCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId<TData = PatchCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId200>(
    assignmentId: string,
    studentId: string,
    customActivityId: string,
    patchCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityIdBody: unknown, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    patchCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId<TData = PatchCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId200>(
    assignmentId: string,
    studentId: string,
    customActivityId: string,
    patchCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityIdBody: unknown, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    patchCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId<TData = PatchCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId200>(
    assignmentId: string,
    studentId: string,
    customActivityId: string,
    patchCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityIdBody: unknown, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;patchCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId<TData = PatchCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId200>(
    assignmentId: string,
    studentId: string,
    customActivityId: string,
    patchCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityIdBody: unknown, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `http://localhost:3193/v1/custom-activities/task-answers/${assignmentId}/${studentId}/${customActivityId}`,
      patchCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityIdBody,options
    );
  }
};

export type GetCustomActivitiesClientResult = NonNullable<GetCustomActivities200>
export type PostCustomActivitiesClientResult = NonNullable<PostCustomActivities201>
export type PostCustomActivitiesSaveImageClientResult = NonNullable<PostCustomActivitiesSaveImage201>
export type PostCustomActivitiesDeleteImageClientResult = NonNullable<PostCustomActivitiesDeleteImage200>
export type PostCustomActivitiesUploadFromURLClientResult = NonNullable<PostCustomActivitiesUploadFromURL201>
export type PostCustomActivitiesGenerateFromAIClientResult = NonNullable<PostCustomActivitiesGenerateFromAI200>
export type PostCustomActivitiesFindOnPexelsClientResult = NonNullable<PostCustomActivitiesFindOnPexels200>
export type GetCustomActivitiesActivityIdClientResult = NonNullable<GetCustomActivitiesActivityId200>
export type PutCustomActivitiesActivityIdClientResult = NonNullable<PutCustomActivitiesActivityId201>
export type PatchCustomActivitiesActivityIdClientResult = NonNullable<PatchCustomActivitiesActivityId200>
export type DeleteCustomActivitiesActivityIdClientResult = NonNullable<DeleteCustomActivitiesActivityId201>
export type GetCustomActivitiesUserUserIdClientResult = NonNullable<GetCustomActivitiesUserUserId200>
export type GetCustomActivitiesUserUserIdTagTagClientResult = NonNullable<GetCustomActivitiesUserUserIdTagTag200>
export type GetCustomActivitiesPublicActivitiesUserIdClientResult = NonNullable<GetCustomActivitiesPublicActivitiesUserId200>
export type PostCustomActivitiesDuplicateActivityIdClientResult = NonNullable<PostCustomActivitiesDuplicateActivityId201>
export type PostCustomActivitiesDuplicatePublicActivityIdUserUserIdClientResult = NonNullable<PostCustomActivitiesDuplicatePublicActivityIdUserUserId201>
export type GetCustomActivitiesStudentActivitiesUserUserIdClientResult = NonNullable<GetCustomActivitiesStudentActivitiesUserUserId200>
export type GetCustomActivitiesStudentActivityUserUserIdActivityActivityIdClientResult = NonNullable<GetCustomActivitiesStudentActivityUserUserIdActivityActivityId200>
export type GetCustomActivitiesAssignedActivitiesClientResult = NonNullable<GetCustomActivitiesAssignedActivities200>
export type PostCustomActivitiesAssignedActivitiesCreateActivityActivityIdClientResult = NonNullable<PostCustomActivitiesAssignedActivitiesCreateActivityActivityId201>
export type PatchCustomActivitiesAssignedActivitiesUpdateStatusActivityIdStudentIdClientResult = NonNullable<PatchCustomActivitiesAssignedActivitiesUpdateStatusActivityIdStudentId201>
export type PatchCustomActivitiesAssignedActivitiesAddStudentsActivityActivityIdClientResult = NonNullable<PatchCustomActivitiesAssignedActivitiesAddStudentsActivityActivityId201>
export type PatchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityIdClientResult = NonNullable<PatchCustomActivitiesAssignedActivitiesRemoveStudentsActivityActivityId200>
export type GetCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityIdClientResult = NonNullable<GetCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId200>
export type PatchCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityIdClientResult = NonNullable<PatchCustomActivitiesTaskAnswersAssignmentIdStudentIdCustomActivityId200>
