/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Supercourse SMS API
 * API documentation for the Supercourse SMS service
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  CustomActivity,
  DeleteCustomActivitiesActivityId201,
  GetCustomActivities200,
  GetCustomActivitiesActivityId200,
  GetCustomActivitiesPublicActivitiesUserId200,
  GetCustomActivitiesStudentActivitiesUserUserId200,
  GetCustomActivitiesUserUserId200,
  PostCustomActivities201,
  PostCustomActivitiesDeleteImage200,
  PostCustomActivitiesDeleteImageBody,
  PostCustomActivitiesDuplicateActivityId201,
  PostCustomActivitiesDuplicatePublicActivityIdUserUserId201,
  PostCustomActivitiesFindOnPexels200,
  PostCustomActivitiesFindOnPexelsBody,
  PostCustomActivitiesGenerateFromAI200,
  PostCustomActivitiesGenerateFromAIBody,
  PostCustomActivitiesSaveImage201,
  PostCustomActivitiesSaveImageBody,
  PostCustomActivitiesUploadFromURL201,
  PostCustomActivitiesUploadFromURLBody,
  PutCustomActivitiesActivityId201
} from '.././schemas';



type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class CustomActivitiesService {
  constructor(
    private http: HttpClient,
  ) {}/**
 * Retrieve a list of all custom activities
 * @summary Get all custom activities
 */
 getCustomActivities<TData = GetCustomActivities200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getCustomActivities<TData = GetCustomActivities200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getCustomActivities<TData = GetCustomActivities200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getCustomActivities<TData = GetCustomActivities200>(
     options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/custom-activities`,options
    );
  }
/**
 * Create a new custom activity with the given details
 * @summary Create a new custom activity
 */
 postCustomActivities<TData = PostCustomActivities201>(
    customActivity: CustomActivity, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postCustomActivities<TData = PostCustomActivities201>(
    customActivity: CustomActivity, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postCustomActivities<TData = PostCustomActivities201>(
    customActivity: CustomActivity, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postCustomActivities<TData = PostCustomActivities201>(
    customActivity: CustomActivity, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/custom-activities`,
      customActivity,options
    );
  }
/**
 * Uploads an image from a custom activity
 * @summary Save an image from a custom activity
 */
 postCustomActivitiesSaveImage<TData = PostCustomActivitiesSaveImage201>(
    postCustomActivitiesSaveImageBody: PostCustomActivitiesSaveImageBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postCustomActivitiesSaveImage<TData = PostCustomActivitiesSaveImage201>(
    postCustomActivitiesSaveImageBody: PostCustomActivitiesSaveImageBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postCustomActivitiesSaveImage<TData = PostCustomActivitiesSaveImage201>(
    postCustomActivitiesSaveImageBody: PostCustomActivitiesSaveImageBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postCustomActivitiesSaveImage<TData = PostCustomActivitiesSaveImage201>(
    postCustomActivitiesSaveImageBody: PostCustomActivitiesSaveImageBody, options?: HttpClientOptions
  ): Observable<TData>  {const formData = new FormData();
if(postCustomActivitiesSaveImageBody.media !== undefined) {
 formData.append('media', postCustomActivitiesSaveImageBody.media)
 }

    return this.http.post<TData>(
      `http://localhost:3193/v1/custom-activities/saveImage`,
      formData,options
    );
  }
/**
 * Deletes a file given its full public URL
 * @summary Delete an image from a custom activity
 */
 postCustomActivitiesDeleteImage<TData = PostCustomActivitiesDeleteImage200>(
    postCustomActivitiesDeleteImageBody: PostCustomActivitiesDeleteImageBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postCustomActivitiesDeleteImage<TData = PostCustomActivitiesDeleteImage200>(
    postCustomActivitiesDeleteImageBody: PostCustomActivitiesDeleteImageBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postCustomActivitiesDeleteImage<TData = PostCustomActivitiesDeleteImage200>(
    postCustomActivitiesDeleteImageBody: PostCustomActivitiesDeleteImageBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postCustomActivitiesDeleteImage<TData = PostCustomActivitiesDeleteImage200>(
    postCustomActivitiesDeleteImageBody: PostCustomActivitiesDeleteImageBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/custom-activities/deleteImage`,
      postCustomActivitiesDeleteImageBody,options
    );
  }
/**
 * Uploads an image from a custom activity
 * @summary Save an image from a custom activity
 */
 postCustomActivitiesUploadFromURL<TData = PostCustomActivitiesUploadFromURL201>(
    postCustomActivitiesUploadFromURLBody: PostCustomActivitiesUploadFromURLBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postCustomActivitiesUploadFromURL<TData = PostCustomActivitiesUploadFromURL201>(
    postCustomActivitiesUploadFromURLBody: PostCustomActivitiesUploadFromURLBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postCustomActivitiesUploadFromURL<TData = PostCustomActivitiesUploadFromURL201>(
    postCustomActivitiesUploadFromURLBody: PostCustomActivitiesUploadFromURLBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postCustomActivitiesUploadFromURL<TData = PostCustomActivitiesUploadFromURL201>(
    postCustomActivitiesUploadFromURLBody: PostCustomActivitiesUploadFromURLBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/custom-activities/uploadFromURL`,
      postCustomActivitiesUploadFromURLBody,options
    );
  }
/**
 * Generates an image using AI (DALL-E) from a provided prompt.
 * @summary Generate an image from AI based on a prompt
 */
 postCustomActivitiesGenerateFromAI<TData = PostCustomActivitiesGenerateFromAI200>(
    postCustomActivitiesGenerateFromAIBody: PostCustomActivitiesGenerateFromAIBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postCustomActivitiesGenerateFromAI<TData = PostCustomActivitiesGenerateFromAI200>(
    postCustomActivitiesGenerateFromAIBody: PostCustomActivitiesGenerateFromAIBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postCustomActivitiesGenerateFromAI<TData = PostCustomActivitiesGenerateFromAI200>(
    postCustomActivitiesGenerateFromAIBody: PostCustomActivitiesGenerateFromAIBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postCustomActivitiesGenerateFromAI<TData = PostCustomActivitiesGenerateFromAI200>(
    postCustomActivitiesGenerateFromAIBody: PostCustomActivitiesGenerateFromAIBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/custom-activities/generateFromAI`,
      postCustomActivitiesGenerateFromAIBody,options
    );
  }
/**
 * Find an image on pexels from a provided prompt.
 * @summary Find an image on pexels based on a prompt
 */
 postCustomActivitiesFindOnPexels<TData = PostCustomActivitiesFindOnPexels200>(
    postCustomActivitiesFindOnPexelsBody: PostCustomActivitiesFindOnPexelsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postCustomActivitiesFindOnPexels<TData = PostCustomActivitiesFindOnPexels200>(
    postCustomActivitiesFindOnPexelsBody: PostCustomActivitiesFindOnPexelsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postCustomActivitiesFindOnPexels<TData = PostCustomActivitiesFindOnPexels200>(
    postCustomActivitiesFindOnPexelsBody: PostCustomActivitiesFindOnPexelsBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postCustomActivitiesFindOnPexels<TData = PostCustomActivitiesFindOnPexels200>(
    postCustomActivitiesFindOnPexelsBody: PostCustomActivitiesFindOnPexelsBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/custom-activities/findOnPexels`,
      postCustomActivitiesFindOnPexelsBody,options
    );
  }
/**
 * Retrieve a list of all custom activities
 * @summary Get custom activities by id
 */
 getCustomActivitiesActivityId<TData = GetCustomActivitiesActivityId200>(
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getCustomActivitiesActivityId<TData = GetCustomActivitiesActivityId200>(
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getCustomActivitiesActivityId<TData = GetCustomActivitiesActivityId200>(
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getCustomActivitiesActivityId<TData = GetCustomActivitiesActivityId200>(
    activityId?: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/custom-activities/${activityId}`,options
    );
  }
/**
 * Update a custom activity with the given details
 * @summary Update a custom activity
 */
 putCustomActivitiesActivityId<TData = PutCustomActivitiesActivityId201>(
    customActivity: CustomActivity,
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    putCustomActivitiesActivityId<TData = PutCustomActivitiesActivityId201>(
    customActivity: CustomActivity,
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    putCustomActivitiesActivityId<TData = PutCustomActivitiesActivityId201>(
    customActivity: CustomActivity,
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;putCustomActivitiesActivityId<TData = PutCustomActivitiesActivityId201>(
    customActivity: CustomActivity,
    activityId?: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.put<TData>(
      `http://localhost:3193/v1/custom-activities/${activityId}`,
      customActivity,options
    );
  }
/**
 * Delete a custom activity with the given details
 * @summary Delete a custom activity
 */
 deleteCustomActivitiesActivityId<TData = DeleteCustomActivitiesActivityId201>(
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    deleteCustomActivitiesActivityId<TData = DeleteCustomActivitiesActivityId201>(
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    deleteCustomActivitiesActivityId<TData = DeleteCustomActivitiesActivityId201>(
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;deleteCustomActivitiesActivityId<TData = DeleteCustomActivitiesActivityId201>(
    activityId?: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.delete<TData>(
      `http://localhost:3193/v1/custom-activities/${activityId}`,options
    );
  }
/**
 * Retrieve a list of all custom activities by user id
 * @summary Get custom activities by user id
 */
 getCustomActivitiesUserUserId<TData = GetCustomActivitiesUserUserId200>(
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getCustomActivitiesUserUserId<TData = GetCustomActivitiesUserUserId200>(
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getCustomActivitiesUserUserId<TData = GetCustomActivitiesUserUserId200>(
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getCustomActivitiesUserUserId<TData = GetCustomActivitiesUserUserId200>(
    userId?: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/custom-activities/user/${userId}`,options
    );
  }
/**
 * Retrieve a list of public custom activities excluding the userId's
 * @summary Get all public custom activities
 */
 getCustomActivitiesPublicActivitiesUserId<TData = GetCustomActivitiesPublicActivitiesUserId200>(
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getCustomActivitiesPublicActivitiesUserId<TData = GetCustomActivitiesPublicActivitiesUserId200>(
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getCustomActivitiesPublicActivitiesUserId<TData = GetCustomActivitiesPublicActivitiesUserId200>(
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getCustomActivitiesPublicActivitiesUserId<TData = GetCustomActivitiesPublicActivitiesUserId200>(
    userId?: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/custom-activities/public-activities/${userId}`,options
    );
  }
/**
 * Duplicate a custom activity by the activity id
 * @summary Duplicate a custom activity
 */
 postCustomActivitiesDuplicateActivityId<TData = PostCustomActivitiesDuplicateActivityId201>(
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postCustomActivitiesDuplicateActivityId<TData = PostCustomActivitiesDuplicateActivityId201>(
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postCustomActivitiesDuplicateActivityId<TData = PostCustomActivitiesDuplicateActivityId201>(
    activityId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postCustomActivitiesDuplicateActivityId<TData = PostCustomActivitiesDuplicateActivityId201>(
    activityId?: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/custom-activities/duplicate/${activityId}`,undefined,options
    );
  }
/**
 * Duplicate a public custom activity by the activity id and the user id
 * @summary Duplicate a public custom activity
 */
 postCustomActivitiesDuplicatePublicActivityIdUserUserId<TData = PostCustomActivitiesDuplicatePublicActivityIdUserUserId201>(
    activityId?: string,
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postCustomActivitiesDuplicatePublicActivityIdUserUserId<TData = PostCustomActivitiesDuplicatePublicActivityIdUserUserId201>(
    activityId?: string,
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postCustomActivitiesDuplicatePublicActivityIdUserUserId<TData = PostCustomActivitiesDuplicatePublicActivityIdUserUserId201>(
    activityId?: string,
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postCustomActivitiesDuplicatePublicActivityIdUserUserId<TData = PostCustomActivitiesDuplicatePublicActivityIdUserUserId201>(
    activityId?: string,
    userId?: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/custom-activities/duplicate-public/${activityId}/user/${userId}`,undefined,options
    );
  }
/**
 * Retrieve a list of students custom activities
 * @summary Get student's custom activities by id
 */
 getCustomActivitiesStudentActivitiesUserUserId<TData = GetCustomActivitiesStudentActivitiesUserUserId200>(
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getCustomActivitiesStudentActivitiesUserUserId<TData = GetCustomActivitiesStudentActivitiesUserUserId200>(
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getCustomActivitiesStudentActivitiesUserUserId<TData = GetCustomActivitiesStudentActivitiesUserUserId200>(
    userId?: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getCustomActivitiesStudentActivitiesUserUserId<TData = GetCustomActivitiesStudentActivitiesUserUserId200>(
    userId?: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/custom-activities/student-activities/user/${userId}`,options
    );
  }
};

export type GetCustomActivitiesClientResult = NonNullable<GetCustomActivities200>
export type PostCustomActivitiesClientResult = NonNullable<PostCustomActivities201>
export type PostCustomActivitiesSaveImageClientResult = NonNullable<PostCustomActivitiesSaveImage201>
export type PostCustomActivitiesDeleteImageClientResult = NonNullable<PostCustomActivitiesDeleteImage200>
export type PostCustomActivitiesUploadFromURLClientResult = NonNullable<PostCustomActivitiesUploadFromURL201>
export type PostCustomActivitiesGenerateFromAIClientResult = NonNullable<PostCustomActivitiesGenerateFromAI200>
export type PostCustomActivitiesFindOnPexelsClientResult = NonNullable<PostCustomActivitiesFindOnPexels200>
export type GetCustomActivitiesActivityIdClientResult = NonNullable<GetCustomActivitiesActivityId200>
export type PutCustomActivitiesActivityIdClientResult = NonNullable<PutCustomActivitiesActivityId201>
export type DeleteCustomActivitiesActivityIdClientResult = NonNullable<DeleteCustomActivitiesActivityId201>
export type GetCustomActivitiesUserUserIdClientResult = NonNullable<GetCustomActivitiesUserUserId200>
export type GetCustomActivitiesPublicActivitiesUserIdClientResult = NonNullable<GetCustomActivitiesPublicActivitiesUserId200>
export type PostCustomActivitiesDuplicateActivityIdClientResult = NonNullable<PostCustomActivitiesDuplicateActivityId201>
export type PostCustomActivitiesDuplicatePublicActivityIdUserUserIdClientResult = NonNullable<PostCustomActivitiesDuplicatePublicActivityIdUserUserId201>
export type GetCustomActivitiesStudentActivitiesUserUserIdClientResult = NonNullable<GetCustomActivitiesStudentActivitiesUserUserId200>
