/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Super Course SMS API
 * API documentation for the Super Course SMS services
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  GetAuthVerifyEmail200,
  GetAuthVerifyEmailParams,
  PostAuthForgotPassword200,
  PostAuthForgotPasswordBody,
  PostAuthImpersonateStudentId200,
  PostAuthLogin200,
  PostAuthLoginBody,
  PostAuthLogout200,
  PostAuthRefresh200,
  PostAuthRefreshBody,
  PostAuthRegister201,
  PostAuthRegisterBody,
  PostAuthResetPassword200,
  PostAuthResetPasswordBody
} from '.././schemas';



type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class AuthService {
  constructor(
    private http: HttpClient,
  ) {}/**
 * Authenticate a user with email and password to receive JWT tokens. If X-Customer-Slug header is provided, authentication occurs against the specified customer database.
 * @summary Authenticate user and return tokens
 */
 postAuthLogin<TData = PostAuthLogin200>(
    postAuthLoginBody: PostAuthLoginBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postAuthLogin<TData = PostAuthLogin200>(
    postAuthLoginBody: PostAuthLoginBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postAuthLogin<TData = PostAuthLogin200>(
    postAuthLoginBody: PostAuthLoginBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postAuthLogin<TData = PostAuthLogin200>(
    postAuthLoginBody: PostAuthLoginBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/auth/login`,
      postAuthLoginBody,options
    );
  }
/**
 * Register a new user with the provided details
 * @summary Register a new user
 */
 postAuthRegister<TData = PostAuthRegister201>(
    postAuthRegisterBody: PostAuthRegisterBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postAuthRegister<TData = PostAuthRegister201>(
    postAuthRegisterBody: PostAuthRegisterBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postAuthRegister<TData = PostAuthRegister201>(
    postAuthRegisterBody: PostAuthRegisterBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postAuthRegister<TData = PostAuthRegister201>(
    postAuthRegisterBody: PostAuthRegisterBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/auth/register`,
      postAuthRegisterBody,options
    );
  }
/**
 * Get a new access token using a refresh token
 * @summary Refresh access token
 */
 postAuthRefresh<TData = PostAuthRefresh200>(
    postAuthRefreshBody: PostAuthRefreshBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postAuthRefresh<TData = PostAuthRefresh200>(
    postAuthRefreshBody: PostAuthRefreshBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postAuthRefresh<TData = PostAuthRefresh200>(
    postAuthRefreshBody: PostAuthRefreshBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postAuthRefresh<TData = PostAuthRefresh200>(
    postAuthRefreshBody: PostAuthRefreshBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/auth/refresh`,
      postAuthRefreshBody,options
    );
  }
/**
 * Verify a user's email address using a verification token
 * @summary Verify email address
 */
 getAuthVerifyEmail<TData = GetAuthVerifyEmail200>(
    params: GetAuthVerifyEmailParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    getAuthVerifyEmail<TData = GetAuthVerifyEmail200>(
    params: GetAuthVerifyEmailParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    getAuthVerifyEmail<TData = GetAuthVerifyEmail200>(
    params: GetAuthVerifyEmailParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;getAuthVerifyEmail<TData = GetAuthVerifyEmail200>(
    params: GetAuthVerifyEmailParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `http://localhost:3193/v1/auth/verify-email`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Request a password reset email
 * @summary Request password reset
 */
 postAuthForgotPassword<TData = PostAuthForgotPassword200>(
    postAuthForgotPasswordBody: PostAuthForgotPasswordBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postAuthForgotPassword<TData = PostAuthForgotPassword200>(
    postAuthForgotPasswordBody: PostAuthForgotPasswordBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postAuthForgotPassword<TData = PostAuthForgotPassword200>(
    postAuthForgotPasswordBody: PostAuthForgotPasswordBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postAuthForgotPassword<TData = PostAuthForgotPassword200>(
    postAuthForgotPasswordBody: PostAuthForgotPasswordBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/auth/forgot-password`,
      postAuthForgotPasswordBody,options
    );
  }
/**
 * Reset password using a reset token
 * @summary Reset password
 */
 postAuthResetPassword<TData = PostAuthResetPassword200>(
    postAuthResetPasswordBody: PostAuthResetPasswordBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postAuthResetPassword<TData = PostAuthResetPassword200>(
    postAuthResetPasswordBody: PostAuthResetPasswordBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postAuthResetPassword<TData = PostAuthResetPassword200>(
    postAuthResetPasswordBody: PostAuthResetPasswordBody, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postAuthResetPassword<TData = PostAuthResetPassword200>(
    postAuthResetPasswordBody: PostAuthResetPasswordBody, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/auth/reset-password`,
      postAuthResetPasswordBody,options
    );
  }
/**
 * Logout user and invalidate tokens
 * @summary Logout user
 */
 postAuthLogout<TData = PostAuthLogout200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postAuthLogout<TData = PostAuthLogout200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postAuthLogout<TData = PostAuthLogout200>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postAuthLogout<TData = PostAuthLogout200>(
     options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/auth/logout`,undefined,options
    );
  }
/**
 * Issues student tokens if the authenticated user is allowed to act as the specified student (linked via contact email).
 * @summary Impersonate a student (parent login as child)
 */
 postAuthImpersonateStudentId<TData = PostAuthImpersonateStudentId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    postAuthImpersonateStudentId<TData = PostAuthImpersonateStudentId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    postAuthImpersonateStudentId<TData = PostAuthImpersonateStudentId200>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;postAuthImpersonateStudentId<TData = PostAuthImpersonateStudentId200>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `http://localhost:3193/v1/auth/impersonate/student/${id}`,undefined,options
    );
  }
};

export type PostAuthLoginClientResult = NonNullable<PostAuthLogin200>
export type PostAuthRegisterClientResult = NonNullable<PostAuthRegister201>
export type PostAuthRefreshClientResult = NonNullable<PostAuthRefresh200>
export type GetAuthVerifyEmailClientResult = NonNullable<GetAuthVerifyEmail200>
export type PostAuthForgotPasswordClientResult = NonNullable<PostAuthForgotPassword200>
export type PostAuthResetPasswordClientResult = NonNullable<PostAuthResetPassword200>
export type PostAuthLogoutClientResult = NonNullable<PostAuthLogout200>
export type PostAuthImpersonateStudentIdClientResult = NonNullable<PostAuthImpersonateStudentId200>
